[tool.poetry]
name = "dophon_manager"
version = "0.1.2r1"
description = ""
authors = ["CallMeE <ealohu@163.com>"]

[tool.poetry.dependencies]
python = "*"
toml = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.6"

[tool.poetry.scripts]
dophon_manager = "dophon_manager:main"