
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-18T15:48:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0b87ec11f16cd1eb14ca36de8c788bc34170d10",
 "version": "1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
