# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

install:
  - make ensure-pip-ci
  - make dev-ci

script:
  - make check
  - make requirements
  - make test

# after_success:
#   coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: stibbons
  distributions: sdist bdist_wheel
  password:
    secure: >
      K/UdLj7gYYOZ8B8RY0BsdOnHEo3l09gzjFcAH41oxC+kuKxHQCmOJ4Sm72yo5uBPAlxjuW0TKOkK5W4uiK+
      UZEpXWK5zvGNa3K+fZnhE9vNC2aPPq4XZc59MrXuDJQuTss2l47qdLo07981VA6f+ES1FnobR9jd6WiBHug
      bJpSe4B3Nn3Utq48U8hZKQRLeA3qvwcGP7B5CILAMiwP43UM8hYDrdAb4fwp9uD+7BCfHhx/MHfESwQyYb6
      hZkcHsqPwrQUCRU9SVUW4PZT7bB5e65BiZyuNP0FuueK3gCtgwfi/hCOnjvuO4QZKTMr6VAocvGIN7NJvrz
      RHnE8lGjNG/202I05ClNljymn6BwuG/WzlEQLJzmWpj8S7OPA7BWfLqyitf/zkZU5J69rjdyBmIkMuKUii+
      BVoy6+uNTHXDEA0ZX/aXGju3vrQsPQ/qCLdrf7NemyooWbjRg1DfBUP5jOjtzXnAYqnN8ez486TrH/tQ2ZZ
      w4P5tYoULzyP2sWMhJ6Y1UZJ9dcNl5TbIi7lcpak1/5zKBXLX3qywq36tgo6v6DpIhlDbqNfAMRKNCNb1AT
      ar21Xek5l92Ctf1ZLO1NdfeqkYj28h4y0BPy9P6pcAh6MaK9D2+dFxKw37wo+zbPOgjQ8E6EDe8UeQUUtRB
      5F8oo+4bHlDrIxN58NM=
  on:
    tags: true
    repo: gsemet/pipenv-to-requirements
    branch: master
