language: python
dist: xenial
sudo: true

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  global:
    - DEPENDS="numpy>=1.9.0 cython>=0.21 setuptools>=18.0 cftime"
    - NO_NET=1
    - MPI=0

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  allow_failures:
    - python: "3.8-dev"
  include:
    # Absolute minimum dependencies.
    - python: 2.7
      env:
        - DEPENDS="numpy==1.9.0 cython==0.21 ordereddict==1.1 setuptools==18.0 cftime"
    # test MPI
    - python: 2.7
      dist: trusty
      env: 
        - MPI=1
        - CC=mpicc
        - DEPENDS="numpy>=1.9.0 cython>=0.21 setuptools>=18.0 mpi4py>=1.3.1 cftime"
        - NETCDF_VERSION=4.6.1
        - NETCDF_DIR=$HOME
        - PATH=${NETCDF_DIR}/bin:${PATH} # pick up nc-config here
      addons:
        apt:
          packages:
            - openmpi-bin
            - libopenmpi-dev
            - libhdf5-openmpi-dev

notifications:
  email: false

before_install:
  - pip install Cython # workaround for pip bug
  - pip install $DEPENDS

install:
  - if [ $MPI -eq 1 ] ; then ci/travis/build-parallel-netcdf.sh; fi
  - python setup.py build
  - python setup.py install

script:
  - |
    if [ $MPI -eq 1 ] ; then
       cd examples
       mpirun -np 4 python mpi_example.py
       cd ..
    fi
  - cd test
  - python run_all.py
