- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs-nonvoting

    check:
      jobs:
        - requirements-check:
            voting: false
    gate:
      jobs:
        - requirements-check:
            voting: false
