[tool.poetry]
name = "speed-stack"
version = "0.1.1"
description = "This simplifies easy enhancements to python."
authors = ["austinv11 <austinv11@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["ujson", "uvloop", "fast", "speed", "drop-in"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.6"
uvloop = { version = "^0.11.2", optional = true, platform = '!windows' }
ujson = { version = "^1.35", optional = true }
python-rapidjson = { version = "^0.6.3", optional = true }
dill = { version = "^0.2.8", optional = true }
multiprocess = { version = "^0.70.6", optional = true }

[tool.poetry.extras]
uvloop = ["uvloop"]
ujson = ["ujson"]
rapidjson = ["python-rapidjson"]
dill = ["dill"]
multiprocess = ["dill", "multiprocess"]
recommended = ["uvloop", "ujson", "dill", "multiprocess"]

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
