stages:
  - test
  - upload
before_script:
  - apk add --update alpine-sdk gcc musl-dev libffi-dev openssl-dev

dev:tests python 3.6:
  image: library/python:3.6.5-alpine3.7
  stage: test
  script:
    - apk add python3-dev
    - python3 -m pip install tox
    - make test_py36
  except:
    - master
    - tags
  artifacts:
    paths:
    - report

dev:tests python 2.7:
  image: library/python:2.7.14-alpine3.7
  stage: test
  script:
    - apk add python2-dev
    - python -m pip install tox
    - make test_py27
  except:
    - master
    - tags
  artifacts:
    paths:
    - report

dev:upload:
  image: library/python:3.6.5-alpine3.7
  stage: upload
  only:
    - tags
  script:
    - make release

pages:
  image: library/python:3.6.5-alpine3.7
  stage: upload
  only:
    - master
  script:
    - make public
  artifacts:
    paths:
    - public    