language: python
python:
- '2.7'
install:
- pip install -U pbr tox-travis setuptools
script:
- tox
deploy:
  provider: pypi
  user: figo
  password:
    secure: Dodkqk0tqocKNneiJeWnE6xzHmj4mphFAjHw1HedM5K+3Xn15CXYZ1aQvF/T/vpGthT8M+3GtHBT9R/Rbq5Xwe9ItUQB9qaC9QQo5rAJTjVLl0aUyrtkgSes/hRObNIqinyMESqHWoN46Z4Z4nTJjoV0fJ6xXEx1ZrMXDVKDytmYQF/wDKVmTNtnnV+tnTQrDYQGU2cXTAV7OUkGE1aRCccMJWVGOnaBUPZAZPtigIRLNXLm/l5iqn8oO8m31KQj1DDrep1ZbWXrnvcH3RgiwelYvFi9BvutXKBbmayGExzIOGomJ08AQ8RXpzcCX5xdvZo3icxxLP2QbCKBAivg31Ohxh8Wu4tt+DjP1XRNb4gZE1bBw6ll9uzhINELLu8CVBkDQ6pWAXC/js7JFlyJZk+HU2mj0+mVepo6f1+oAvd9UmhK1ZEG87JmXUHjOzm8xe8Y2lD37vplqSSyEhUbD6ZYsz1+oHyVUA0xkd0NtK8tV5t7VZusiYfwDvOfiV+O3Uc9q2ev8kIEQOvYXR1SjzzU97p4UZ8rH5Jy7q2KsTfw+TZm88H98BNth37G0eQ2IS4TDpd36C/dbvLONvKGCtT5Mkdjel+Vnc09IomO8QWmLToFyf5YBkK2vUwg5NOTXcEIUfKQT6VhE9BhC/AX9QGiSdT/K3KTBzOx3Zo6p0U=
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    repo: figome/python-festung
