package:
  name: pypng
  version: '0.0.18'

source:
  git_url: https://github.com/drj11/pypng.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - png

about:
  home: https://github.com/drj11/pypng
  license: MIT
  summary: Pure Python PNG image encoder/decoder
