# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PlaceDigestPlaceDigestNormalizedYearlyResponseDTOCommodityDataDTO(Model):
    """PlaceDigestPlaceDigestNormalizedYearlyResponseDTOCommodityDataDTO.

    :param commodity_code: The commodity code
    :type commodity_code: str
    :param commodity_info: The commodity info
    :type commodity_info: str
    :param commodity_id: The commodity identifier
    :type commodity_id: int
    :param target_comparison: The target year info
    :type target_comparison:
     ~energycap.sdk.models.PlaceDigestPlaceDigestNormalizedYearlyResponseDTOTargetComparisonDTO
    :param common_use_unit: The common use unit of measure
    :type common_use_unit: ~energycap.sdk.models.UnitUnitChildDTO
    :param results: An array of yearly data
    :type results:
     list[~energycap.sdk.models.PlaceDigestPlaceDigestNormalizedYearlyResponseDTOCommodityResultsDTO]
    """

    _attribute_map = {
        'commodity_code': {'key': 'commodityCode', 'type': 'str'},
        'commodity_info': {'key': 'commodityInfo', 'type': 'str'},
        'commodity_id': {'key': 'commodityId', 'type': 'int'},
        'target_comparison': {'key': 'targetComparison', 'type': 'PlaceDigestPlaceDigestNormalizedYearlyResponseDTOTargetComparisonDTO'},
        'common_use_unit': {'key': 'commonUseUnit', 'type': 'UnitUnitChildDTO'},
        'results': {'key': 'results', 'type': '[PlaceDigestPlaceDigestNormalizedYearlyResponseDTOCommodityResultsDTO]'},
    }

    def __init__(self, commodity_code=None, commodity_info=None, commodity_id=None, target_comparison=None, common_use_unit=None, results=None):
        super(PlaceDigestPlaceDigestNormalizedYearlyResponseDTOCommodityDataDTO, self).__init__()
        self.commodity_code = commodity_code
        self.commodity_info = commodity_info
        self.commodity_id = commodity_id
        self.target_comparison = target_comparison
        self.common_use_unit = common_use_unit
        self.results = results
