# Generated by Django 2.1 on 2018-08-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0002_auto_20180813_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcheck',
            name='is_published',
        ),
        migrations.AddField(
            model_name='factcheck',
            name='status',
            field=models.CharField(choices=[('dft', 'Draft'), ('fil', 'Filed'), ('pub', 'Published')], default='dft', max_length=3),
        ),
    ]
