# Generated by Django 2.0.7 on 2018-08-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_definindo_parametro_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameterforbase',
            options={'verbose_name': 'Parametro para o Core', 'verbose_name_plural': 'Parametros para o Core'},
        ),
    ]
