# Generated by Django 2.0.7 on 2018-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180816_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterforbase',
            name='iconeProjeto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
