# Generated by Django 2.0.7 on 2018-08-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180823_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterforbase',
            name='descricaoProjeto',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='parameterforbase',
            name='iconeProjeto',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='parameterforbase',
            name='nomeProjeto',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='parameterforbase',
            name='tituloProjeto',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
