# Generated by Django 2.0.7 on 2018-09-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180823_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterforbase',
            name='login_redirect_url',
            field=models.CharField(blank=True, default='/core/', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='parameterforbase',
            name='login_url',
            field=models.CharField(blank=True, default='/core/login/', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='parameterforbase',
            name='logout_redirect_url',
            field=models.CharField(blank=True, default='/core/login/', max_length=250, null=True),
        ),
    ]
