# Generated by Django 2.0.7 on 2018-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180927_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersuser',
            name='bloquear_sequencia_caracter',
            field=models.BooleanField(default=True, help_text='Bloqueia sequência de caracteres no campo de senha', verbose_name='Bloquear sequência de caracteres'),
        ),
    ]
