# Generated by Django 2.0.7 on 2018-10-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181001_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersuser',
            name='bloquear_sequencia_caracter',
            field=models.BooleanField(default=True, help_text='Bloqueia sequência de caracteres no campo de senha', verbose_name='Bloquear sequências de caracteres'),
        ),
        migrations.AlterField(
            model_name='parametersuser',
            name='combinar_numero_caracter',
            field=models.BooleanField(default=True, verbose_name='Combinar Letras e Numeros'),
        ),
        migrations.AlterField(
            model_name='parametersuser',
            name='mim_tamanho',
            field=models.IntegerField(default=8, verbose_name='Quantidade mínima de caracteres'),
        ),
        migrations.AlterField(
            model_name='parametersuser',
            name='qtde_caracter',
            field=models.IntegerField(default=2, verbose_name='Quantidade mínima de letras'),
        ),
    ]
