# Generated by Django 2.0.7 on 2018-10-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181002_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersuser',
            name='max_tamanho',
            field=models.IntegerField(default=30, help_text='Tamanho máximo da senha', verbose_name='Quantidade máxima de caracteres'),
        ),
        migrations.AlterField(
            model_name='parametersuser',
            name='mim_tamanho',
            field=models.IntegerField(default=8, help_text='Tamanho mínimo da senha', verbose_name='Quantidade mínima de caracteres'),
        ),
    ]
