# Generated by Django 2.1.2 on 2018-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181002_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobase',
            name='prodata',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
