# Generated by Django 2.1.2 on 2018-10-12 15:07

from django.db import migrations, models


def load_stores_from_sql():
    import os
    sql_statements = open(os.path.join(os.path.dirname(os.path.dirname(__file__)),
                                       'utils/sql/iran_cities_farsi.sql'),
                          encoding="utf8")
    return sql_statements


def delete_stores_with_sql():
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IranCitiesFarsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('province', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunSQL(load_stores_from_sql(), delete_stores_with_sql()),
    ]
