# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RateDigestRateDigestActualYearlyResponseDTO(Model):
    """RateDigestRateDigestActualYearlyResponseDTO.

    :param name: The rate name
    :type name: str
    :param rate_id: The rate identifier
    :type rate_id: int
    :param global_use_unit: The use unit of measure
    :type global_use_unit: ~energycap.sdk.models.UnitUnitChildDTO
    :param cost_unit: The cost unit of measure
    :type cost_unit: ~energycap.sdk.models.UnitUnitChildDTO
    :param updated: The date and time the data was updated
    :type updated: datetime
    :param results: An array of yearly data
    :type results:
     list[~energycap.sdk.models.RateDigestRateDigestActualYearlyResponseDTOResultsDTO]
    :param commodities: An array of yearly data per commodity
    :type commodities:
     list[~energycap.sdk.models.RateDigestRateDigestActualYearlyResponseDTOCommodityDataDTO]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'rate_id': {'key': 'rateId', 'type': 'int'},
        'global_use_unit': {'key': 'globalUseUnit', 'type': 'UnitUnitChildDTO'},
        'cost_unit': {'key': 'costUnit', 'type': 'UnitUnitChildDTO'},
        'updated': {'key': 'updated', 'type': 'iso-8601'},
        'results': {'key': 'results', 'type': '[RateDigestRateDigestActualYearlyResponseDTOResultsDTO]'},
        'commodities': {'key': 'commodities', 'type': '[RateDigestRateDigestActualYearlyResponseDTOCommodityDataDTO]'},
    }

    def __init__(self, name=None, rate_id=None, global_use_unit=None, cost_unit=None, updated=None, results=None, commodities=None):
        super(RateDigestRateDigestActualYearlyResponseDTO, self).__init__()
        self.name = name
        self.rate_id = rate_id
        self.global_use_unit = global_use_unit
        self.cost_unit = cost_unit
        self.updated = updated
        self.results = results
        self.commodities = commodities
