# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UnitSystemCommodityMismatchChildDTO(Model):
    """UnitSystemCommodityMismatchChildDTO.

    :param commodity:
    :type commodity: ~energycap.sdk.models.CommoditiesCommodityChildDTO
    :param count:
    :type count: int
    """

    _attribute_map = {
        'commodity': {'key': 'commodity', 'type': 'CommoditiesCommodityChildDTO'},
        'count': {'key': 'count', 'type': 'int'},
    }

    def __init__(self, commodity=None, count=None):
        super(UnitSystemCommodityMismatchChildDTO, self).__init__()
        self.commodity = commodity
        self.count = count
