language: python

dist: trusty

env:
  - PYTHON=2.7

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libqt4-core
      - libqt4-gui
      - python-qt4

matrix:
  fast_finish: true
  exclude:
    - os: osx
  include:
    - os: osx
      language: generic
      python: "2.7"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export CONDA_OS=MacOSX;
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-${CONDA_OS}-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda info -a;
      conda install pyqt=4;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/PyQt4
              $VIRTUAL_ENV/lib/python2.7/site-packages;
        ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/sip*
              $VIRTUAL_ENV/lib/python2.7/site-packages;
    fi
  - pip install -r requirements.txt
  - python setup.py install


before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script: python setup.py test

deploy:
  - provider: pypi
    user: statoil-travis
    distributions: bdist_wheel sdist
    on:
      tags: true
    password:
      secure: Yy4V9djnr+tG/VXLXc1EkLuALxgpSURS8TQKm/8D5bmm83Xxry7ocy7WX0vQcsAW58zZ5DTFJzkwvhzlGPr+YPvioIQ5nr/fI0BHrQglZxYZsglJWHL/g0AnWM2olkSKQM8lUXyD+B8BfzSnM0Jt5S8A7EXuiFMcQbTjOLegCXyJAykAcdnXBWi5TO+Y57e4XovQmVh/t7iLOw//ZuLzVmcbKsUALrEZkH+xlXs7TfgwDx9aCS4yTL69lDs7palqy+dqybZY0qlFk6KwJvJOJXR9PzKhX+IPpBf6gquCaC6/4iSlyBLegDieZLfkCeSH7mYj2ewff9ieXUlaO+mdnpPnjKQ5ricsrnUw462RgpPbqQyRQb9u2a4FoklFc0ukzYV6ozO6IiuCNWI/VLetnMJj0tQNRjpYJGlp0vrm50gIX08h0M8MHSEnXms7Q4RDu1l8rj96p2UF/Ha8EtfJ1MoE+RKU/ua2DdPswzp6bcjjw5NiVGKB5ntupTZkVlrWVUh9ClQ8NqAQK0vxGzrPaC2fwzfBT7Gs8s1NxM+3inVP2K3pOcYs5u5vSJ5tPo6bgoK159IByQBEp+fug8TXWbbF+LSPg77mFjRacTpkqSmJSRNNXKOcbtVjq7w0M1FXxVgew1/iCdbKqxpKiwAyDlx8989KtM1bl2SOUbP39C4=
