# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/python/auxygen/auxygen/gui/ui/ui_wlakeshore.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WLakeshore(object):
    def setupUi(self, WLakeshore):
        WLakeshore.setObjectName("WLakeshore")
        WLakeshore.resize(995, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lakeshore"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WLakeshore.setWindowIcon(icon)
        WLakeshore.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(WLakeshore)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(WLakeshore)
        self.tabWidget.setObjectName("tabWidget")
        self.tabStatus = QtWidgets.QWidget()
        self.tabStatus.setObjectName("tabStatus")
        self.tabWidget.addTab(self.tabStatus, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.formLayout = QtWidgets.QFormLayout(self.tabSettings)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tabSettings)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.editAddress = QtWidgets.QLineEdit(self.tabSettings)
        self.editAddress.setObjectName("editAddress")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editAddress)
        self.label_10 = QtWidgets.QLabel(self.tabSettings)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtWidgets.QLabel(self.tabSettings)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioA = QtWidgets.QRadioButton(self.tabSettings)
        self.radioA.setChecked(True)
        self.radioA.setObjectName("radioA")
        self.groupStoreSensor = QtWidgets.QButtonGroup(WLakeshore)
        self.groupStoreSensor.setObjectName("groupStoreSensor")
        self.groupStoreSensor.addButton(self.radioA)
        self.horizontalLayout_4.addWidget(self.radioA)
        self.radioB = QtWidgets.QRadioButton(self.tabSettings)
        self.radioB.setObjectName("radioB")
        self.groupStoreSensor.addButton(self.radioB)
        self.horizontalLayout_4.addWidget(self.radioB)
        self.radioC = QtWidgets.QRadioButton(self.tabSettings)
        self.radioC.setObjectName("radioC")
        self.groupStoreSensor.addButton(self.radioC)
        self.horizontalLayout_4.addWidget(self.radioC)
        self.radioD = QtWidgets.QRadioButton(self.tabSettings)
        self.radioD.setObjectName("radioD")
        self.groupStoreSensor.addButton(self.radioD)
        self.horizontalLayout_4.addWidget(self.radioD)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.editTempError = QtWidgets.QLineEdit(self.tabSettings)
        self.editTempError.setObjectName("editTempError")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editTempError)
        self.editTimeout = QtWidgets.QLineEdit(self.tabSettings)
        self.editTimeout.setObjectName("editTimeout")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editTimeout)
        self.label_11 = QtWidgets.QLabel(self.tabSettings)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.tabWidget.addTab(self.tabSettings, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startButton = QtWidgets.QPushButton(WLakeshore)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon1)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_9.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(WLakeshore)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/stop"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_9.addWidget(self.stopButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.clearButton = QtWidgets.QPushButton(WLakeshore)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)

        self.retranslateUi(WLakeshore)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WLakeshore)

    def retranslateUi(self, WLakeshore):
        _translate = QtCore.QCoreApplication.translate
        WLakeshore.setWindowTitle(_translate("WLakeshore", "Lakeshore"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("WLakeshore", "Status"))
        self.label.setText(_translate("WLakeshore", "Address"))
        self.label_10.setText(_translate("WLakeshore", "Temperature error"))
        self.label_12.setText(_translate("WLakeshore", "Store sensor"))
        self.radioA.setText(_translate("WLakeshore", "A"))
        self.radioB.setText(_translate("WLakeshore", "B"))
        self.radioC.setText(_translate("WLakeshore", "C"))
        self.radioD.setText(_translate("WLakeshore", "D"))
        self.label_11.setText(_translate("WLakeshore", "Communication timeout"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("WLakeshore", "Settings"))
        self.startButton.setText(_translate("WLakeshore", "Connect"))
        self.stopButton.setText(_translate("WLakeshore", "Disconnect"))
        self.clearButton.setText(_translate("WLakeshore", "Clear"))

from . import resources_rc
