# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/python/auxygen/auxygen/gui/ui/ui_wiseg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WIseg(object):
    def setupUi(self, WIseg):
        WIseg.setObjectName("WIseg")
        WIseg.resize(1275, 1191)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iseg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WIseg.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(WIseg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(WIseg)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDevice = QtWidgets.QWidget()
        self.tabDevice.setObjectName("tabDevice")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabDevice)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabDevice)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.labelKillFlag = QtWidgets.QLabel(self.groupBox_2)
        self.labelKillFlag.setObjectName("labelKillFlag")
        self.gridLayout.addWidget(self.labelKillFlag, 5, 1, 1, 1)
        self.labelHVFlag = QtWidgets.QLabel(self.groupBox_2)
        self.labelHVFlag.setObjectName("labelHVFlag")
        self.gridLayout.addWidget(self.labelHVFlag, 3, 1, 1, 1)
        self.labelInhibitFlag = QtWidgets.QLabel(self.groupBox_2)
        self.labelInhibitFlag.setObjectName("labelInhibitFlag")
        self.gridLayout.addWidget(self.labelInhibitFlag, 4, 1, 1, 1)
        self.labelRemoteFlag = QtWidgets.QLabel(self.groupBox_2)
        self.labelRemoteFlag.setObjectName("labelRemoteFlag")
        self.gridLayout.addWidget(self.labelRemoteFlag, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.labelExceeded_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelExceeded_2.setObjectName("labelExceeded_2")
        self.gridLayout.addWidget(self.labelExceeded_2, 8, 0, 1, 1)
        self.labelMaxCurrent1 = QtWidgets.QLabel(self.groupBox_2)
        self.labelMaxCurrent1.setObjectName("labelMaxCurrent1")
        self.gridLayout.addWidget(self.labelMaxCurrent1, 9, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(self.groupBox_2)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 0, 1, 1)
        self.labelExceeded = QtWidgets.QLabel(self.groupBox_2)
        self.labelExceeded.setObjectName("labelExceeded")
        self.gridLayout.addWidget(self.labelExceeded, 6, 0, 1, 1)
        self.labelMaxVoltage1 = QtWidgets.QLabel(self.groupBox_2)
        self.labelMaxVoltage1.setObjectName("labelMaxVoltage1")
        self.gridLayout.addWidget(self.labelMaxVoltage1, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.labelExceededFlag = QtWidgets.QLabel(self.groupBox_2)
        self.labelExceededFlag.setObjectName("labelExceededFlag")
        self.gridLayout.addWidget(self.labelExceededFlag, 6, 1, 1, 1)
        self.labelPolarityFlag = QtWidgets.QLabel(self.groupBox_2)
        self.labelPolarityFlag.setObjectName("labelPolarityFlag")
        self.gridLayout.addWidget(self.labelPolarityFlag, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.labelRamp = QtWidgets.QLabel(self.groupBox_2)
        self.labelRamp.setObjectName("labelRamp")
        self.gridLayout.addWidget(self.labelRamp, 8, 1, 1, 1)
        self.labelMaxCurrent = QtWidgets.QLabel(self.groupBox_2)
        self.labelMaxCurrent.setObjectName("labelMaxCurrent")
        self.gridLayout.addWidget(self.labelMaxCurrent, 9, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.labelMaxVoltage = QtWidgets.QLabel(self.groupBox_2)
        self.labelMaxVoltage.setObjectName("labelMaxVoltage")
        self.gridLayout.addWidget(self.labelMaxVoltage, 10, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabDevice)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 2)
        self.sbRamp = QtWidgets.QSpinBox(self.groupBox_4)
        self.sbRamp.setMinimum(2)
        self.sbRamp.setMaximum(255)
        self.sbRamp.setObjectName("sbRamp")
        self.gridLayout_3.addWidget(self.sbRamp, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 2)
        self.buttonToSeq = QtWidgets.QPushButton(self.groupBox_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/macro"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonToSeq.setIcon(icon1)
        self.buttonToSeq.setObjectName("buttonToSeq")
        self.gridLayout_3.addWidget(self.buttonToSeq, 3, 1, 1, 2)
        self.sbVoltage = QtWidgets.QSpinBox(self.groupBox_4)
        self.sbVoltage.setMaximum(2000)
        self.sbVoltage.setObjectName("sbVoltage")
        self.gridLayout_3.addWidget(self.sbVoltage, 0, 2, 1, 1)
        self.buttonRun = QtWidgets.QPushButton(self.groupBox_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRun.setIcon(icon2)
        self.buttonRun.setObjectName("buttonRun")
        self.gridLayout_3.addWidget(self.buttonRun, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabDevice)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelStatus = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(10)
        self.labelStatus.setFont(font)
        self.labelStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout_4.addWidget(self.labelStatus, 0, 0, 1, 1)
        self.labelVoltage = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        self.labelVoltage.setFont(font)
        self.labelVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVoltage.setObjectName("labelVoltage")
        self.gridLayout_4.addWidget(self.labelVoltage, 1, 0, 1, 1)
        self.plotVoltage = GraphicsLayoutWidget(self.groupBox_3)
        self.plotVoltage.setObjectName("plotVoltage")
        self.gridLayout_4.addWidget(self.plotVoltage, 2, 0, 1, 1)
        self.labelCurrent = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        self.labelCurrent.setFont(font)
        self.labelCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrent.setObjectName("labelCurrent")
        self.gridLayout_4.addWidget(self.labelCurrent, 3, 0, 1, 1)
        self.plotCurrent = GraphicsLayoutWidget(self.groupBox_3)
        self.plotCurrent.setObjectName("plotCurrent")
        self.gridLayout_4.addWidget(self.plotCurrent, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 3, 1)
        self.tabWidget.addTab(self.tabDevice, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.formLayout = QtWidgets.QFormLayout(self.tabSettings)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.tabSettings)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.editAddress = QtWidgets.QLineEdit(self.tabSettings)
        self.editAddress.setObjectName("editAddress")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editAddress)
        self.label_9 = QtWidgets.QLabel(self.tabSettings)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.editError = QtWidgets.QLineEdit(self.tabSettings)
        self.editError.setObjectName("editError")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editError)
        self.label_11 = QtWidgets.QLabel(self.tabSettings)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.editComTimeout = QtWidgets.QLineEdit(self.tabSettings)
        self.editComTimeout.setObjectName("editComTimeout")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editComTimeout)
        self.label_12 = QtWidgets.QLabel(self.tabSettings)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioA = QtWidgets.QRadioButton(self.tabSettings)
        self.radioA.setObjectName("radioA")
        self.horizontalLayout_2.addWidget(self.radioA)
        self.radioB = QtWidgets.QRadioButton(self.tabSettings)
        self.radioB.setObjectName("radioB")
        self.horizontalLayout_2.addWidget(self.radioB)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabSettings, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonConnect = QtWidgets.QPushButton(WIseg)
        self.buttonConnect.setObjectName("buttonConnect")
        self.horizontalLayout.addWidget(self.buttonConnect)
        self.buttonDisconnect = QtWidgets.QPushButton(WIseg)
        self.buttonDisconnect.setObjectName("buttonDisconnect")
        self.horizontalLayout.addWidget(self.buttonDisconnect)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonClose = QtWidgets.QPushButton(WIseg)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(WIseg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WIseg)
        WIseg.setTabOrder(self.sbVoltage, self.sbRamp)
        WIseg.setTabOrder(self.sbRamp, self.buttonRun)
        WIseg.setTabOrder(self.buttonRun, self.buttonToSeq)
        WIseg.setTabOrder(self.buttonToSeq, self.buttonConnect)
        WIseg.setTabOrder(self.buttonConnect, self.buttonDisconnect)
        WIseg.setTabOrder(self.buttonDisconnect, self.buttonClose)
        WIseg.setTabOrder(self.buttonClose, self.editComTimeout)
        WIseg.setTabOrder(self.editComTimeout, self.editError)
        WIseg.setTabOrder(self.editError, self.tabWidget)
        WIseg.setTabOrder(self.tabWidget, self.editAddress)

    def retranslateUi(self, WIseg):
        _translate = QtCore.QCoreApplication.translate
        WIseg.setWindowTitle(_translate("WIseg", "Iseg NHQ"))
        self.groupBox_2.setTitle(_translate("WIseg", "Module status"))
        self.label.setText(_translate("WIseg", "Remote control:"))
        self.labelKillFlag.setText(_translate("WIseg", "0"))
        self.labelHVFlag.setText(_translate("WIseg", "0"))
        self.labelInhibitFlag.setText(_translate("WIseg", "0"))
        self.labelRemoteFlag.setText(_translate("WIseg", "0"))
        self.label_3.setText(_translate("WIseg", "High voltage:"))
        self.label_6.setText(_translate("WIseg", "Kill switch:"))
        self.labelExceeded_2.setText(_translate("WIseg", "Actual ramp (V/s):"))
        self.labelMaxCurrent1.setText(_translate("WIseg", "Max current (mA):"))
        self.labelName.setText(_translate("WIseg", "Iseg NHQ"))
        self.labelExceeded.setText(_translate("WIseg", "Voltage exceeded:"))
        self.labelMaxVoltage1.setText(_translate("WIseg", "Max voltage (V):"))
        self.label_5.setText(_translate("WIseg", "Inhibit switch:"))
        self.labelExceededFlag.setText(_translate("WIseg", "0"))
        self.labelPolarityFlag.setText(_translate("WIseg", "0"))
        self.label_2.setText(_translate("WIseg", "Polarity:"))
        self.labelRamp.setText(_translate("WIseg", "0"))
        self.labelMaxCurrent.setText(_translate("WIseg", "0"))
        self.labelMaxVoltage.setText(_translate("WIseg", "0"))
        self.groupBox_4.setTitle(_translate("WIseg", "Control"))
        self.label_7.setText(_translate("WIseg", "Voltage:"))
        self.label_8.setText(_translate("WIseg", "Ramp:"))
        self.buttonToSeq.setText(_translate("WIseg", "To Sequence"))
        self.buttonRun.setText(_translate("WIseg", "Run"))
        self.groupBox_3.setTitle(_translate("WIseg", "Actual state"))
        self.labelStatus.setText(_translate("WIseg", "Status unknown"))
        self.labelVoltage.setText(_translate("WIseg", "Voltage: 0 V"))
        self.labelCurrent.setText(_translate("WIseg", "Current: 0 mA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDevice), _translate("WIseg", "Device"))
        self.label_4.setText(_translate("WIseg", "Cryoproxy address"))
        self.label_9.setText(_translate("WIseg", "Voltage error"))
        self.label_11.setText(_translate("WIseg", "Communication timeout"))
        self.label_12.setText(_translate("WIseg", "Channel"))
        self.radioA.setText(_translate("WIseg", "A (&1)"))
        self.radioB.setText(_translate("WIseg", "B (&2)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("WIseg", "Settings"))
        self.buttonConnect.setText(_translate("WIseg", "Connect"))
        self.buttonDisconnect.setText(_translate("WIseg", "Disconnect"))
        self.buttonClose.setText(_translate("WIseg", "Close"))

from pyqtgraph import GraphicsLayoutWidget
from . import resources_rc
