---
- name: Checking for journald.conf
  stat: path=/etc/systemd/journald.conf
  register: journald_conf_file

- name: Update journald setup
  replace:
    dest: /etc/systemd/journald.conf
    regexp: '^(\#| )?{{ item.var }}=\s*.*?$'
    replace: ' {{ item.var }}={{ item.val }}'
    backup: yes
  with_items: "{{ journald_options | default([]) }}"
  when: journald_conf_file.stat.exists
  register: journald_update

- name: Restart journald
  systemd:
    name: systemd-journald
    state: restarted
  when: journald_update|changed
