# automatically generated by the FlatBuffers compiler, do not modify

# namespace: lumby_fbs

import flatbuffers

# /// Allows to manipulate a `OrderUpdateVec` without unpacking it.
# /// If you want to serialize a large amount of `OrderUpdate` without acessing
# /// the underlying data, this is what you should use.
class NestedOrderUpdateVec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNestedOrderUpdateVec(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NestedOrderUpdateVec()
        x.Init(buf, n + offset)
        return x

    # NestedOrderUpdateVec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NestedOrderUpdateVec
    def Vec(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .NestedOrderUpdate import NestedOrderUpdate
            obj = NestedOrderUpdate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NestedOrderUpdateVec
    def VecLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def NestedOrderUpdateVecStart(builder): builder.StartObject(1)
def NestedOrderUpdateVecAddVec(builder, vec): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vec), 0)
def NestedOrderUpdateVecStartVecVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def NestedOrderUpdateVecEnd(builder): return builder.EndObject()
