# automatically generated by the FlatBuffers compiler, do not modify

# namespace: lumby_fbs

import flatbuffers

# /// A message regarding a trade.
class TradeUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTradeUpdate(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TradeUpdate()
        x.Init(buf, n + offset)
        return x

    # TradeUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TradeUpdate
    def BfxTradeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TradeUpdate
    def Trade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .Trade import Trade
            obj = Trade()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TradeUpdateStart(builder): builder.StartObject(2)
def TradeUpdateAddBfxTradeType(builder, bfxTradeType): builder.PrependInt8Slot(0, bfxTradeType, 0)
def TradeUpdateAddTrade(builder, trade): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(trade), 0)
def TradeUpdateEnd(builder): return builder.EndObject()
