
# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
language: python
python:
  - "2.7"
before_install:
    echo 'apt-get install -y libxml2 libxslt1-dev'
install:
  - pip install requests
  - pip install lxml
  - pip install sftpserver
  - pip install coveralls

script: make test

after_success:
    - coveralls


branches:
  only:
    - master
    - develop
