[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "troposphere_crunch"
author = "Josh Klar"
author-email = "josh@klar.sh"
home-page = "https://github.com/klardotsh/troposphere-crunch"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = [
	"troposphere",
	"toml",
	"tqdm",
]

[tool.flit.scripts]
"troposphere-crunch" = "troposphere_crunch.main:main"
