
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-10T09:55:27-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "689961d5cae4f0a996a56de463793175b0582a3d",
 "version": "v1.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
