# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AccountDigestAccountDigestActualMonthlyResponseDTO(Model):
    """AccountDigestAccountDigestActualMonthlyResponseDTO.

    :param account_code: The account code
    :type account_code: str
    :param account_info: The account info
    :type account_info: str
    :param account_id: The account identifier
    :type account_id: int
    :param updated: The date and time the data was updated
    :type updated: datetime
    :param global_use_unit: The use unit of measure
    :type global_use_unit: ~energycap.sdk.models.UnitUnitChildDTO
    :param cost_unit: The bodyline's cost unit of measure for this
    :type cost_unit: ~energycap.sdk.models.UnitUnitChildDTO
    :param commodities: An array of monthly data per commodity
    :type commodities:
     list[~energycap.sdk.models.AccountDigestAccountDigestActualMonthlyResponseDTOCommodityDataDTO]
    :param results: An array of monthly data
    :type results:
     list[~energycap.sdk.models.AccountDigestAccountDigestActualMonthlyResponseDTOResultsDTO]
    """

    _attribute_map = {
        'account_code': {'key': 'accountCode', 'type': 'str'},
        'account_info': {'key': 'accountInfo', 'type': 'str'},
        'account_id': {'key': 'accountId', 'type': 'int'},
        'updated': {'key': 'updated', 'type': 'iso-8601'},
        'global_use_unit': {'key': 'globalUseUnit', 'type': 'UnitUnitChildDTO'},
        'cost_unit': {'key': 'costUnit', 'type': 'UnitUnitChildDTO'},
        'commodities': {'key': 'commodities', 'type': '[AccountDigestAccountDigestActualMonthlyResponseDTOCommodityDataDTO]'},
        'results': {'key': 'results', 'type': '[AccountDigestAccountDigestActualMonthlyResponseDTOResultsDTO]'},
    }

    def __init__(self, account_code=None, account_info=None, account_id=None, updated=None, global_use_unit=None, cost_unit=None, commodities=None, results=None):
        super(AccountDigestAccountDigestActualMonthlyResponseDTO, self).__init__()
        self.account_code = account_code
        self.account_info = account_info
        self.account_id = account_id
        self.updated = updated
        self.global_use_unit = global_use_unit
        self.cost_unit = cost_unit
        self.commodities = commodities
        self.results = results
