
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-14T00:09:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d2e8eea9d729c187a7e390824e62ee3d9649c28",
 "version": "v1.2.3-1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
