binary_sensor:
  - platform: mqtt
    state_topic: ais/mic/sensor
    name: ais_remote_mic
  - platform: mqtt
    state_topic: ais/button/sensor
    name: ais_remote_button
  - platform: mqtt
    state_topic: ais/button/sensor
    name: selected_entity
#  - platform: mqtt
#    state_topic: ais/secure_android_id/sensor
#    name: secure_android_id


sensor:
  - platform: ais_android_cmd
    name: current_host_name
    command: "getprop net.hostname"
#  - platform: template
#    sensors:
#      certification_info:
#        value_template: To urządzenie do pełnego działania (komendy głosowe, synteza mowy) wymaga usług Google Android.
#                        Zarejestruj swoje urządzenie, przesyłając jego identyfikator do Google Android by bezpiecznie kożystać z pełnej funkcjonalności urządzenia.
  - platform: template
    sensors:
      network_devices_info:
        value_template: "Po wykryciu urządzenia możesz kliknąć w jego link by przejść do ustawień urządzenia.\n#UWAGA: Zmieniaj ustawienia urządzenia tylko gdy jesteś pewny, że wiesz co robisz!"
  - platform: ais_device_search_mqtt
    name: network_devices_info_value
    state_topic: "stat/#"
  - platform: template
    sensors:
      ssh_connection_info:
        value_template: "Na urządzeniu działa serwer ssh, aby połączyć się do konsoli AIS dom należy:\n
                        - pobrać autoryzowany klucz ssh (poniżej)\n
                        - w swojej konsoli wpisać:\n\n
                        @ssh ais-dom -p 8022 -i <ścieżka do klucza ssh>\n
                        $*ais-dom to nazwa hosta systemu AIS dom"
  - platform: template
    sensors:
      ftp_connection_info:
        value_template: "Na urządzeniu działa też serwer ftp, umożliwiający wymianę plików (np. muzycznych), serwer dostępny jest pod adresem:\n
                        @ftp://ais-dom:1024\n
                        $*ais-dom to nazwa hosta systemu AIS dom"
  - platform: template
    sensors:
      host_name_dev_info:
        value_template: "ais-dom - z taką domyślną nazwą hosta komunikują się urządzenia w systemie AIS dom.\n
                        Możesz zmienić nazwę hosta na inną ale pamiętaj, żeby zmienić też konfigurację urządzeń.\n
                        # UWAGA: Żeby zmiana była widoczna wymagany będzie restart!"

  - platform: template
    sensors:
      https_connection_info:
        value_template: "Komunikaja z serwerem WWW AIS dom a Twoją przeglądarką jest szyfrowana - protokół https.\n
                        @https://ais-dom:8123 lub https://localhost:8123\n
                        Zainstaluj poniższy certyfikat w swoim systemie/przeglądarce by dodać do zaufanych hosty: localhost i ais-dom."

input_text:
  new_host_name:
    name: Nowa nazwa hosta
    initial: ais-dom
  buttons_ais_remote:
    name: Buttons AIS Remote

input_select:
  assistant_voice:
    name: "Głos"
    options:
      - "Kobieta online"
      - "Kobieta lokalnie"
      - "Kobieta 1"
      - "Kobieta 2"
      - "Kobieta 3"
      - "Mężczyzna 1"
      - "Mężczyzna 2"
      - "Mężczyzna 3"
    icon: mdi:voice
    initial: "Kobieta lokalnie"
  tts_player:
    name: 'Powiadamiaj dodatkowo'
    options:
      - "-"
    initial: "-"
    icon: mdi:cellphone-message
input_number:
  assistant_rate:
    name: "Szybkość mowy"
    min: 0.1
    max: 2
    step: 0.1
    initial: 1
  assistant_tone:
    name: "Ton mowy"
    min: 0.1
    max: 2
    step: 0.1
    initial: 1

group:
  ais_tts_configuration:
    name: Zamiana tekstu na mowę
    control: hidden
    entities:
      - input_select.assistant_voice
      - input_number.assistant_rate
      - input_number.assistant_tone
      - input_select.tts_player
  AIS Pilot:
    name: Pilot
    control: hidden
    entities:
      - input_text.buttons_ais_remote
      - binary_sensor.ais_remote_mic
      - binary_sensor.ais_remote_button
      - binary_sensor.selected_entity
  ais_host_rename:
    name: Zmiana nazwy hosta
    control: hidden
    entities:
      - sensor.host_name_dev_info
      - sensor.current_host_name
      - input_text.new_host_name
      - script.ais_change_host_name
#  ais_android_certification:
#    name: Certyfikacja urządzenia
#    entities:
#      - sensor.certification_info
#      - script.ais_getsecure_android_id
#      - binary_sensor.secure_android_id
#      - weblink.uncertified_android_registration
  ais_dev_ssh:
    name: Zdalny dostęp
    entities:
      - sensor.https_connection_info
      - weblink.https_localhost_cert
      - sensor.ssh_connection_info
      - weblink.klucz_ssh
      - sensor.ftp_connection_info
      - weblink.ftp_url

  ais_devices_in_network:
    name: Urządzenia w Twojej sieci
    control: hidden
    entities:
      - sensor.network_devices_info
      - sensor.network_devices_info_value
      - script.ais_scan_network_devices
