sensor:
  # - platform: speedtest
  #   monitored_conditions:
  #     - ping
  #     - download
  #     - upload
  - platform: template
    sensors:
      ais_connect_iot_device_info:
        value_template: "a) podłącz urządzenie do prądu\n
                        b) uruchom 'Skanuj w poszukiwaniu nowych urządzeń'\n
                        c) wybierz sieć wifi, jeśli podłączasz urządzenie do zabezpieczonej sieci to podaj też hasło\n
                        d) podaj nazwę dla nowego urządzenia i uruchom 'Dołącz nowe urządzenie'"
  - platform: ais_android_cmd
    command: getprop net.hostname
    name: local_host_name
    scan_interval: 360
  - platform: command_line
    command: python3 -c "import socket; print((([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2]
              if not ip.startswith('127.')] or [[(s.connect(('8.8.8.8', 53)),
              s.getsockname()[0], s.close()) for s in
              [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]])
              + ['no IP found'])[0])"
    name: internal_ip_address
    scan_interval: 360
  - platform: ais_long_text
    name: ais_rss_help_text
    package: homeassistant.components.ais_cloud
    method: get_rss_help_text
#  - platform: command_line
#    command: curl ipinfo.io/ip
#    name: external_ip_address
#    scan_interval: 360
#  - platform: command_line
#    command: grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
#    name: uzycie_procesora_val
#    scan_interval: 360
#  - platform: command_line
#    command: df ~ | awk '{ print $5 }' | tail -n 1 | sed 's/.$//'
#    name: uzycie_dysku_val
#    scan_interval: 360
#  - platform: command_line
#    command: free | grep Mem | awk '{usage=($4/$2)*100} END {print usage}'
#    name: wolna_pamiec_val
#    scan_interval: 360
#  - platform: systemmonitor
#    resources:
#      - type: since_last_boot

#  - platform: template
#    sensors:
#      uzycie_procesora:
#        value_template: "{{ states.sensor.uzycie_procesora_val.state | round() }}"
#        unit_of_measurement: '%'
#      uzycie_dysku:
#        value_template: "{{ states.sensor.uzycie_dysku_val.state | round() }}"
#        unit_of_measurement: '%'
#      wolna_pamiec:
#        value_template: "{{ states.sensor.wolna_pamiec_val.state | round() }}"
#        unit_of_measurement: '%'
#      since_last_boot_templated:
#        value_template: >-
#          {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
#          {%- set count = slb | length -%}
#          {%- set hms = slb[count - 1] -%}
#          {%- set hms_trimmed = hms.split('.')[0] -%}
#          {%- set hms_split = hms_trimmed.split(':') -%}
#          {%- set hours = hms_split[0] | int -%}
#          {%- set minutes = hms_split[1] | int -%}
#          {%- set seconds = hms_split[2] | int -%}
#
#          {%- if count == 3 -%}
#            {{ slb[0] ~ ' ' 'd.,' ' ' }}
#          {%- endif -%}
#          {%- if hours > 0 -%}
#              {{ hours }} godz.
#          {%- endif -%}
#          {%- if minutes > 0 -%}
#            {%- if hours > 0 -%}
#              {{ ', ' }}
#            {%- endif -%}
#              {{ minutes }} min.
#          {%- endif -%}
#          {%- if seconds > 0 -%}
#            {%- if hours > 0 or minutes > 0 -%}
#              {{ ', ' }}
#            {%- endif -%}
#              {{ seconds }} sek.
#          {%- endif -%}
  - platform: rest
    name: ais_android_wifi_current_network_info
    resource: http://localhost:8122/command
    method: POST
    payload: '{ "WifiConnectionInfo" : true }'
    verify_ssl: false
    headers:
      User-Agent: AIS dom
      Content-Type: application/json
weblink:
  entities:
    - name: klucz ssh
      url: /local/id_rsa_ais
      icon: mdi:console-line
    - name: ftp_url
      url: ftp://ais-dom:1024
      icon: mdi:play-network
#    - name: uncertified_android_registration
#      url: https://www.google.com/android/uncertified/
#      icon: mdi:certificate
    - name: cloud
      url: https://powiedz.co/ords/f?p=1000:101
      icon: mdi:open-in-new
    - name: upgrade_log
      url: /local/upgrade_log.txt
      icon: mdi:file-document
    - name: https_localhost_cert
      url: /local/rootCA.pem
      icon: mdi:verified

input_text:
  ais_android_wifi_password:
    name: "Podaj hasło do Wifi:"
    mode: password
    initial: ""
    icon: mdi:textbox-password
  ais_iot_device_wifi_password:
    name: "Podaj hasło do Wifi:"
    mode: password
    initial: ""
    icon: mdi:textbox-password
  ais_iot_device_name:
    name: "Podaj nazwę dla nowego urządzenia:"
    initial: ""
input_select:
  ais_rss_help_topic:
    name: 'Strona:'
    options:
      - "-"
      - "1. Pierwsze kroki"
      - "2. Co nowego"
      - "3. Komendy głosowe"
      - "4. Sterowanie pilotem"
      - "5. Serwisy audio"
      - "6. Automatyka domowa"
      - "7. Zdalny dostęp"
    initial: "-"
    icon: mdi:format-list-bulleted-type
  ais_android_wifi_network:
    name: 'Wybierz sieć Wifi:'
    options:
      - "-"
    initial: "-"
    icon: mdi:wifi
  ais_iot_devices_in_network:
    name: 'Wykryte nowe urządzenia:'
    options:
      - "-"
    initial: "-"
    icon: mdi:home-plus
input_boolean:
  ais_android_wifi_changes_notify:
    name: Powiadamiaj o zmianach Wifi
    initial: off
    icon: mdi:voice

group:
#  System Status:
#    control: hidden
#    name: Status systemu
#    entities:
#      - sensor.uzycie_procesora
#      - sensor.uzycie_dysku
#      - sensor.wolna_pamiec
#      - sensor.since_last_boot_templated
  Internet Status:
    name: Ustawienia sieci
    control: hidden
    entities:
      - sensor.local_host_name
      # - sensor.speedtest_download
      # - sensor.speedtest_upload
      # - sensor.speedtest_ping
      - sensor.external_ip_address
      - sensor.internal_ip_address
      - sensor.ais_android_wifi_current_network_info
      - script.ais_scan_android_wifi_network
      - input_select.ais_android_wifi_network
      - input_text.ais_android_wifi_password
      - script.ais_connect_android_wifi_network
      - input_boolean.ais_android_wifi_changes_notify
  AIS add IOT device:
    name: Dodawanie nowych urządzeń
    control: hidden
    entities:
      - sensor.ais_connect_iot_device_info
      - script.ais_scan_iot_devices_in_network
      - input_select.ais_iot_devices_in_network
      - input_select.ais_android_wifi_network
      - input_text.ais_iot_device_wifi_password
      - input_text.ais_iot_device_name
      - script.ais_connect_iot_device_to_network
  AIS Configurator:
    name: Konfiguracja
    entities:
      - configurator.ais_dom_host
  ais_rss_help:
    control: hidden
    name: Strony pomocy
    entities:
      - input_select.ais_rss_help_topic
      - sensor.ais_rss_help_text

