[tool.poetry]
name = "hanzilvlib"
version = "0.1.3"
description = "A library to view contents from HanziLevelProject"
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ['hanzi', 'chinese']
repository = "https://github.com/patarapolw/hanzilvlib"
homepage = "https://github.com/patarapolw/hanzilvlib"

[tool.poetry.dependencies]
python = ">=3.5"
importlib_resources = "^1.0"

[tool.poetry.dev-dependencies]
jupyter = "^1.0"
notebook = "^5.7"
