verbose: true
sign_chain_of_trust: true
verify_chain_of_trust: true
verify_cot_signature: true
cot_job_type: signing
log_dir: "/data/log"
work_dir: "/data/work"
artifact_dir: "/data/artifact"
task_log_dir: "/data/artifact/public/logs"
base_gpg_home_dir: "/data/gpg"
gpg_lockfile: "/data/gpg_homedir.lock"
git_key_repo_dir: "/data/key_repo"
git_key_repo_url: "https://github.com/mozilla-releng/cot-gpg-keys.git"
git_commit_signing_pubkey_dir: "/data/git_pubkeys/"
last_good_git_revision_file: "/data/git_revision"
pubkey_path: "/data/my_pubkey.asc"
privkey_path: "/data/my_privkey.asc"
gpg_path: gpg
my_email: "scriptworker@example.com"
