ANALYTICS_URL = "https://www.google-analytics.com/collect"
ANALYTICS_URL = "https://www.google-analytics.com/debug/collect"
ANALYTICS_CODE = "UA-XXXXX-Y"
ANALYTICS_VERSION = "1"
ANALYTICS_TIMEOUT = 1.5

VERSION_ATTR = "v"
TRACKING_ID_ATTR = "tid"
CLIENT_ID_ATTR = "cid"
TYPE_ATTR = "t"

PAGEVIEW_HOSTNAME_ATTR = "dh"
PAGEVIEW_PAGE_ATTR = "dp"
PAGEVIEW_TITLE_ATTR = "dt"

EVENT_CATEGORY_ATTR = "ec"
EVENT_ACTION_ATTR = "ea"
EVENT_LABEL_ATTR = "el"
EVENT_VALUE_ATTR = "ev"

TRANSACTION_ID_ATTR = "ti"
TRANSACTION_AFFILIATION_ATTR = "ta"
TRANSACTION_REVENUE_ATTR = "tr"
TRANSACTION_SHIPPING_ATTR = "ts"
TRANSACTION_TAX_ATTR = "tt"
TRANSACTION_CURRENCY_CODE_ATTR = "cu"

ITEM_TRANSACTION_ID_ATTR = "ti"
ITEM_NAME_ATTR = "in"
ITEM_PRICE_ATTR = "ip"
ITEM_QUANTITY_ATTR = "iq"
ITEM_CODE_ATTR = "ic"
ITEM_VARIATION_ATTR = "iv"
ITEM_CURRENCY_ATTR = "cu"

SOCIAL_ACTION_ATTR = "sa"
SOCIAL_NETWORK_ATTR = "sn"
SOCIAL_TARGET_ATTR = "st"

PROXY_SERVER_IP = "uip"
PROXY_SERVER_USER_AGENT = "ua"

track_pageview_dict = {
    VERSION_ATTR: ANALYTICS_VERSION,
    TRACKING_ID_ATTR: ANALYTICS_CODE,
    CLIENT_ID_ATTR: None,
    TYPE_ATTR: "pageview",
    PAGEVIEW_PAGE_ATTR: None,
    PAGEVIEW_HOSTNAME_ATTR: None,
    PAGEVIEW_TITLE_ATTR: None,
    PROXY_SERVER_IP: None,
    PROXY_SERVER_USER_AGENT: None,
}


track_social_dict = {
    VERSION_ATTR: ANALYTICS_VERSION,
    TRACKING_ID_ATTR: ANALYTICS_CODE,
    CLIENT_ID_ATTR: None,
    TYPE_ATTR: "social",
    SOCIAL_ACTION_ATTR: None,
    SOCIAL_NETWORK_ATTR: None,
    SOCIAL_TARGET_ATTR: None,
    PROXY_SERVER_IP: None,
    PROXY_SERVER_USER_AGENT: None,
}

track_event_dict = {
    VERSION_ATTR: ANALYTICS_VERSION,
    TRACKING_ID_ATTR: ANALYTICS_CODE,
    CLIENT_ID_ATTR: None,
    TYPE_ATTR: "event",
    EVENT_CATEGORY_ATTR: None,
    EVENT_ACTION_ATTR: None,
    EVENT_LABEL_ATTR: None,
    EVENT_VALUE_ATTR: None,
    PROXY_SERVER_IP: None,
    PROXY_SERVER_USER_AGENT: None,
}


track_transaction_dict = {
    VERSION_ATTR: ANALYTICS_VERSION,
    TRACKING_ID_ATTR: ANALYTICS_CODE,
    CLIENT_ID_ATTR: None,
    TYPE_ATTR: "transaction",
    TRANSACTION_ID_ATTR: None,
    TRANSACTION_AFFILIATION_ATTR: None,
    TRANSACTION_REVENUE_ATTR: None,
    TRANSACTION_SHIPPING_ATTR: None,
    TRANSACTION_TAX_ATTR: None,
    TRANSACTION_CURRENCY_CODE_ATTR: None,
    PROXY_SERVER_IP: None,
    PROXY_SERVER_USER_AGENT: None,
}


track_item_dict = {
    VERSION_ATTR: ANALYTICS_VERSION,
    TRACKING_ID_ATTR: ANALYTICS_CODE,
    CLIENT_ID_ATTR: None,
    TYPE_ATTR: "item",
    ITEM_TRANSACTION_ID_ATTR: None,
    ITEM_NAME_ATTR: None,
    ITEM_PRICE_ATTR: None,
    ITEM_QUANTITY_ATTR: None,
    ITEM_CODE_ATTR: None,
    ITEM_VARIATION_ATTR: None,
    ITEM_CURRENCY_ATTR: None,
    PROXY_SERVER_IP: None,
    PROXY_SERVER_USER_AGENT: None,
}
