[tool.poetry]
name = "pyrepr"
version = "0.1.0"
description = "Pretty-printing serializable objects for humans"
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/patarapolw/pyrepr"
homepage = "https://github.com/patarapolw/pyrepr"

[tool.poetry.dependencies]
python = "*"
toml = "^0.10.0"
markdownify = "^0.4.1"

[tool.poetry.dev-dependencies]
