# Generated by Django 2.1.1 on 2018-09-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20180924_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_offered',
            field=models.DateField(blank=True, null=True, verbose_name='last offered'),
        ),
    ]
