# Generated by Django 2.1.1 on 2018-10-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20180928_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_level',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='article',
            name='talks',
        ),
    ]
