# Generated by Django 2.1.1 on 2018-10-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20181002_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='level',
            new_name='student_level',
        ),
    ]
