# Generated by Django 2.1.2 on 2018-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20181002_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Undergraduate'), (10, 'Masters'), (20, 'Doctoral')], null=True),
        ),
    ]
