# Generated by Django 2.1.2 on 2018-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20181002_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='start_date',
            field=models.DateField(default='1900-01-01', verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
