# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.block_volumes_api import BlockVolumesApi  # noqa: E501
from xms_client.rest import ApiException


class TestBlockVolumesApi(unittest.TestCase):
    """BlockVolumesApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.block_volumes_api.BlockVolumesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch_get_block_volume_samples(self):
        """Test case for batch_get_block_volume_samples

        """
        pass

    def test_create_block_volume(self):
        """Test case for create_block_volume

        """
        pass

    def test_delete_block_volume(self):
        """Test case for delete_block_volume

        """
        pass

    def test_get_block_volume(self):
        """Test case for get_block_volume

        """
        pass

    def test_get_block_volume_samples(self):
        """Test case for get_block_volume_samples

        """
        pass

    def test_list_block_volumes(self):
        """Test case for list_block_volumes

        """
        pass

    def test_migrate_block_volume(self):
        """Test case for migrate_block_volume

        """
        pass

    def test_rebuild_block_volume_replication(self):
        """Test case for rebuild_block_volume_replication

        """
        pass

    def test_set_block_volume_replication(self):
        """Test case for set_block_volume_replication

        """
        pass

    def test_set_block_volume_replication_0(self):
        """Test case for set_block_volume_replication_0

        """
        pass

    def test_set_snapshot_protection(self):
        """Test case for set_snapshot_protection

        """
        pass

    def test_suspend_block_volume_replication(self):
        """Test case for suspend_block_volume_replication

        """
        pass

    def test_unset_snapshot_protection(self):
        """Test case for unset_snapshot_protection

        """
        pass

    def test_update_block_volume(self):
        """Test case for update_block_volume

        """
        pass

    def test_update_migration(self):
        """Test case for update_migration

        """
        pass


if __name__ == '__main__':
    unittest.main()
