# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.fs_folders_api import FsFoldersApi  # noqa: E501
from xms_client.rest import ApiException


class TestFsFoldersApi(unittest.TestCase):
    """FsFoldersApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.fs_folders_api.FsFoldersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_folder(self):
        """Test case for create_folder

        """
        pass

    def test_delete_folder(self):
        """Test case for delete_folder

        """
        pass

    def test_get_folder(self):
        """Test case for get_folder

        """
        pass

    def test_get_fs_folder_samples(self):
        """Test case for get_fs_folder_samples

        """
        pass

    def test_list_folders(self):
        """Test case for list_folders

        """
        pass

    def test_roll_back_folder(self):
        """Test case for roll_back_folder

        """
        pass

    def test_update_folder(self):
        """Test case for update_folder

        """
        pass


if __name__ == '__main__':
    unittest.main()
