# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.cloud_instances_api import CloudInstancesApi  # noqa: E501
from xms_client.rest import ApiException


class TestCloudInstancesApi(unittest.TestCase):
    """CloudInstancesApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.cloud_instances_api.CloudInstancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cloud_instance(self):
        """Test case for get_cloud_instance

        """
        pass

    def test_get_cloud_instance_samples(self):
        """Test case for get_cloud_instance_samples

        """
        pass

    def test_list_cloud_instances(self):
        """Test case for list_cloud_instances

        """
        pass


if __name__ == '__main__':
    unittest.main()
