# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.os_gateways_api import OsGatewaysApi  # noqa: E501
from xms_client.rest import ApiException


class TestOsGatewaysApi(unittest.TestCase):
    """OsGatewaysApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.os_gateways_api.OsGatewaysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_gateway(self):
        """Test case for create_gateway

        """
        pass

    def test_delete_gateway(self):
        """Test case for delete_gateway

        """
        pass

    def test_get_gateway(self):
        """Test case for get_gateway

        """
        pass

    def test_get_gateway_samples(self):
        """Test case for get_gateway_samples

        """
        pass

    def test_list_gateways(self):
        """Test case for list_gateways

        """
        pass

    def test_update_gateway(self):
        """Test case for update_gateway

        """
        pass


if __name__ == '__main__':
    unittest.main()
