# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.object_storage_policy_update_req import ObjectStoragePolicyUpdateReq  # noqa: E501
from xms_client.rest import ApiException


class TestObjectStoragePolicyUpdateReq(unittest.TestCase):
    """ObjectStoragePolicyUpdateReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectStoragePolicyUpdateReq(self):
        """Test ObjectStoragePolicyUpdateReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.object_storage_policy_update_req.ObjectStoragePolicyUpdateReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
