# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.os_replication_policies_api import OsReplicationPoliciesApi  # noqa: E501
from xms_client.rest import ApiException


class TestOsReplicationPoliciesApi(unittest.TestCase):
    """OsReplicationPoliciesApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.os_replication_policies_api.OsReplicationPoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_object_storage_replication_policy(self):
        """Test case for create_object_storage_replication_policy

        """
        pass

    def test_delete_object_storage_replication_policy(self):
        """Test case for delete_object_storage_replication_policy

        """
        pass

    def test_get_object_storage_replication_policy(self):
        """Test case for get_object_storage_replication_policy

        """
        pass

    def test_list_object_storage_replication_policies(self):
        """Test case for list_object_storage_replication_policies

        """
        pass


if __name__ == '__main__':
    unittest.main()
