# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.dp_gateways_resp import DpGatewaysResp  # noqa: E501
from xms_client.rest import ApiException


class TestDpGatewaysResp(unittest.TestCase):
    """DpGatewaysResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDpGatewaysResp(self):
        """Test DpGatewaysResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.dp_gateways_resp.DpGatewaysResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
