# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.fs_client_group_update_req_client_group import FSClientGroupUpdateReqClientGroup  # noqa: E501
from xms_client.rest import ApiException


class TestFSClientGroupUpdateReqClientGroup(unittest.TestCase):
    """FSClientGroupUpdateReqClientGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFSClientGroupUpdateReqClientGroup(self):
        """Test FSClientGroupUpdateReqClientGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.fs_client_group_update_req_client_group.FSClientGroupUpdateReqClientGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
