# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.cloud_platforms_api import CloudPlatformsApi  # noqa: E501
from xms_client.rest import ApiException


class TestCloudPlatformsApi(unittest.TestCase):
    """CloudPlatformsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.cloud_platforms_api.CloudPlatformsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cloud_platform(self):
        """Test case for create_cloud_platform

        """
        pass

    def test_delete_cloud_platform(self):
        """Test case for delete_cloud_platform

        """
        pass

    def test_get_cloud_platform(self):
        """Test case for get_cloud_platform

        """
        pass

    def test_list_cloud_platforms(self):
        """Test case for list_cloud_platforms

        """
        pass

    def test_sync_cloud_platform(self):
        """Test case for sync_cloud_platform

        """
        pass

    def test_update_cloud_platform(self):
        """Test case for update_cloud_platform

        """
        pass


if __name__ == '__main__':
    unittest.main()
