# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.event_logs_api import EventLogsApi  # noqa: E501
from xms_client.rest import ApiException


class TestEventLogsApi(unittest.TestCase):
    """EventLogsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.event_logs_api.EventLogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_event_logs(self):
        """Test case for list_event_logs

        """
        pass


if __name__ == '__main__':
    unittest.main()
