arch:
  - 'osl42-x86_64'
# arch_warn_on_failure:
arch_ignore_failure:
  - 'sled11-x86-gcc4.x'
  - 'sled11-x86_64-gcc4.x'

doc_dir: 'build_doc'

test:
  - rm -rf build build_doc source/rafcon.egg-info source/RAFCON.egg-info
  - pip2 install setuptools --upgrade
  - pip2 install pytest --upgrade
  - python setup.py test

env:

env_script:
  - 'free_display=$(python -c "import os;  print '':'' + str(max(map(lambda d: int(d[1]), os.listdir(''/tmp/.X11-unix''))+[-1])+1)")'
  - Xvfb `echo $free_display` -fp $HOME/.fonts -shmem -screen 0 1920x1200x24 & DISPLAY=$free_display
  - export DISPLAY
  - trap 'kill $(jobs -pr)' SIGINT SIGTERM EXIT

