# Generated by Django 2.1.2 on 2018-10-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0004_auto_20181016_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('origin_src', models.CharField(max_length=255, verbose_name='原始地址')),
                ('local_src', models.CharField(blank=True, max_length=255, null=True, verbose_name='本地地址')),
                ('remove_src', models.CharField(blank=True, max_length=255, null=True, verbose_name='远程地址')),
                ('schema', models.IntegerField(choices=[(1, 'HTTPS'), (2, 'HTTP')], default=1, verbose_name='URL类型')),
                ('upload_from', models.IntegerField(choices=[(1, '自动抓取'), (2, '手动添加')], default=1, verbose_name='添加来源')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '远程图片',
                'verbose_name_plural': '远程图片管理',
                'db_table': 'remote_images',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='autotask',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autopost.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(2, '主菜单'), (1, '显示'), (0, '隐藏')], default=1, verbose_name='状态'),
        ),
    ]
