# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{}')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tour_userdata',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tourview',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tourview',
            name='user',
        ),
        migrations.DeleteModel(
            name='TourView',
        ),
    ]
