sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install -U coverage coveralls
    - pip install zc.buildout
    - buildout
script:
    - coverage run bin/test -vvc
after_success:
    - coveralls
notifications:
    email: tseaver@palladion.com
cache:
    - pip: true
    - directories:
      - eggs/
