[tool.poetry]
name = "htmlviewer"
version = "0.1.7"
description = "Table viewer for relational databases, without using HandsOnTable."
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/patarapolw/htmlviewer"
homepage = "https://github.com/patarapolw/htmlviewer"

[tool.poetry.dependencies]
python = "*"
jinja2 = "^2.10"
jupyter = "^1.0"
notebook = "^5.7"

[tool.poetry.dev-dependencies]
