# .travis.yml based on https://github.com/DRMacIver/hypothesis/blob/master/.travis.yml
language: python
sudo: false

python:
  - 3.7-dev

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - PYTHONHASHSEED=random

    matrix:
      # These are ordered to get as much diversity in the
      # first group of parallel runs (4) as possible
      - TASK=test-py37
      - TASK=test-py27
      - TASK=test-pypy
      - TASK=test-py36
      - TASK=test-py27-noembed
      - TASK=test-pypy3
      - TASK=test-py35
      - TASK=test-py34

matrix:
  fast_finish: true

script:
    - make $TASK

notifications:
  email: false


cache:
  pip: true
  directories:
    - $HOME/.venv
    - $HOME/.runtimes
    - $HOME/.wheelhouse


before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
