# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class Direction23Enum(object):

    """Implementation of the 'Direction23' enum.

    Play DTMF Direction & in play audio & sendDigit

    Attributes:
        IN: in direction
        OUT: out direction
        BOTH: both

    """

    IN = 'in'

    OUT = 'out'

    BOTH = 'both'

