# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class MergeNumberStatusEnum(object):

    """Implementation of the 'MergeNumberStatus' enum.

    Choose sub account either merge or delete

    Attributes:
        DELETE: TODO: type description here.
        MERGE: TODO: type description here.

    """

    DELETE = 0

    MERGE = 1

