# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ProductCode30Enum(object):

    """Implementation of the 'Product Code30' enum.

    Returns a list of all usage for a specific "product" or feature of
    Message360.

    Attributes:
        ALL: TODO: type description here.
        ENUM_1: TODO: type description here.
        ENUM_2: TODO: type description here.
        ENUM_3: TODO: type description here.
        ENUM_4: TODO: type description here.
        TRANSCRIPTION: TODO: type description here.
        EMAIL: TODO: type description here.
        CONFERENCE: TODO: type description here.
        CARRIER: TODO: type description here.
        ENUM_9: TODO: type description here.
        ENUM_10: TODO: type description here.
        ENUM_11: TODO: type description here.
        ENUM_12: TODO: type description here.
        ENUM_13: TODO: type description here.

    """

    ALL = 0

    ENUM_1 = 1

    ENUM_2 = 2

    ENUM_3 = 3

    ENUM_4 = 4

    TRANSCRIPTION = 5

    EMAIL = 6

    CONFERENCE = 7

    CARRIER = 8

    ENUM_9 = 9

    ENUM_10 = 10

    ENUM_11 = 11

    ENUM_12 = 12

    ENUM_13 = 13

