# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class Status25Enum(object):

    """Implementation of the 'Status25' enum.

    Transcription Status

    Attributes:
        INPROGRESS: TODO: type description here.
        SUCCESS: TODO: type description here.
        FAILURE: TODO: type description here.

    """

    INPROGRESS = 'inprogress'

    SUCCESS = 'success'

    FAILURE = 'failure'

