
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-12T22:16:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc2b2f678e675ae495aec960b746226b5e1c913c",
 "version": "0.20.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
