
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "408a1f6517ba60b81ef275f122179b51d98e277d",
 "version": "0.1.0.b2766.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
