# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class AlertRuleCreateReqRule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'level': 'str',
        'resource_type': 'str',
        'trigger_mode': 'str',
        'trigger_period': 'int',
        'trigger_value': 'str',
        'type': 'str'
    }

    attribute_map = {
        'enabled': 'enabled',
        'level': 'level',
        'resource_type': 'resource_type',
        'trigger_mode': 'trigger_mode',
        'trigger_period': 'trigger_period',
        'trigger_value': 'trigger_value',
        'type': 'type'
    }

    def __init__(self, enabled=None, level=None, resource_type=None, trigger_mode=None, trigger_period=None, trigger_value=None, type=None):  # noqa: E501
        """AlertRuleCreateReqRule - a model defined in Swagger"""  # noqa: E501

        self._enabled = None
        self._level = None
        self._resource_type = None
        self._trigger_mode = None
        self._trigger_period = None
        self._trigger_value = None
        self._type = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if level is not None:
            self.level = level
        if resource_type is not None:
            self.resource_type = resource_type
        if trigger_mode is not None:
            self.trigger_mode = trigger_mode
        if trigger_period is not None:
            self.trigger_period = trigger_period
        if trigger_value is not None:
            self.trigger_value = trigger_value
        if type is not None:
            self.type = type

    @property
    def enabled(self):
        """Gets the enabled of this AlertRuleCreateReqRule.  # noqa: E501


        :return: The enabled of this AlertRuleCreateReqRule.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this AlertRuleCreateReqRule.


        :param enabled: The enabled of this AlertRuleCreateReqRule.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def level(self):
        """Gets the level of this AlertRuleCreateReqRule.  # noqa: E501


        :return: The level of this AlertRuleCreateReqRule.  # noqa: E501
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this AlertRuleCreateReqRule.


        :param level: The level of this AlertRuleCreateReqRule.  # noqa: E501
        :type: str
        """

        self._level = level

    @property
    def resource_type(self):
        """Gets the resource_type of this AlertRuleCreateReqRule.  # noqa: E501


        :return: The resource_type of this AlertRuleCreateReqRule.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this AlertRuleCreateReqRule.


        :param resource_type: The resource_type of this AlertRuleCreateReqRule.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def trigger_mode(self):
        """Gets the trigger_mode of this AlertRuleCreateReqRule.  # noqa: E501


        :return: The trigger_mode of this AlertRuleCreateReqRule.  # noqa: E501
        :rtype: str
        """
        return self._trigger_mode

    @trigger_mode.setter
    def trigger_mode(self, trigger_mode):
        """Sets the trigger_mode of this AlertRuleCreateReqRule.


        :param trigger_mode: The trigger_mode of this AlertRuleCreateReqRule.  # noqa: E501
        :type: str
        """

        self._trigger_mode = trigger_mode

    @property
    def trigger_period(self):
        """Gets the trigger_period of this AlertRuleCreateReqRule.  # noqa: E501


        :return: The trigger_period of this AlertRuleCreateReqRule.  # noqa: E501
        :rtype: int
        """
        return self._trigger_period

    @trigger_period.setter
    def trigger_period(self, trigger_period):
        """Sets the trigger_period of this AlertRuleCreateReqRule.


        :param trigger_period: The trigger_period of this AlertRuleCreateReqRule.  # noqa: E501
        :type: int
        """

        self._trigger_period = trigger_period

    @property
    def trigger_value(self):
        """Gets the trigger_value of this AlertRuleCreateReqRule.  # noqa: E501


        :return: The trigger_value of this AlertRuleCreateReqRule.  # noqa: E501
        :rtype: str
        """
        return self._trigger_value

    @trigger_value.setter
    def trigger_value(self, trigger_value):
        """Sets the trigger_value of this AlertRuleCreateReqRule.


        :param trigger_value: The trigger_value of this AlertRuleCreateReqRule.  # noqa: E501
        :type: str
        """

        self._trigger_value = trigger_value

    @property
    def type(self):
        """Gets the type of this AlertRuleCreateReqRule.  # noqa: E501


        :return: The type of this AlertRuleCreateReqRule.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AlertRuleCreateReqRule.


        :param type: The type of this AlertRuleCreateReqRule.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertRuleCreateReqRule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
