# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from xms_client.models.dp_block_snapshot_policy_nestview import DpBlockSnapshotPolicyNestview  # noqa: F401,E501
# from xms_client.models.dp_site_nestview import DpSiteNestview  # noqa: F401,E501


class DpBlockSnapshotPlan(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'compressed': 'bool',
        'create': 'datetime',
        'deduplicated': 'bool',
        'dp_block_snapshot_policy': 'DpBlockSnapshotPolicyNestview',
        'dp_site': 'DpSiteNestview',
        'encrypted': 'bool',
        'full_backup_interval': 'int',
        'id': 'int',
        'operation_interval': 'int',
        'retained_max': 'int',
        'status': 'str',
        'type': 'str',
        'update': 'datetime'
    }

    attribute_map = {
        'compressed': 'compressed',
        'create': 'create',
        'deduplicated': 'deduplicated',
        'dp_block_snapshot_policy': 'dp_block_snapshot_policy',
        'dp_site': 'dp_site',
        'encrypted': 'encrypted',
        'full_backup_interval': 'full_backup_interval',
        'id': 'id',
        'operation_interval': 'operation_interval',
        'retained_max': 'retained_max',
        'status': 'status',
        'type': 'type',
        'update': 'update'
    }

    def __init__(self, compressed=None, create=None, deduplicated=None, dp_block_snapshot_policy=None, dp_site=None, encrypted=None, full_backup_interval=None, id=None, operation_interval=None, retained_max=None, status=None, type=None, update=None):  # noqa: E501
        """DpBlockSnapshotPlan - a model defined in Swagger"""  # noqa: E501

        self._compressed = None
        self._create = None
        self._deduplicated = None
        self._dp_block_snapshot_policy = None
        self._dp_site = None
        self._encrypted = None
        self._full_backup_interval = None
        self._id = None
        self._operation_interval = None
        self._retained_max = None
        self._status = None
        self._type = None
        self._update = None
        self.discriminator = None

        if compressed is not None:
            self.compressed = compressed
        if create is not None:
            self.create = create
        if deduplicated is not None:
            self.deduplicated = deduplicated
        if dp_block_snapshot_policy is not None:
            self.dp_block_snapshot_policy = dp_block_snapshot_policy
        if dp_site is not None:
            self.dp_site = dp_site
        if encrypted is not None:
            self.encrypted = encrypted
        if full_backup_interval is not None:
            self.full_backup_interval = full_backup_interval
        if id is not None:
            self.id = id
        if operation_interval is not None:
            self.operation_interval = operation_interval
        if retained_max is not None:
            self.retained_max = retained_max
        if status is not None:
            self.status = status
        if type is not None:
            self.type = type
        if update is not None:
            self.update = update

    @property
    def compressed(self):
        """Gets the compressed of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The compressed of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: bool
        """
        return self._compressed

    @compressed.setter
    def compressed(self, compressed):
        """Sets the compressed of this DpBlockSnapshotPlan.


        :param compressed: The compressed of this DpBlockSnapshotPlan.  # noqa: E501
        :type: bool
        """

        self._compressed = compressed

    @property
    def create(self):
        """Gets the create of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The create of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: datetime
        """
        return self._create

    @create.setter
    def create(self, create):
        """Sets the create of this DpBlockSnapshotPlan.


        :param create: The create of this DpBlockSnapshotPlan.  # noqa: E501
        :type: datetime
        """

        self._create = create

    @property
    def deduplicated(self):
        """Gets the deduplicated of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The deduplicated of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: bool
        """
        return self._deduplicated

    @deduplicated.setter
    def deduplicated(self, deduplicated):
        """Sets the deduplicated of this DpBlockSnapshotPlan.


        :param deduplicated: The deduplicated of this DpBlockSnapshotPlan.  # noqa: E501
        :type: bool
        """

        self._deduplicated = deduplicated

    @property
    def dp_block_snapshot_policy(self):
        """Gets the dp_block_snapshot_policy of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The dp_block_snapshot_policy of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: DpBlockSnapshotPolicyNestview
        """
        return self._dp_block_snapshot_policy

    @dp_block_snapshot_policy.setter
    def dp_block_snapshot_policy(self, dp_block_snapshot_policy):
        """Sets the dp_block_snapshot_policy of this DpBlockSnapshotPlan.


        :param dp_block_snapshot_policy: The dp_block_snapshot_policy of this DpBlockSnapshotPlan.  # noqa: E501
        :type: DpBlockSnapshotPolicyNestview
        """

        self._dp_block_snapshot_policy = dp_block_snapshot_policy

    @property
    def dp_site(self):
        """Gets the dp_site of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The dp_site of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: DpSiteNestview
        """
        return self._dp_site

    @dp_site.setter
    def dp_site(self, dp_site):
        """Sets the dp_site of this DpBlockSnapshotPlan.


        :param dp_site: The dp_site of this DpBlockSnapshotPlan.  # noqa: E501
        :type: DpSiteNestview
        """

        self._dp_site = dp_site

    @property
    def encrypted(self):
        """Gets the encrypted of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The encrypted of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: bool
        """
        return self._encrypted

    @encrypted.setter
    def encrypted(self, encrypted):
        """Sets the encrypted of this DpBlockSnapshotPlan.


        :param encrypted: The encrypted of this DpBlockSnapshotPlan.  # noqa: E501
        :type: bool
        """

        self._encrypted = encrypted

    @property
    def full_backup_interval(self):
        """Gets the full_backup_interval of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The full_backup_interval of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: int
        """
        return self._full_backup_interval

    @full_backup_interval.setter
    def full_backup_interval(self, full_backup_interval):
        """Sets the full_backup_interval of this DpBlockSnapshotPlan.


        :param full_backup_interval: The full_backup_interval of this DpBlockSnapshotPlan.  # noqa: E501
        :type: int
        """

        self._full_backup_interval = full_backup_interval

    @property
    def id(self):
        """Gets the id of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The id of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DpBlockSnapshotPlan.


        :param id: The id of this DpBlockSnapshotPlan.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def operation_interval(self):
        """Gets the operation_interval of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The operation_interval of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: int
        """
        return self._operation_interval

    @operation_interval.setter
    def operation_interval(self, operation_interval):
        """Sets the operation_interval of this DpBlockSnapshotPlan.


        :param operation_interval: The operation_interval of this DpBlockSnapshotPlan.  # noqa: E501
        :type: int
        """

        self._operation_interval = operation_interval

    @property
    def retained_max(self):
        """Gets the retained_max of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The retained_max of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: int
        """
        return self._retained_max

    @retained_max.setter
    def retained_max(self, retained_max):
        """Sets the retained_max of this DpBlockSnapshotPlan.


        :param retained_max: The retained_max of this DpBlockSnapshotPlan.  # noqa: E501
        :type: int
        """

        self._retained_max = retained_max

    @property
    def status(self):
        """Gets the status of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The status of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DpBlockSnapshotPlan.


        :param status: The status of this DpBlockSnapshotPlan.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def type(self):
        """Gets the type of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The type of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DpBlockSnapshotPlan.


        :param type: The type of this DpBlockSnapshotPlan.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def update(self):
        """Gets the update of this DpBlockSnapshotPlan.  # noqa: E501


        :return: The update of this DpBlockSnapshotPlan.  # noqa: E501
        :rtype: datetime
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this DpBlockSnapshotPlan.


        :param update: The update of this DpBlockSnapshotPlan.  # noqa: E501
        :type: datetime
        """

        self._update = update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DpBlockSnapshotPlan):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
