# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class FSGatewayGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_group_num': 'int',
        'action_status': 'str',
        'create': 'datetime',
        'description': 'str',
        'encoding': 'str',
        'folder_num': 'int',
        'id': 'int',
        'name': 'str',
        'port': 'int',
        'security': 'str',
        'status': 'str',
        'types': 'list[str]',
        'update': 'datetime',
        'vip': 'str',
        'vip_mask': 'int'
    }

    attribute_map = {
        'access_group_num': 'access_group_num',
        'action_status': 'action_status',
        'create': 'create',
        'description': 'description',
        'encoding': 'encoding',
        'folder_num': 'folder_num',
        'id': 'id',
        'name': 'name',
        'port': 'port',
        'security': 'security',
        'status': 'status',
        'types': 'types',
        'update': 'update',
        'vip': 'vip',
        'vip_mask': 'vip_mask'
    }

    def __init__(self, access_group_num=None, action_status=None, create=None, description=None, encoding=None, folder_num=None, id=None, name=None, port=None, security=None, status=None, types=None, update=None, vip=None, vip_mask=None):  # noqa: E501
        """FSGatewayGroup - a model defined in Swagger"""  # noqa: E501

        self._access_group_num = None
        self._action_status = None
        self._create = None
        self._description = None
        self._encoding = None
        self._folder_num = None
        self._id = None
        self._name = None
        self._port = None
        self._security = None
        self._status = None
        self._types = None
        self._update = None
        self._vip = None
        self._vip_mask = None
        self.discriminator = None

        if access_group_num is not None:
            self.access_group_num = access_group_num
        if action_status is not None:
            self.action_status = action_status
        if create is not None:
            self.create = create
        if description is not None:
            self.description = description
        if encoding is not None:
            self.encoding = encoding
        if folder_num is not None:
            self.folder_num = folder_num
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if port is not None:
            self.port = port
        if security is not None:
            self.security = security
        if status is not None:
            self.status = status
        if types is not None:
            self.types = types
        if update is not None:
            self.update = update
        if vip is not None:
            self.vip = vip
        if vip_mask is not None:
            self.vip_mask = vip_mask

    @property
    def access_group_num(self):
        """Gets the access_group_num of this FSGatewayGroup.  # noqa: E501


        :return: The access_group_num of this FSGatewayGroup.  # noqa: E501
        :rtype: int
        """
        return self._access_group_num

    @access_group_num.setter
    def access_group_num(self, access_group_num):
        """Sets the access_group_num of this FSGatewayGroup.


        :param access_group_num: The access_group_num of this FSGatewayGroup.  # noqa: E501
        :type: int
        """

        self._access_group_num = access_group_num

    @property
    def action_status(self):
        """Gets the action_status of this FSGatewayGroup.  # noqa: E501


        :return: The action_status of this FSGatewayGroup.  # noqa: E501
        :rtype: str
        """
        return self._action_status

    @action_status.setter
    def action_status(self, action_status):
        """Sets the action_status of this FSGatewayGroup.


        :param action_status: The action_status of this FSGatewayGroup.  # noqa: E501
        :type: str
        """

        self._action_status = action_status

    @property
    def create(self):
        """Gets the create of this FSGatewayGroup.  # noqa: E501


        :return: The create of this FSGatewayGroup.  # noqa: E501
        :rtype: datetime
        """
        return self._create

    @create.setter
    def create(self, create):
        """Sets the create of this FSGatewayGroup.


        :param create: The create of this FSGatewayGroup.  # noqa: E501
        :type: datetime
        """

        self._create = create

    @property
    def description(self):
        """Gets the description of this FSGatewayGroup.  # noqa: E501


        :return: The description of this FSGatewayGroup.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this FSGatewayGroup.


        :param description: The description of this FSGatewayGroup.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def encoding(self):
        """Gets the encoding of this FSGatewayGroup.  # noqa: E501


        :return: The encoding of this FSGatewayGroup.  # noqa: E501
        :rtype: str
        """
        return self._encoding

    @encoding.setter
    def encoding(self, encoding):
        """Sets the encoding of this FSGatewayGroup.


        :param encoding: The encoding of this FSGatewayGroup.  # noqa: E501
        :type: str
        """

        self._encoding = encoding

    @property
    def folder_num(self):
        """Gets the folder_num of this FSGatewayGroup.  # noqa: E501


        :return: The folder_num of this FSGatewayGroup.  # noqa: E501
        :rtype: int
        """
        return self._folder_num

    @folder_num.setter
    def folder_num(self, folder_num):
        """Sets the folder_num of this FSGatewayGroup.


        :param folder_num: The folder_num of this FSGatewayGroup.  # noqa: E501
        :type: int
        """

        self._folder_num = folder_num

    @property
    def id(self):
        """Gets the id of this FSGatewayGroup.  # noqa: E501


        :return: The id of this FSGatewayGroup.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FSGatewayGroup.


        :param id: The id of this FSGatewayGroup.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this FSGatewayGroup.  # noqa: E501


        :return: The name of this FSGatewayGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FSGatewayGroup.


        :param name: The name of this FSGatewayGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def port(self):
        """Gets the port of this FSGatewayGroup.  # noqa: E501


        :return: The port of this FSGatewayGroup.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this FSGatewayGroup.


        :param port: The port of this FSGatewayGroup.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def security(self):
        """Gets the security of this FSGatewayGroup.  # noqa: E501


        :return: The security of this FSGatewayGroup.  # noqa: E501
        :rtype: str
        """
        return self._security

    @security.setter
    def security(self, security):
        """Sets the security of this FSGatewayGroup.


        :param security: The security of this FSGatewayGroup.  # noqa: E501
        :type: str
        """

        self._security = security

    @property
    def status(self):
        """Gets the status of this FSGatewayGroup.  # noqa: E501


        :return: The status of this FSGatewayGroup.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this FSGatewayGroup.


        :param status: The status of this FSGatewayGroup.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def types(self):
        """Gets the types of this FSGatewayGroup.  # noqa: E501


        :return: The types of this FSGatewayGroup.  # noqa: E501
        :rtype: list[str]
        """
        return self._types

    @types.setter
    def types(self, types):
        """Sets the types of this FSGatewayGroup.


        :param types: The types of this FSGatewayGroup.  # noqa: E501
        :type: list[str]
        """

        self._types = types

    @property
    def update(self):
        """Gets the update of this FSGatewayGroup.  # noqa: E501


        :return: The update of this FSGatewayGroup.  # noqa: E501
        :rtype: datetime
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this FSGatewayGroup.


        :param update: The update of this FSGatewayGroup.  # noqa: E501
        :type: datetime
        """

        self._update = update

    @property
    def vip(self):
        """Gets the vip of this FSGatewayGroup.  # noqa: E501


        :return: The vip of this FSGatewayGroup.  # noqa: E501
        :rtype: str
        """
        return self._vip

    @vip.setter
    def vip(self, vip):
        """Sets the vip of this FSGatewayGroup.


        :param vip: The vip of this FSGatewayGroup.  # noqa: E501
        :type: str
        """

        self._vip = vip

    @property
    def vip_mask(self):
        """Gets the vip_mask of this FSGatewayGroup.  # noqa: E501


        :return: The vip_mask of this FSGatewayGroup.  # noqa: E501
        :rtype: int
        """
        return self._vip_mask

    @vip_mask.setter
    def vip_mask(self, vip_mask):
        """Sets the vip_mask of this FSGatewayGroup.


        :param vip_mask: The vip_mask of this FSGatewayGroup.  # noqa: E501
        :type: int
        """

        self._vip_mask = vip_mask

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FSGatewayGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
