# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class ObjectStorageSetReqInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lifecycle_end_on': 'str',
        'lifecycle_start_on': 'str'
    }

    attribute_map = {
        'lifecycle_end_on': 'lifecycle_end_on',
        'lifecycle_start_on': 'lifecycle_start_on'
    }

    def __init__(self, lifecycle_end_on=None, lifecycle_start_on=None):  # noqa: E501
        """ObjectStorageSetReqInfo - a model defined in Swagger"""  # noqa: E501

        self._lifecycle_end_on = None
        self._lifecycle_start_on = None
        self.discriminator = None

        self.lifecycle_end_on = lifecycle_end_on
        self.lifecycle_start_on = lifecycle_start_on

    @property
    def lifecycle_end_on(self):
        """Gets the lifecycle_end_on of this ObjectStorageSetReqInfo.  # noqa: E501

        lifecycle end execute time  # noqa: E501

        :return: The lifecycle_end_on of this ObjectStorageSetReqInfo.  # noqa: E501
        :rtype: str
        """
        return self._lifecycle_end_on

    @lifecycle_end_on.setter
    def lifecycle_end_on(self, lifecycle_end_on):
        """Sets the lifecycle_end_on of this ObjectStorageSetReqInfo.

        lifecycle end execute time  # noqa: E501

        :param lifecycle_end_on: The lifecycle_end_on of this ObjectStorageSetReqInfo.  # noqa: E501
        :type: str
        """
        if lifecycle_end_on is None:
            raise ValueError("Invalid value for `lifecycle_end_on`, must not be `None`")  # noqa: E501

        self._lifecycle_end_on = lifecycle_end_on

    @property
    def lifecycle_start_on(self):
        """Gets the lifecycle_start_on of this ObjectStorageSetReqInfo.  # noqa: E501

        lifecycle start execute time  # noqa: E501

        :return: The lifecycle_start_on of this ObjectStorageSetReqInfo.  # noqa: E501
        :rtype: str
        """
        return self._lifecycle_start_on

    @lifecycle_start_on.setter
    def lifecycle_start_on(self, lifecycle_start_on):
        """Sets the lifecycle_start_on of this ObjectStorageSetReqInfo.

        lifecycle start execute time  # noqa: E501

        :param lifecycle_start_on: The lifecycle_start_on of this ObjectStorageSetReqInfo.  # noqa: E501
        :type: str
        """
        if lifecycle_start_on is None:
            raise ValueError("Invalid value for `lifecycle_start_on`, must not be `None`")  # noqa: E501

        self._lifecycle_start_on = lifecycle_start_on

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectStorageSetReqInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
