# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from xms_client.models.bucket_flag_req import BucketFlagReq  # noqa: F401,E501


class ObjectStorageBucketUpdateReqBucket(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'all_user_permission': 'str',
        'auth_user_permission': 'str',
        'flag': 'BucketFlagReq',
        'owner_id': 'int',
        'owner_permission': 'str',
        'quota_max_objects': 'int',
        'quota_max_size': 'int',
        'replication_policy_id': 'int'
    }

    attribute_map = {
        'all_user_permission': 'all_user_permission',
        'auth_user_permission': 'auth_user_permission',
        'flag': 'flag',
        'owner_id': 'owner_id',
        'owner_permission': 'owner_permission',
        'quota_max_objects': 'quota_max_objects',
        'quota_max_size': 'quota_max_size',
        'replication_policy_id': 'replication_policy_id'
    }

    def __init__(self, all_user_permission=None, auth_user_permission=None, flag=None, owner_id=None, owner_permission=None, quota_max_objects=None, quota_max_size=None, replication_policy_id=None):  # noqa: E501
        """ObjectStorageBucketUpdateReqBucket - a model defined in Swagger"""  # noqa: E501

        self._all_user_permission = None
        self._auth_user_permission = None
        self._flag = None
        self._owner_id = None
        self._owner_permission = None
        self._quota_max_objects = None
        self._quota_max_size = None
        self._replication_policy_id = None
        self.discriminator = None

        if all_user_permission is not None:
            self.all_user_permission = all_user_permission
        if auth_user_permission is not None:
            self.auth_user_permission = auth_user_permission
        if flag is not None:
            self.flag = flag
        if owner_id is not None:
            self.owner_id = owner_id
        if owner_permission is not None:
            self.owner_permission = owner_permission
        if quota_max_objects is not None:
            self.quota_max_objects = quota_max_objects
        if quota_max_size is not None:
            self.quota_max_size = quota_max_size
        if replication_policy_id is not None:
            self.replication_policy_id = replication_policy_id

    @property
    def all_user_permission(self):
        """Gets the all_user_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501


        :return: The all_user_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: str
        """
        return self._all_user_permission

    @all_user_permission.setter
    def all_user_permission(self, all_user_permission):
        """Sets the all_user_permission of this ObjectStorageBucketUpdateReqBucket.


        :param all_user_permission: The all_user_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: str
        """

        self._all_user_permission = all_user_permission

    @property
    def auth_user_permission(self):
        """Gets the auth_user_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501


        :return: The auth_user_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: str
        """
        return self._auth_user_permission

    @auth_user_permission.setter
    def auth_user_permission(self, auth_user_permission):
        """Sets the auth_user_permission of this ObjectStorageBucketUpdateReqBucket.


        :param auth_user_permission: The auth_user_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: str
        """

        self._auth_user_permission = auth_user_permission

    @property
    def flag(self):
        """Gets the flag of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501


        :return: The flag of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: BucketFlagReq
        """
        return self._flag

    @flag.setter
    def flag(self, flag):
        """Sets the flag of this ObjectStorageBucketUpdateReqBucket.


        :param flag: The flag of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: BucketFlagReq
        """

        self._flag = flag

    @property
    def owner_id(self):
        """Gets the owner_id of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501


        :return: The owner_id of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: int
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this ObjectStorageBucketUpdateReqBucket.


        :param owner_id: The owner_id of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: int
        """

        self._owner_id = owner_id

    @property
    def owner_permission(self):
        """Gets the owner_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501


        :return: The owner_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: str
        """
        return self._owner_permission

    @owner_permission.setter
    def owner_permission(self, owner_permission):
        """Sets the owner_permission of this ObjectStorageBucketUpdateReqBucket.


        :param owner_permission: The owner_permission of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: str
        """

        self._owner_permission = owner_permission

    @property
    def quota_max_objects(self):
        """Gets the quota_max_objects of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501


        :return: The quota_max_objects of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: int
        """
        return self._quota_max_objects

    @quota_max_objects.setter
    def quota_max_objects(self, quota_max_objects):
        """Sets the quota_max_objects of this ObjectStorageBucketUpdateReqBucket.


        :param quota_max_objects: The quota_max_objects of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: int
        """

        self._quota_max_objects = quota_max_objects

    @property
    def quota_max_size(self):
        """Gets the quota_max_size of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501


        :return: The quota_max_size of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: int
        """
        return self._quota_max_size

    @quota_max_size.setter
    def quota_max_size(self, quota_max_size):
        """Sets the quota_max_size of this ObjectStorageBucketUpdateReqBucket.


        :param quota_max_size: The quota_max_size of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: int
        """

        self._quota_max_size = quota_max_size

    @property
    def replication_policy_id(self):
        """Gets the replication_policy_id of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501

        replication policy  # noqa: E501

        :return: The replication_policy_id of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :rtype: int
        """
        return self._replication_policy_id

    @replication_policy_id.setter
    def replication_policy_id(self, replication_policy_id):
        """Sets the replication_policy_id of this ObjectStorageBucketUpdateReqBucket.

        replication policy  # noqa: E501

        :param replication_policy_id: The replication_policy_id of this ObjectStorageBucketUpdateReqBucket.  # noqa: E501
        :type: int
        """

        self._replication_policy_id = replication_policy_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectStorageBucketUpdateReqBucket):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
