# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from xms_client.models.object_storage_replication_rule_item import ObjectStorageReplicationRuleItem  # noqa: F401,E501


class ObjectStorageReplicationPolicy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bucket_num': 'int',
        'create': 'datetime',
        'id': 'int',
        'name': 'str',
        'rule': 'list[ObjectStorageReplicationRuleItem]',
        'update': 'datetime'
    }

    attribute_map = {
        'bucket_num': 'bucket_num',
        'create': 'create',
        'id': 'id',
        'name': 'name',
        'rule': 'rule',
        'update': 'update'
    }

    def __init__(self, bucket_num=None, create=None, id=None, name=None, rule=None, update=None):  # noqa: E501
        """ObjectStorageReplicationPolicy - a model defined in Swagger"""  # noqa: E501

        self._bucket_num = None
        self._create = None
        self._id = None
        self._name = None
        self._rule = None
        self._update = None
        self.discriminator = None

        if bucket_num is not None:
            self.bucket_num = bucket_num
        if create is not None:
            self.create = create
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if rule is not None:
            self.rule = rule
        if update is not None:
            self.update = update

    @property
    def bucket_num(self):
        """Gets the bucket_num of this ObjectStorageReplicationPolicy.  # noqa: E501


        :return: The bucket_num of this ObjectStorageReplicationPolicy.  # noqa: E501
        :rtype: int
        """
        return self._bucket_num

    @bucket_num.setter
    def bucket_num(self, bucket_num):
        """Sets the bucket_num of this ObjectStorageReplicationPolicy.


        :param bucket_num: The bucket_num of this ObjectStorageReplicationPolicy.  # noqa: E501
        :type: int
        """

        self._bucket_num = bucket_num

    @property
    def create(self):
        """Gets the create of this ObjectStorageReplicationPolicy.  # noqa: E501


        :return: The create of this ObjectStorageReplicationPolicy.  # noqa: E501
        :rtype: datetime
        """
        return self._create

    @create.setter
    def create(self, create):
        """Sets the create of this ObjectStorageReplicationPolicy.


        :param create: The create of this ObjectStorageReplicationPolicy.  # noqa: E501
        :type: datetime
        """

        self._create = create

    @property
    def id(self):
        """Gets the id of this ObjectStorageReplicationPolicy.  # noqa: E501


        :return: The id of this ObjectStorageReplicationPolicy.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ObjectStorageReplicationPolicy.


        :param id: The id of this ObjectStorageReplicationPolicy.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ObjectStorageReplicationPolicy.  # noqa: E501


        :return: The name of this ObjectStorageReplicationPolicy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ObjectStorageReplicationPolicy.


        :param name: The name of this ObjectStorageReplicationPolicy.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def rule(self):
        """Gets the rule of this ObjectStorageReplicationPolicy.  # noqa: E501


        :return: The rule of this ObjectStorageReplicationPolicy.  # noqa: E501
        :rtype: list[ObjectStorageReplicationRuleItem]
        """
        return self._rule

    @rule.setter
    def rule(self, rule):
        """Sets the rule of this ObjectStorageReplicationPolicy.


        :param rule: The rule of this ObjectStorageReplicationPolicy.  # noqa: E501
        :type: list[ObjectStorageReplicationRuleItem]
        """

        self._rule = rule

    @property
    def update(self):
        """Gets the update of this ObjectStorageReplicationPolicy.  # noqa: E501


        :return: The update of this ObjectStorageReplicationPolicy.  # noqa: E501
        :rtype: datetime
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this ObjectStorageReplicationPolicy.


        :param update: The update of this ObjectStorageReplicationPolicy.  # noqa: E501
        :type: datetime
        """

        self._update = update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectStorageReplicationPolicy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
