
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9e0188d2b756b25c36868f089f39800fd45b82d9",
 "version": "0.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
