[tool.poetry]
name = "hello_todo"
version = "0.1.1"
description = ""
authors = ["Mathias Ngo <ngo.mathias@gmail.com>"]

[tool.poetry.scripts]
todos = "hello_todo.cli:hello"

[tool.poetry.dependencies]
python = "*"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
