[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pcte-dynamic-provisioning"
version = "0.1.0"
description = "Dynamic Provisioning of the PCTE Greyspace Environment"
authors = ["Jordan Gregory <jordan.gregory@metova.com>"]
readme = "README.rst"
documentation = "https://cybercents.atlassian.com/pcte"
packages = [
    { include = "pcte_dynaprov", from = "src" },
]

[tool.poetry.scripts]
pcte-dynamic-provision = 'main:cli'

[tool.poetry.dependencies]
python = "^3.6"
jsonschema = "^2.6"
pika = "^0.12.0"
PyYAML = "^3.13"
aiohttp = "^3.4"
pyvmomi = "^6.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.8"
pytest-cov = "^2.6"
tox = "^3.5"
