# Generated by Django 2.1.2 on 2018-10-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0003_auto_20181014_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotask',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autopost.Author'),
        ),
        migrations.AlterField(
            model_name='autotask',
            name='content_except',
            field=models.CharField(blank=True, default='[]', help_text='以json格式', max_length=255, null=True, verbose_name='不包含内容'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, '显示'), (0, '隐藏'), (2, '主菜单')], default=1, verbose_name='状态'),
        ),
    ]
