# Generated by Django 2.1.2 on 2018-10-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0005_auto_20181017_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteimages',
            old_name='remove_src',
            new_name='remote_src',
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, '显示'), (2, '主菜单'), (0, '隐藏')], default=1, verbose_name='状态'),
        ),
    ]
