# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djflocash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='fpn_id',
            field=models.CharField(max_length=50, verbose_name='Unique FloCash ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trans_id',
            field=models.CharField(max_length=50, verbose_name='Unique transaction ID. If error, the value is 0'),
        ),
    ]
