
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "56026b45b0f1c1b804231fd4912b0dc47e7c1c27",
 "version": "0.2.3.b2911"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
