
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-17T13:11:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f9bc78d575eeb8015923311a72e0f6197c669cc",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
