
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-11T16:52:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5944e54d0529bc40e3a1da435cd34b40ac702f28",
 "version": "1.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
