# -*- coding: utf-8 -*-

"""
    apimaticdemonstration1234

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from .decorators import lazy_property
from .configuration import Configuration
from .controllers.messages_controller import MessagesController
from .controllers.replies_controller import RepliesController
from .controllers.delivery_reports_controller import DeliveryReportsController

class Apimaticdemonstration1234Client(object):

    config = Configuration

    @lazy_property
    def messages(self):
        return MessagesController()

    @lazy_property
    def replies(self):
        return RepliesController()

    @lazy_property
    def delivery_reports(self):
        return DeliveryReportsController()



