
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-26T17:30:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "08f43cdb1e5262b143bff873567cf125dec3bda5",
 "version": "v0.3.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
