#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['there']

package_data = \
{'': ['*']}

setup(name='there',
      version='0.0.8',
      description='Print current file and line number',
      author='Matthias Bussonnier',
      author_email='bussonniermatthias@gmail.com',
      url='https://github.com/Carreau/there',
      packages=packages,
      package_data=package_data,
     )
