package:
  name: toyplot
  version: "0.16.1" ## need to set this explicit b/c the git version is v0.15.0

source:
  ## eaton-lab branch is up-to-date with sandialabs, but excludes requirements
  ## that are only used to build the documentation. 
  #git_url: https://github.com/sandialabs/toyplot.git
  #git_tag: 5f0271f1d9c478917096c8b0496cd6a590f00a0a
  git_url: https://github.com/eaton-lab/toyplot.git
  git_tag: 0.16.1

build:
  ##string: dev   ## {{ environ.get('GIT_DESCRIBE_HASH', '') }}
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python 
    - setuptools
    - numpy >=1.8.2
    - pandas >=0.14.1
    - pip
    - pypng >=0.0.18   ## png
    - pillow           ## pdf 
    - reportlab        ## pdf
    - graphviz         ## graphs
    - networkx         ## graphs
    - multipledispatch ## render
    - six               ## not really being used
    #- custom_inherit   ## not really being used
    #- arrow            ## used for date-times 
    - mock ## docs
  run:
    - python 
    - setuptools
    - pip
    - numpy >=1.8.2
    - pypng >=0.0.18
    - pandas >=0.14.1    
    - pillow
    - reportlab
    - graphviz
    - networkx
    - multipledispatch
    - six
    #- custom_inherit
    #- arrow

test:
  imports:
    - toyplot

    
about:
  home: http://github.com/sandialabs/toyplot
  license: BSD
  summary: A modern plotting toolkit supporting electronic publishing and reproducibility.

