user_feature_list = ['location_n_periods',
                                'description_n_capsp',
                                'description_n_caps',
                                'name_n_exclaims',
                                'location_n_chars',
                                'location_n_exclaims',
                                'description_n_extraspaces',
                                'name_n_periods',
                                'location_n_lowersp',
                                'location_n_words',
                                'description_n_lowersp',
                                'description_n_periods',
                                'location_n_urls',
                                'description_n_mentions',
                                'name_n_puncts',
                                'location_n_capsp',
                                'description_n_chars',
                                'verified',
                                'name_n_lowers',
                                'description_n_urls',
                                'tweets_to_followers',
                                'ff_ratio',
                                'description_n_puncts',
                                'description_n_charsperword',
                                'location_n_charsperword',
                                'description_n_words',
                                'description_n_digits',
                                'description_n_commas',
                                'name_n_lowersp',
                                'location_n_extraspaces',
                                'location_n_puncts',
                                'name_n_mentions',
                                'name_n_words',
                                'name_n_caps',
                                'name_n_extraspaces',
                                'name_n_commas',
                                'description_n_exclaims',
                                'location_n_commas',
                                'name_n_digits',
                                'location_n_digits',
                                'name_n_charsperword',
                                'description_n_lowers',
                                'name_n_chars',
                                'name_n_capsp',
                                'location_n_mentions',
                                'location_n_caps',
                                'location_n_lowers',]
                                # +['favourites_count',]
                                # +['location_n_hashtags',
                                #     'location_n_nonasciis',
                                #     'listed_count',
                                #     'retweet_count',
                                #     'statuses_rate',
                                #     'friends_count',
                                #     'name_n_hashtags',
                                #     'description_n_nonasciis',
                                #     'favorite_count',
                                #     'description_n_hashtags',
                                #     'followers_count',
                                #     'statuses_count',
                                #     'years_on_twitter',
                                #     'name_n_nonasciis']

tweet_feature_list = ['status_text_n_capsp',
                                    'status_text_n_exclaims',
                                    'status_text_n_urls',
                                    'status_text_n_extraspaces',
                                    'status_text_n_lowers',
                                    'status_text_n_charsperword',
                                    'status_text_n_commas',
                                    'status_text_n_words',
                                    'status_text_n_hashtags',
                                    'status_text_n_mentions',
                                    'n_tweets',
                                    'status_text_n_digits',
                                    'status_text_n_caps',
                                    'status_text_n_puncts',
                                    'status_text_n_lowersp',
                                    'status_text_n_chars',
                                    'status_text_n_periods']
                                    # +['google',
                                    #     'facebook',
                                    #     'ifttt',
                                    #     'hootsuite',
                                    #     'ipad',
                                    #     'iphone',
                                    #     'webclient',
                                    #     'android',
                                    #     'lite',
                                    #     'n_quotes',
                                    #     'status_text_n_nonasciis',
                                    #     'n_timeofday',
                                    #     'n_retweets']