- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-java-influxdb
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - legacy-monasca-persister-maven-build
    gate:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-java-influxdb
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - legacy-monasca-persister-maven-build
    post:
      jobs:
        - legacy-monasca-persister-localrepo-upload
