# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('yourtips', '0002_create_index_tip_page'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='yourtipsarticlepage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='yourtip',
            name='homepage_action_copy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Homepage Banner Copy'),
        ),
        migrations.AlterField(
            model_name='yourtipsentry',
            name='converted_article_page',
            field=models.ForeignKey(blank=True, help_text='Your tip article page to which the entry was converted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tip_entries', to='yourtips.YourTipsArticlePage'),
        ),
    ]
