
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '4.10.1'
version_full = 'a252b75f226362511f7d251e96e190b7ffc4067e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

