# Generated by Django 2.1.2 on 2018-10-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0006_auto_20181017_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotask',
            name='lazy_photo',
            field=models.CharField(blank=True, default='', help_text='延时图片替换src值的', max_length=128, null=True, verbose_name='图片属性'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(2, '主菜单'), (0, '隐藏'), (1, '显示')], default=1, verbose_name='状态'),
        ),
    ]
