# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

install:
  - "C:\\Python36\\python -m pip install -U pip"
  - "C:\\Python36\\python -m pip install -U setuptools tox"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "C:\\Python36\\python -m tox -e %TOX_ENV%"

# We don't deploy anything on tags with AppVeyor, we use Travis instead, so we
# might as well save resources
skip_tags: true
