language:
  - generic

os:
  - linux

install:
  - sudo apt-get update;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh;
  - bash miniconda3.sh -b -p $HOME/miniconda3

  ## CONDA PY3 BUILD
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - which python
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - pip install --index-url https://test.pypi.org/simple/ toytree
  #- git clone https://github.com/eaton-lab/toytree.git t2
  #- cd t2
  #- pip install -e .
  #- cd ..
  #- pip install 
  #- conda install pip jupyter notebook nbconvert ipykernel -qy
  #- conda install future requests numpy reportlab -qy
  #
  #- pip install toytree
  #- conda install -c eaton-lab toytree


# command to run tests
script: 
 
  ## do CONDA py3 tests
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - python -c "import toyplot; print(toyplot.__version__)"
  - python -c "import toytree; print(toytree.__version__)"