[tool.poetry]
name = "kbckit"
version = "0.1.0"
description = "Toolkit for KBC"
authors = ["Ryo Takahashi <reiyw.setuve@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
logzero = "^1.5"
pandas = "^0.23.4"
requests = "^2.20"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
