# Generated by Django 2.1 on 2018-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0004_auto_20180813_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcheck',
            name='publish_date',
            field=models.DateField(blank=True, help_text='The date this fact check was published.', null=True),
        ),
    ]
