
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-23T14:30:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c0d3dc21607a3a94695bf14bbaab4c95ab13da7",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
