Environment:
  Production:
    Builder:
      Files:
        MainWindow: ui/main_window.glade
        PreferencesDialog: ui/preferences_dialog.glade
        TagsDialog: ui/tags_dialog.glade
    
    Preferences:
      Doubleclick_Execute: /usr/bin/firefox 
      Autobackup: True
      Autobackup_Suffix: '~'
      Default_Database_File: ''
      
  Development:
    Builder:
      Files:
        MainWindow: ui/main_window.glade
        PreferencesDialog: ui/preferences_dialog.glade
        TagsDialog: ui/tags_dialog.glade
    
    Preferences:
      Doubleclick_Execute: /usr/bin/firefox 
      Autobackup: True
      Autobackup_Suffix: '~'
      Default_Database_File: ''
