---

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --forked
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.6 ]]; then flake8; fi
