# coding: utf-8

"""
    Abstract API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CollectionHighlights(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'offsets': 'list[list[int]]',
        'path': 'list[str]'
    }

    attribute_map = {
        'offsets': 'offsets',
        'path': 'path'
    }

    def __init__(self, offsets=None, path=None):  # noqa: E501
        """CollectionHighlights - a model defined in Swagger"""  # noqa: E501

        self._offsets = None
        self._path = None
        self.discriminator = None

        if offsets is not None:
            self.offsets = offsets
        if path is not None:
            self.path = path

    @property
    def offsets(self):
        """Gets the offsets of this CollectionHighlights.  # noqa: E501


        :return: The offsets of this CollectionHighlights.  # noqa: E501
        :rtype: list[list[int]]
        """
        return self._offsets

    @offsets.setter
    def offsets(self, offsets):
        """Sets the offsets of this CollectionHighlights.


        :param offsets: The offsets of this CollectionHighlights.  # noqa: E501
        :type: list[list[int]]
        """

        self._offsets = offsets

    @property
    def path(self):
        """Gets the path of this CollectionHighlights.  # noqa: E501


        :return: The path of this CollectionHighlights.  # noqa: E501
        :rtype: list[str]
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this CollectionHighlights.


        :param path: The path of this CollectionHighlights.  # noqa: E501
        :type: list[str]
        """

        self._path = path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionHighlights):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
