
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-12T14:47:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "01017de269b218fef6d14d79ea7278a6e7e26a23",
 "version": "v1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
