[tool.poetry]
name = "posetta"
version = "0.0.2"
description = "The universal translator of geodetic coordinate file formats"
authors = ["Geir Arne Hjelle <geir.arne.hjelle@kartverket.no>", "Kristian Evers <kreve@sdfe.dk>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"
pandas = "^0.23.4"
fastkml = "^0.11.0"
lxml = "^4.2"
click = "^7.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
posetta = "posetta.__main__:cli"
posetta_gui = "posetta.__main__:gui"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
