sudo: false
language: python
python:
  - "3.6"
cache: pip
install:
  - pip install flit
  - flit install -s
script:
  - pip install -r test-requirements.txt
  - python -m pytest -v test_commits.py --cov=clincher
after_success:
  - coveralls