[tool.poetry]
name = "cotinga"
version = "0.1.3"
description = ""
authors = ["Nicolas Hainaux <nh.techn@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
sqlalchemy = "^1.2"
pygobject = "^3.28"
toml = "^0.9.4"
Babel = "^2.6"
sqlalchemy-utils = "^0.33.3"
mathmakerlib = "^0.7.0"
file-magic = "^0.4.0"
reportlab = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
polib = "^1.1"

[tool.poetry.scripts]
cotinga = "cotinga.gui:run"
