language: python
env:
  global:
  - PYTHON_VERSION=$PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='cython pandas scipy numpy coveralls coverage h5py mock dask xarray'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
matrix:
  include:
    - env: PYTHON_VERSION=2.7
      os: linux
    - env: PYTHON_VERSION=2.7
      os: osx
      language: generic
    - env: PYTHON_VERSION=3.6
      os: linux
    - env: PYTHON_VERSION=3.6
      os: osx
      language: generic
    - env: PYTHON_VERSION=3.7
      os: linux
    - env: PYTHON_VERSION=3.7
      os: osx
      language: generic
install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
script:
- coverage run --source=python-geotiepoints setup.py test
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure: cnWXKNEvy9ggNw11czp1aUtBsuwM0V3x8tNyvo7zR1Wl8ktarTU6jTvD7PKpAyFT05rRSgi2K+jrHqsu4Xbo1rJNBsvqlHee7wCihfZOXOkwXJM6yjaQsf6e1TwA+JR4Sw/G1VLzzWufUTnKjEKSTvAka+GSo02MzyO6y5FXzc0=
    distributions: sdist
    skip_existing: true
    on:
      tags: true
      repo: pytroll/python-geotiepoints
notifications:
  slack: pytroll:BTiIJLKkWvlePXCYRew0rliC
