language: python
python:
- '2.7'
- '3.5'
- '3.6'
- pypy
install:
- pip install -U pip
- pip install -U setuptools setuptools_scm
- pip install -U tox tox-travis coveralls
script:
- tox
after_success:
- coveralls
