# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BillsMoveBillsDestinationDTO(Model):
    """BillsMoveBillsDestinationDTO.

    :param commodities:
    :type commodities:
     list[~energycap.sdk.models.CommoditiesCommodityChildDTO]
    :param accounts:
    :type accounts:
     list[~energycap.sdk.models.BillsDestinationAccountResponseDTO]
    """

    _attribute_map = {
        'commodities': {'key': 'commodities', 'type': '[CommoditiesCommodityChildDTO]'},
        'accounts': {'key': 'accounts', 'type': '[BillsDestinationAccountResponseDTO]'},
    }

    def __init__(self, commodities=None, accounts=None):
        super(BillsMoveBillsDestinationDTO, self).__init__()
        self.commodities = commodities
        self.accounts = accounts
