import turtle

t = turtle.Pen()
t.speed(0)

def head():
    t.penup()
    t.goto(0, (-100))
    t.pendown()
    t.begin_fill()
    t.fillcolor('gold')
    t.circle(100)
    t.end_fill()
    t.penup()

def glasses():
    #左镜框
    t.penup()
    t.goto(20,50)
    t.pencolor('brown')
    t.pensize(10)
    t.setheading(0)
    t.pendown()
    t.fillcolor('skyblue')
    t.begin_fill()
    t.forward(60)
    t.circle(8,90)
    t.forward(30)
    t.circle(8,90)
    t.forward(60)
    t.circle(8,90)
    t.forward(30)
    t.circle(8,90)
    t.end_fill()
    # 右镜框
    t.penup()
    t.goto(-20,50)
    t.setheading(180)
    t.pendown()
    t.begin_fill()
    t.forward(60)
    t.circle(-8,90)
    t.forward(30)
    t.circle(-8,90)
    t.forward(60)
    t.circle(-8,90)
    t.forward(30)
    t.circle(-8,90)
    t.end_fill()
    # 眼镜连接
    t.penup()
    t.goto(-6,70)
    t.setheading(0)
    t.pensize(20)
    t.pendown()
    t.forward(13)
    # 左镜片光泽
    t.penup()
    t.goto(50,65)
    t.setheading(45)
    t.pensize(8)
    t.pencolor('white')
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(70,65)
    t.pendown()
    t.forward(12)
    # 右镜片光泽
    t.penup()
    t.goto(-50,65)
    t.setheading(45)
    t.pensize(8)
    t.pencolor('white')
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(-30,65)
    t.pendown()
    t.forward(12)


def face():
    #右眼睛
    t.pencolor('black')
    t.pensize(5)
    t.penup()
    t.goto(55,15)
    t.pendown()
    t.setheading(110)
    t.circle(20,140)
    t.penup()
    #左眼睛
    t.goto(-55,15)
    t.pendown()
    t.setheading(70)
    t.circle(-20,140)
    t.penup()
    #嘴巴(外)
    t.goto(-15,-10)
    t.pensize(1)
    t.pencolor('coral')
    t.fillcolor('coral')
    t.setheading(-90)
    t.pendown()
    t.begin_fill()
    t.circle(15,180)
    for i in range(10):
        t.forward(3)
        t.left(7)
    t.left(20)
    t.backward(2)
    t.left(20)
    for i in range(10):
        t.forward(3)
        t.left(7)
    t.end_fill()
    #嘴巴(里)
    t.penup()
    t.goto(12,-10)
    t.setheading(120)
    t.pencolor('darkred')
    t.fillcolor('darkred')
    t.begin_fill()
    t.circle(14,120)
    t.setheading(-60)
    t.circle(14,120)
    t.end_fill()





def hands():
    #左手
    t.penup()
    t.goto(100,0)
    t.pensize(1)
    t.pencolor('black')
    t.setheading(-10)
    t.pendown()
    t.fillcolor('gold')
    t.begin_fill()
    for i in range(7):
        t.forward(9)
        t.right(6)
    for i in range(19):
        t.forward(1)
        t.right(6)
    for i in range(7):
        t.forward(9)
        t.right(5)
    t.end_fill()
    #右手
    t.penup()
    t.goto(-100,0)
    t.setheading(190)
    t.pendown()
    t.fillcolor('gold')
    t.begin_fill()
    for i in range(7):
        t.forward(9)
        t.left(6)
    for i in range(19):
        t.forward(1)
        t.left(6)
    for i in range(7):
        t.forward(9)
        t.left(5)
    t.end_fill()

def hat():
    #蓝色部分
    t.penup()
    t.goto(50,96)
    t.pencolor('deepskyblue')
    t.fillcolor('deepskyblue')
    t.pensize(1)
    t.pendown()
    t.begin_fill()
    t.setheading(90)
    t.circle(10,90)
    t.forward(10)
    t.setheading(90)
    t.forward(10)
    t.circle(5,90)
    t.forward(50)
    t.circle(5,90)
    t.forward(10)
    t.setheading(180)
    t.forward(10)
    t.circle(10,90)
    t.setheading(0)
    t.forward(100)
    t.end_fill()
    #棕色部分
    t.penup()
    t.goto(20,122)
    t.pencolor('brown')
    t.fillcolor('brown')
    t.setheading(90)
    t.pendown()
    t.begin_fill()
    t.forward(15)
    t.circle(5,90)
    t.forward(30)
    t.circle(5,90)
    t.forward(15)
    t.end_fill()

def 大黄鸡():
    head()
    face()
    hat()
    glasses()
    hands()
    turtle.done()

def 纪念碑谷():
    t = turtle.Pen()
    t.speed(9)
    turtle.bgcolor("#A688EC")
    
    #Part1
    t.pencolor("#5C9EF2")
    t.fillcolor("#5C9EF2")
    t.penup()
    t.goto((-50), 150)
    t.setheading((-30))
    t.pendown()
    t.begin_fill()
    t.forward(230)
    t.right(120)
    t.forward(200)
    t.right(120)
    t.forward(30)
    t.right(60)
    t.forward(140)
    t.left(120)
    t.forward(200)
    t.right(120)
    t.forward(30)
    t.end_fill()

    #Part2
    #t.penup()
    t.backward(30)
    t.right(60)
    t.pencolor("#3578D3")
    t.fillcolor("#3578D3")
    t.begin_fill()
    t.forward(200)
    t.right(120)
    t.forward(30)
    t.right(60)
    t.forward(140)
    t.left(120)
    t.forward(200)
    t.right(120)
    t.forward(30)
    t.right(60)
    t.forward(230)
    t.end_fill()
    
    #Part3
    t.pencolor("#2556A2")
    t.fillcolor("#2556A2")
    t.penup()
    t.right(120)
    t.forward(30)
    t.right(60)
    t.forward(30)
    t.pendown()
    t.begin_fill()
    t.forward(200)
    t.left(120)
    t.forward(230)
    t.left(60)
    t.forward(30)
    t.left(120)
    t.forward(200)
    t.right(120)
    t.forward(140)
    t.left(60)
    t.forward(30)
    t.end_fill()

    #Part4
    t.penup()
    t.backward(6)
    t.pencolor("#5C9EF2")
    t.fillcolor("#5C9EF2")
    t.left(120)
    t.forward(25)

    def drawCube():
        t.pendown()
        t.begin_fill()
        t.forward(4)
        t.left(120)
        t.forward(20)
        t.left(60)
        t.forward(4)
        t.left(120)
        t.forward(20)
        t.left(60)
        t.end_fill()
        t.penup()

    for i in range(12):
        drawCube()
        t.forward(12)

    #Part5
    t.fillcolor("#FFFFFF")
    t.pencolor("#FFFFFF")
    t.goto(90, 60)
    t.pensize(2)
    t.pendown()
    t.forward(9)
    t.left(60)
    t.forward(3)
    t.hideturtle()
    t.penup()
    t.goto(95, 60)
    t.right(60)
    t.pendown()
    t.forward(6)
    t.left(60)
    t.forward(3)
    t.penup()
    t.goto(93, 80)
    t.pendown()
    t.right(33)
    t.begin_fill()
    t.forward(18)
    t.right(85)
    t.circle((-20), 60)
    t.right(87)
    t.forward(18)
    t.right(85)
    t.circle(8)
    t.end_fill()
    t.sety(80)
    t.begin_fill()
    t.lt(150)
    t.fd(25)
    t.rt(145)
    t.fd(25)
    t.rt(90)
    t.fd(4)
    t.end_fill()
    t.goto(95,78)
    t.setheading(180)
    t.pensize(2)
    t.pencolor('#000000')
    for i in range(9):
        t.fd(3)
        t.right(18)
    t.penup()

    #words
    t.goto(-60,-160)
    t.pencolor("#2556A2")
    t.pendown()
    t.write('纪念碑谷', font=("Arial", 30, "normal"))
    t.penup()
    turtle.done()
    
def 太极():
    t = turtle.Pen()
    t.pencolor('gray')
    #灰色画笔方向朝左
    t.right(180)
    t.fillcolor('gray')
    __Pen.fillcolor("#000000")
    __Pen.pencolor("#000000")
    __Pen.speed(0)
    t.speed(0)
    for __count in range(360):
        __Pen.begin_fill()
        #黑色画笔向上画一个圆
        __Pen.circle(50)
        #黑色画笔左拐一度
        __Pen.left(1)
        __Pen.end_fill()
        t.begin_fill()
        #灰色画笔向下画一个圆
        t.circle(50)
        #灰色画笔左拐一度
        t.left(1)
        t.end_fill()
    turtle.done()

