# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.fs_ad_users_api import FsAdUsersApi  # noqa: E501
from xms_client.rest import ApiException


class TestFsAdUsersApi(unittest.TestCase):
    """FsAdUsersApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.fs_ad_users_api.FsAdUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fsad_user(self):
        """Test case for get_fsad_user

        """
        pass

    def test_list_fsad_users(self):
        """Test case for list_fsad_users

        """
        pass


if __name__ == '__main__':
    unittest.main()
