# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.object_storage_lifecycle_resp import ObjectStorageLifecycleResp  # noqa: E501
from xms_client.rest import ApiException


class TestObjectStorageLifecycleResp(unittest.TestCase):
    """ObjectStorageLifecycleResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectStorageLifecycleResp(self):
        """Test ObjectStorageLifecycleResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.object_storage_lifecycle_resp.ObjectStorageLifecycleResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
