# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.cloud_platforms_resp import CloudPlatformsResp  # noqa: E501
from xms_client.rest import ApiException


class TestCloudPlatformsResp(unittest.TestCase):
    """CloudPlatformsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudPlatformsResp(self):
        """Test CloudPlatformsResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.cloud_platforms_resp.CloudPlatformsResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
