# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.cloud_volume_attachments_api import CloudVolumeAttachmentsApi  # noqa: E501
from xms_client.rest import ApiException


class TestCloudVolumeAttachmentsApi(unittest.TestCase):
    """CloudVolumeAttachmentsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.cloud_volume_attachments_api.CloudVolumeAttachmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_cloud_volume_attachments(self):
        """Test case for list_cloud_volume_attachments

        """
        pass


if __name__ == '__main__':
    unittest.main()
