# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.object_storage_bucket_update_req_bucket import ObjectStorageBucketUpdateReqBucket  # noqa: E501
from xms_client.rest import ApiException


class TestObjectStorageBucketUpdateReqBucket(unittest.TestCase):
    """ObjectStorageBucketUpdateReqBucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectStorageBucketUpdateReqBucket(self):
        """Test ObjectStorageBucketUpdateReqBucket"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.object_storage_bucket_update_req_bucket.ObjectStorageBucketUpdateReqBucket()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
