# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.fs_share_mappings_api import FsShareMappingsApi  # noqa: E501
from xms_client.rest import ApiException


class TestFsShareMappingsApi(unittest.TestCase):
    """FsShareMappingsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.fs_share_mappings_api.FsShareMappingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_fs_share_mappings(self):
        """Test case for list_fs_share_mappings

        """
        pass


if __name__ == '__main__':
    unittest.main()
