# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.search_api import SearchApi  # noqa: E501
from xms_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search(self):
        """Test case for search

        """
        pass


if __name__ == '__main__':
    unittest.main()
