# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.licenses_api import LicensesApi  # noqa: E501
from xms_client.rest import ApiException


class TestLicensesApi(unittest.TestCase):
    """LicensesApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.licenses_api.LicensesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_license_key(self):
        """Test case for download_license_key

        """
        pass

    def test_get_active_license(self):
        """Test case for get_active_license

        """
        pass

    def test_get_license(self):
        """Test case for get_license

        """
        pass

    def test_list_licenses(self):
        """Test case for list_licenses

        """
        pass

    def test_register_license(self):
        """Test case for register_license

        """
        pass


if __name__ == '__main__':
    unittest.main()
