# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.dp_block_snapshot_plans_api import DpBlockSnapshotPlansApi  # noqa: E501
from xms_client.rest import ApiException


class TestDpBlockSnapshotPlansApi(unittest.TestCase):
    """DpBlockSnapshotPlansApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.dp_block_snapshot_plans_api.DpBlockSnapshotPlansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_dp_block_snapshot_plan(self):
        """Test case for create_dp_block_snapshot_plan

        """
        pass

    def test_delete_dp_block_snapshot_plan(self):
        """Test case for delete_dp_block_snapshot_plan

        """
        pass

    def test_get_dp_block_snapshot_plan(self):
        """Test case for get_dp_block_snapshot_plan

        """
        pass

    def test_list_dp_block_snapshot_plans(self):
        """Test case for list_dp_block_snapshot_plans

        """
        pass

    def test_update_dp_block_snapshot_plan(self):
        """Test case for update_dp_block_snapshot_plan

        """
        pass


if __name__ == '__main__':
    unittest.main()
