# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.client_groups_api import ClientGroupsApi  # noqa: E501
from xms_client.rest import ApiException


class TestClientGroupsApi(unittest.TestCase):
    """ClientGroupsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.client_groups_api.ClientGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_client_group(self):
        """Test case for create_client_group

        """
        pass

    def test_delete_client_group(self):
        """Test case for delete_client_group

        """
        pass

    def test_get_client_group(self):
        """Test case for get_client_group

        """
        pass

    def test_list_client_groups(self):
        """Test case for list_client_groups

        """
        pass

    def test_update_client_group(self):
        """Test case for update_client_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
