# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: 3.2.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.pool_nestview import PoolNestview  # noqa: E501
from xms_client.rest import ApiException


class TestPoolNestview(unittest.TestCase):
    """PoolNestview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoolNestview(self):
        """Test PoolNestview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.pool_nestview.PoolNestview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
