[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "controlgraph"
author = "Dell inc."
author-email = "opx-infra@openswitch.net"
home-page = "https://openswitch.net"
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.5,<4"
description-file="README.md"
requires = [
    "networkx",
    "pydot",
    "python-debian",
]

[tool.flit.scripts]
controlgraph = "controlgraph:main"
