# coding: utf-8

"""
    Omnichannel API

    Messente's API which allows sending messages via various channels with fallback options.  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import omnichannel
from omnichannel.models.whats_app import WhatsApp  # noqa: E501
from omnichannel.rest import ApiException


class TestWhatsApp(unittest.TestCase):
    """WhatsApp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWhatsApp(self):
        """Test WhatsApp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = omnichannel.models.whats_app.WhatsApp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
