stages:
  - deploy

deploy:
  image: python:3
  stage: deploy
  script:
  - pip install -U twine setuptools
  # We don't want to build wheel here as it doesn't support post-install script
  - python setup.py sdist
  - twine upload -u $PYPI_USER -p $PYPI_PASS dist/*
  only:
  - tags