- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - python-ironic-inspector-client-tempest-dsvm
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - python-ironic-inspector-client-tempest-dsvm
        - openstack-tox-lower-constraints
