
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5ab78384289dae8932760228b3b460865c65548e",
 "version": "1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
