repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    -   id: black
        args: [--safe]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: flake8
        additional_dependencies: ["flake8-bugbear == 18.8.0"]
        language_version: python3
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.9.1
    hooks:
    -   id: pyupgrade
