# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ListActionExportHoldDto(Model):
    """ListActionExportHoldDto.

    :param export_hold:
    :type export_hold: bool
    """

    _attribute_map = {
        'export_hold': {'key': 'exportHold', 'type': 'bool'},
    }

    def __init__(self, export_hold=None):
        super(ListActionExportHoldDto, self).__init__()
        self.export_hold = export_hold
