# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PerformanceComparisonDataResponseDto(Model):
    """PerformanceComparisonDataResponseDto.

    :param data_points:
    :type data_points:
     list[~energycap.sdk.models.PerformanceComparisonDataPointDto]
    :param performance_comparisons:
    :type performance_comparisons:
     list[~energycap.sdk.models.PerformanceComparisonDto]
    """

    _attribute_map = {
        'data_points': {'key': 'dataPoints', 'type': '[PerformanceComparisonDataPointDto]'},
        'performance_comparisons': {'key': 'performanceComparisons', 'type': '[PerformanceComparisonDto]'},
    }

    def __init__(self, data_points=None, performance_comparisons=None):
        super(PerformanceComparisonDataResponseDto, self).__init__()
        self.data_points = data_points
        self.performance_comparisons = performance_comparisons
