---
- include_tasks: ceph.yml
  when:
    - enable_ceph | bool
    - gnocchi_backend_storage == 'ceph'

- include_tasks: external_ceph.yml
  when:
    - enable_ceph | bool == False
    - gnocchi_backend_storage == 'ceph'

- include_tasks: register.yml
  when: inventory_hostname in groups['gnocchi-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['gnocchi-statsd'] or
        inventory_hostname in groups['gnocchi-api'] or
        inventory_hostname in groups['gnocchi-metricd']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['gnocchi-api']

- name: Flush handlers
  meta: flush_handlers
