language: python
sudo: false

install:
  - pip install --upgrade pip tox

script:
  - tox -e py27
  - tox -e py34
  - tox -e lint
  - tox -e cover

after_success:
  - tox -e coveralls

deploy:
  provider: pypi
  user: gcloudpypi
  password:
    secure: "QIM16urde5QcGIw8I1C9QTPJtTp0/gl/c8zm2ddGC3RTRE9YilGtOWtxkDDNFQoQH3YW9ljhgMPSpbhpEbxwNiFuxiHTq2XflfMhIhH+zxoiP2p7vrvcsCO8Ui0iEhfECRUchOI4VMwK19UWCRQ1otH5ADULXTYWWY3Q0AVQxzlxdTxc9hqvEVQPZHB4hB/N15xnVpY+dLtmvS6jCEY9HqW/wSNgbRJupei8y98RrR9T+AJHGoyU25Mzp3Wdhl5lyq96eaSPAM1df6j82ad06ofjjbR5CceS8FDbFKQm8Rhbjo8LPa/WzWTZ54qNOTPfp6nJykSXCJ2WoFLFqX6QiVJD8rpg7VpM9Fyd+s0BePr13kbSgNhKm3UvK/l9uShscOLvEHUpU71DPY3fuY+1oWprgUjdVFWsAggrG8IkeTLZND4h7drijgBBKwtgMmMoQeDhqd0P9nOEUZagwuKW0yOKEl1ktEZgwaSrk2KW27XbLS5Cm9AgCKZeCfXokxf/GnIy2R90WVmxCQYOCzWvko0K9cPEFYC4UATQL3tHEfDXeMqxrxgU82aP4MC8oze5L23PiPdy14OmaHGP9f8x8ftIx+XoRjkTR1GiLoqF08Kl8I5dW85X1b+ZGOzPrK1kMZCbfjkQFFl1tbQ3aJAyf8IBx94fxml6s1Hiwa1Y7c8="
  on:
    tags: true
    repo: googleapis/google-cloud-python-happybase
    # until this is fixed: https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
  distributions: "sdist bdist_wheel"

cache:
  directories:
    - ${HOME}/.cache/pip
