from distutils.core import setup
setup(
  name = 'useful_inkleby',
  packages = ['useful_inkleby',
              'useful_inkleby.files',
              'useful_inkleby.data',
              'useful_inkleby.decorators',
              'useful_inkleby.useful_django',
              'useful_inkleby.useful_django.admin',
              'useful_inkleby.useful_django.fields',
              'useful_inkleby.useful_django.models',
              'useful_inkleby.useful_django.management',
              'useful_inkleby.useful_django.management.commands',
              'useful_inkleby.useful_django.forms',
              'useful_inkleby.useful_django.serialisers',
              'useful_inkleby.useful_django.views',
              ],
  version = '0.4',
  description = 'A set of django and generic tools',
  author = 'Alex Parsons',
  author_email = 'alex@alexparsons.co.uk',
  url = 'https://github.com/ajparsons/useful_inkleby', 
  download_url = 'https://github.com/ajparsons/useful_inkleby/archive/0.4.tar.gz', 
  keywords = ['django'], 
  classifiers = [],
)