# Generated by Django 2.1.2 on 2018-10-14 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('autopost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desc',
            new_name='summery',
        ),
        migrations.RenameField(
            model_name='autotask',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='autotask',
            name='check_duration',
        ),
        migrations.RemoveField(
            model_name='autotask',
            name='duplicate_check',
        ),
        migrations.AddField(
            model_name='autotask',
            name='crontab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.CrontabSchedule', verbose_name='定时任务'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '显示'), (2, '主菜单')], default=1, verbose_name='状态'),
        ),
    ]
