# Generated by Django 2.1.2 on 2018-10-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('autopost', '0002_auto_20181014_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotask',
            options={'ordering': ['-id'], 'verbose_name': '抓取任务', 'verbose_name_plural': '抓取任务'},
        ),
        migrations.AddField(
            model_name='autotask',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.PeriodicTask', verbose_name='定时任务'),
        ),
        migrations.AlterField(
            model_name='autotask',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.Site', verbose_name='所属站点'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, '隐藏'), (2, '主菜单'), (1, '显示')], default=1, verbose_name='状态'),
        ),
    ]
