---

#exclude:
#    - '^(.*)[\/\\\\]project[\/\\\\]{{ label }}[\/\\\\]templates[\/\\\\](.*)$'

ignore:
    - '^(.*)pyc(.*)$'
    - '^(.*)pyo(.*)$'
    - '^(.*)__pycache__(.*)$'

variables:
    -   name: gcpproject # config.yml
        prompt: "GCP Project Name"
        default: "trusty-acre-156607"
    
    -   name: apiname
        prompt: "API Name"
        default: "identities"
    
    -   name: dockerusername
        prompt: "Dockerhub Username"
        default: "dennisseidel"