
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-24T17:53:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f089ad47916d92c496c8267515b9dc7509068c1",
 "version": "0.0.0a16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
