
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-01T10:46:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9c761e5e7738cc58fcabbb89d0343fcf39d3887",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
