# Generated by Django 2.1.1 on 2018-09-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='time',
            field=models.TimeField(verbose_name='时间'),
        ),
    ]
