
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-26T10:23:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bdb4182667e82bcc31f07a1660e0909aa500e3e",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
