# coding: utf-8

"""
    Nucleus REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.6.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_client
from nucleus_client.models.page_view import PageView  # noqa: E501
from nucleus_client.rest import ApiException


class TestPageView(unittest.TestCase):
    """PageView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageView(self):
        """Test PageView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_client.models.page_view.PageView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
