# coding: utf-8

"""
    Nucleus REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.6.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_client
from nucleus_client.api.default_api import DefaultApi  # noqa: E501
from nucleus_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = nucleus_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_client(self):
        """Test case for activate_client

        """
        pass

    def test_activate_user(self):
        """Test case for activate_user

        """
        pass

    def test_add_api_key(self):
        """Test case for add_api_key

        """
        pass

    def test_add_block_type(self):
        """Test case for add_block_type

        """
        pass

    def test_add_client(self):
        """Test case for add_client

        """
        pass

    def test_add_dataset(self):
        """Test case for add_dataset

        """
        pass

    def test_add_download_request(self):
        """Test case for add_download_request

        """
        pass

    def test_add_integration(self):
        """Test case for add_integration

        """
        pass

    def test_add_integration_type(self):
        """Test case for add_integration_type

        """
        pass

    def test_add_role(self):
        """Test case for add_role

        """
        pass

    def test_add_role_permission(self):
        """Test case for add_role_permission

        """
        pass

    def test_add_user(self):
        """Test case for add_user

        """
        pass

    def test_add_user_role(self):
        """Test case for add_user_role

        """
        pass

    def test_add_view(self):
        """Test case for add_view

        """
        pass

    def test_add_widget_type(self):
        """Test case for add_widget_type

        """
        pass

    def test_change_password(self):
        """Test case for change_password

        """
        pass

    def test_create_client_package(self):
        """Test case for create_client_package

        """
        pass

    def test_create_full_page(self):
        """Test case for create_full_page

        """
        pass

    def test_delete_activity_by_external_key(self):
        """Test case for delete_activity_by_external_key

        """
        pass

    def test_delete_api_key(self):
        """Test case for delete_api_key

        """
        pass

    def test_delete_block_type(self):
        """Test case for delete_block_type

        """
        pass

    def test_delete_client(self):
        """Test case for delete_client

        """
        pass

    def test_delete_dataset(self):
        """Test case for delete_dataset

        """
        pass

    def test_delete_integration(self):
        """Test case for delete_integration

        """
        pass

    def test_delete_page(self):
        """Test case for delete_page

        """
        pass

    def test_delete_page_preferences_by_page(self):
        """Test case for delete_page_preferences_by_page

        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        """
        pass

    def test_delete_widget_type(self):
        """Test case for delete_widget_type

        """
        pass

    def test_get_activities(self):
        """Test case for get_activities

        """
        pass

    def test_get_api_key(self):
        """Test case for get_api_key

        """
        pass

    def test_get_api_keys(self):
        """Test case for get_api_keys

        """
        pass

    def test_get_block_type(self):
        """Test case for get_block_type

        """
        pass

    def test_get_block_type_by_name(self):
        """Test case for get_block_type_by_name

        """
        pass

    def test_get_block_types(self):
        """Test case for get_block_types

        """
        pass

    def test_get_client(self):
        """Test case for get_client

        """
        pass

    def test_get_client_by_code(self):
        """Test case for get_client_by_code

        """
        pass

    def test_get_client_packages(self):
        """Test case for get_client_packages

        """
        pass

    def test_get_clients(self):
        """Test case for get_clients

        """
        pass

    def test_get_completed_jobs(self):
        """Test case for get_completed_jobs

        """
        pass

    def test_get_dataset(self):
        """Test case for get_dataset

        """
        pass

    def test_get_dataset_by_name(self):
        """Test case for get_dataset_by_name

        """
        pass

    def test_get_dataset_by_slug(self):
        """Test case for get_dataset_by_slug

        """
        pass

    def test_get_datasets(self):
        """Test case for get_datasets

        """
        pass

    def test_get_download(self):
        """Test case for get_download

        """
        pass

    def test_get_download_request(self):
        """Test case for get_download_request

        """
        pass

    def test_get_download_requests(self):
        """Test case for get_download_requests

        """
        pass

    def test_get_entity_batch(self):
        """Test case for get_entity_batch

        """
        pass

    def test_get_entity_batch_health_report(self):
        """Test case for get_entity_batch_health_report

        """
        pass

    def test_get_entity_batches(self):
        """Test case for get_entity_batches

        """
        pass

    def test_get_incomplete_jobs(self):
        """Test case for get_incomplete_jobs

        """
        pass

    def test_get_integration(self):
        """Test case for get_integration

        """
        pass

    def test_get_integration_type(self):
        """Test case for get_integration_type

        """
        pass

    def test_get_integration_type_by_name(self):
        """Test case for get_integration_type_by_name

        """
        pass

    def test_get_integration_types(self):
        """Test case for get_integration_types

        """
        pass

    def test_get_integrations(self):
        """Test case for get_integrations

        """
        pass

    def test_get_job_overview(self):
        """Test case for get_job_overview

        """
        pass

    def test_get_me(self):
        """Test case for get_me

        """
        pass

    def test_get_page(self):
        """Test case for get_page

        """
        pass

    def test_get_page_by_slug(self):
        """Test case for get_page_by_slug

        """
        pass

    def test_get_page_preferences(self):
        """Test case for get_page_preferences

        """
        pass

    def test_get_page_preferences_by_page(self):
        """Test case for get_page_preferences_by_page

        """
        pass

    def test_get_pages(self):
        """Test case for get_pages

        """
        pass

    def test_get_role(self):
        """Test case for get_role

        """
        pass

    def test_get_role_by_name(self):
        """Test case for get_role_by_name

        """
        pass

    def test_get_role_by_slug(self):
        """Test case for get_role_by_slug

        """
        pass

    def test_get_role_permission(self):
        """Test case for get_role_permission

        """
        pass

    def test_get_role_permissions(self):
        """Test case for get_role_permissions

        """
        pass

    def test_get_roles(self):
        """Test case for get_roles

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_get_user_by_activation_key(self):
        """Test case for get_user_by_activation_key

        """
        pass

    def test_get_user_by_email(self):
        """Test case for get_user_by_email

        """
        pass

    def test_get_user_by_reset_key(self):
        """Test case for get_user_by_reset_key

        """
        pass

    def test_get_user_roles(self):
        """Test case for get_user_roles

        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass

    def test_get_view(self):
        """Test case for get_view

        """
        pass

    def test_get_views(self):
        """Test case for get_views

        """
        pass

    def test_get_views_by_hash_keys(self):
        """Test case for get_views_by_hash_keys

        """
        pass

    def test_get_widget_type(self):
        """Test case for get_widget_type

        """
        pass

    def test_get_widget_type_by_name(self):
        """Test case for get_widget_type_by_name

        """
        pass

    def test_get_widget_types(self):
        """Test case for get_widget_types

        """
        pass

    def test_load_client_package(self):
        """Test case for load_client_package

        """
        pass

    def test_queue_entity_batch(self):
        """Test case for queue_entity_batch

        """
        pass

    def test_queue_partner_entity_batch(self):
        """Test case for queue_partner_entity_batch

        """
        pass

    def test_remove_role(self):
        """Test case for remove_role

        """
        pass

    def test_remove_role_permission(self):
        """Test case for remove_role_permission

        """
        pass

    def test_remove_user_role(self):
        """Test case for remove_user_role

        """
        pass

    def test_replace_page(self):
        """Test case for replace_page

        """
        pass

    def test_request_password_reset(self):
        """Test case for request_password_reset

        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        """
        pass

    def test_update_api_key(self):
        """Test case for update_api_key

        """
        pass

    def test_update_block_type(self):
        """Test case for update_block_type

        """
        pass

    def test_update_client(self):
        """Test case for update_client

        """
        pass

    def test_update_dataset(self):
        """Test case for update_dataset

        """
        pass

    def test_update_integration(self):
        """Test case for update_integration

        """
        pass

    def test_update_integration_type(self):
        """Test case for update_integration_type

        """
        pass

    def test_update_page(self):
        """Test case for update_page

        """
        pass

    def test_update_page_preferences_by_page(self):
        """Test case for update_page_preferences_by_page

        """
        pass

    def test_update_role(self):
        """Test case for update_role

        """
        pass

    def test_update_user(self):
        """Test case for update_user

        """
        pass

    def test_update_widget_type(self):
        """Test case for update_widget_type

        """
        pass


if __name__ == '__main__':
    unittest.main()
