# coding: utf-8

"""
    Nucleus REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.6.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_client
from nucleus_client.models.job_overview import JobOverview  # noqa: E501
from nucleus_client.rest import ApiException


class TestJobOverview(unittest.TestCase):
    """JobOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobOverview(self):
        """Test JobOverview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_client.models.job_overview.JobOverview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
