#-*- coding:utf-8 -*-

# This file is generated from the AUTHORS file during the installation process.
# Do not edit it as your changes will be overwritten.

__authors__ = [
    u"Naveen Michaud-Agrawal",
    u"Elizabeth J. Denning",
    u"Christian Beckstein (logo)",
    u"Joshua L. Adelman",
    u"Shobhit Agarwal",
    u"Balasubramanian",
    u"Utkarsh Bansal",
    u"Jonathan Barnoud",
    u"Alejandro Bernardin",
    u"Mateusz Bieniek",
    u"Mateusz Bieniek",
    u"Jose Borreguero",
    u"Sébastien Buchoux",
    u"Sören von Bülow",
    u"David Caplan",
    u"Matthieu Chavent",
    u"Ruggero Cortini",
    u"Robert Delgado",
    u"Xavier Deupi",
    u"Jan Domanski",
    u"David L. Dotson",
    u"Philip Fowler",
    u"Joseph Goose",
    u"Richard J. Gowers",
    u"Lukas Grossar",
    u"Abhinav Gupta",
    u"Benjamin Hall",
    u"Kyle J. Huston",
    u"Joe Jordan",
    u"Max Linke",
    u"Jinju Lu",
    u"Robert McGibbon",
    u"Manuel Nuno Melo",
    u"Fiona B. Naughton",
    u"Alex Nesterenko",
    u"Hai Nguyen",
    u"Danny Parton",
    u"Joshua L. Phillips",
    u"Kashish Punjani",
    u"Vedant Rathore",
    u"Tyler Reddy",
    u"Pedro Reis",
    u"Paul Rigor",
    u"Carlos Yanez S.",
    u"Sean L. Seyler",
    u"Paul Smith",
    u"Andy Somogyi",
    u"Caio S. Souza",
    u"Lukas Stelzl",
    u"Gorman Stock",
    u"Ayush Suhane",
    u"Xiki Tempula",
    u"Isaac Virshup",
    u"Zhuyi Xue",
    u"Johannes Zeman",
    u"Oliver Beckstein"
]
