- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ironic-lib-tempest-partition-agent_ipmitool
        - ironic-lib-tempest-partition-pxe_ipmitool
        - ironic-lib-tempest-wholedisk-agent_ipmitool
        - ironic-lib-tempest-wholedisk-pxe_ipmitool
    gate:
      queue: ironic
      jobs:
        - ironic-lib-tempest-partition-agent_ipmitool
        - ironic-lib-tempest-partition-pxe_ipmitool
        - ironic-lib-tempest-wholedisk-agent_ipmitool
        - ironic-lib-tempest-wholedisk-pxe_ipmitool
