# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro_serving_grpc/manager/entities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hydro_serving_grpc.contract import model_contract_pb2 as hydro__serving__grpc_dot_contract_dot_model__contract__pb2
from hydro_serving_grpc.contract import model_signature_pb2 as hydro__serving__grpc_dot_contract_dot_model__signature__pb2
from hydro_serving_grpc.monitoring import data_profile_types_pb2 as hydro__serving__grpc_dot_monitoring_dot_data__profile__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydro_serving_grpc/manager/entities.proto',
  package='hydrosphere.manager',
  syntax='proto3',
  serialized_options=_b('\n#io.hydrosphere.serving.manager.grpc'),
  serialized_pb=_b('\n)hydro_serving_grpc/manager/entities.proto\x12\x13hydrosphere.manager\x1a\x30hydro_serving_grpc/contract/model_contract.proto\x1a\x31hydro_serving_grpc/contract/model_signature.proto\x1a\x36hydro_serving_grpc/monitoring/data_profile_types.proto\"!\n\x05Model\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"4\n\x07Runtime\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"\xc4\x02\n\x0cModelVersion\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nimage_name\x18\x03 \x01(\t\x12\x11\n\timage_tag\x18\x04 \x01(\t\x12)\n\x05model\x18\x05 \x01(\x0b\x32\x1a.hydrosphere.manager.Model\x12\x35\n\x08\x63ontract\x18\x06 \x01(\x0b\x32#.hydrosphere.contract.ModelContract\x12\x44\n\ndata_types\x18\x07 \x03(\x0b\x32\x30.hydrosphere.manager.ModelVersion.DataTypesEntry\x1aY\n\x0e\x44\x61taTypesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0e\x32\'.hydrosphere.monitoring.DataProfileType:\x02\x38\x01\"\'\n\x0b\x45nvironment\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB%\n#io.hydrosphere.serving.manager.grpcb\x06proto3')
  ,
  dependencies=[hydro__serving__grpc_dot_contract_dot_model__contract__pb2.DESCRIPTOR,hydro__serving__grpc_dot_contract_dot_model__signature__pb2.DESCRIPTOR,hydro__serving__grpc_dot_monitoring_dot_data__profile__types__pb2.DESCRIPTOR,])




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='hydrosphere.manager.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hydrosphere.manager.Model.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='hydrosphere.manager.Model.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=256,
)


_RUNTIME = _descriptor.Descriptor(
  name='Runtime',
  full_name='hydrosphere.manager.Runtime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hydrosphere.manager.Runtime.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='hydrosphere.manager.Runtime.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='hydrosphere.manager.Runtime.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=310,
)


_MODELVERSION_DATATYPESENTRY = _descriptor.Descriptor(
  name='DataTypesEntry',
  full_name='hydrosphere.manager.ModelVersion.DataTypesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hydrosphere.manager.ModelVersion.DataTypesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hydrosphere.manager.ModelVersion.DataTypesEntry.value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=637,
)

_MODELVERSION = _descriptor.Descriptor(
  name='ModelVersion',
  full_name='hydrosphere.manager.ModelVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hydrosphere.manager.ModelVersion.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='hydrosphere.manager.ModelVersion.image_name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_tag', full_name='hydrosphere.manager.ModelVersion.image_tag', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='hydrosphere.manager.ModelVersion.model', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract', full_name='hydrosphere.manager.ModelVersion.contract', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_types', full_name='hydrosphere.manager.ModelVersion.data_types', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODELVERSION_DATATYPESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=637,
)


_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='hydrosphere.manager.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hydrosphere.manager.Environment.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='hydrosphere.manager.Environment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=678,
)

_MODELVERSION_DATATYPESENTRY.fields_by_name['value'].enum_type = hydro__serving__grpc_dot_monitoring_dot_data__profile__types__pb2._DATAPROFILETYPE
_MODELVERSION_DATATYPESENTRY.containing_type = _MODELVERSION
_MODELVERSION.fields_by_name['model'].message_type = _MODEL
_MODELVERSION.fields_by_name['contract'].message_type = hydro__serving__grpc_dot_contract_dot_model__contract__pb2._MODELCONTRACT
_MODELVERSION.fields_by_name['data_types'].message_type = _MODELVERSION_DATATYPESENTRY
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['Runtime'] = _RUNTIME
DESCRIPTOR.message_types_by_name['ModelVersion'] = _MODELVERSION
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'hydro_serving_grpc.manager.entities_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.manager.Model)
  ))
_sym_db.RegisterMessage(Model)

Runtime = _reflection.GeneratedProtocolMessageType('Runtime', (_message.Message,), dict(
  DESCRIPTOR = _RUNTIME,
  __module__ = 'hydro_serving_grpc.manager.entities_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.manager.Runtime)
  ))
_sym_db.RegisterMessage(Runtime)

ModelVersion = _reflection.GeneratedProtocolMessageType('ModelVersion', (_message.Message,), dict(

  DataTypesEntry = _reflection.GeneratedProtocolMessageType('DataTypesEntry', (_message.Message,), dict(
    DESCRIPTOR = _MODELVERSION_DATATYPESENTRY,
    __module__ = 'hydro_serving_grpc.manager.entities_pb2'
    # @@protoc_insertion_point(class_scope:hydrosphere.manager.ModelVersion.DataTypesEntry)
    ))
  ,
  DESCRIPTOR = _MODELVERSION,
  __module__ = 'hydro_serving_grpc.manager.entities_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.manager.ModelVersion)
  ))
_sym_db.RegisterMessage(ModelVersion)
_sym_db.RegisterMessage(ModelVersion.DataTypesEntry)

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENT,
  __module__ = 'hydro_serving_grpc.manager.entities_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.manager.Environment)
  ))
_sym_db.RegisterMessage(Environment)


DESCRIPTOR._options = None
_MODELVERSION_DATATYPESENTRY._options = None
# @@protoc_insertion_point(module_scope)
