"""
Author: qiacai
"""

"""
Constants to use for ada
"""

"""
Constants for algorithms
"""
ALGORITHM_DEFAULT_WINDOW_REGEX = '^([0-9]*)(y|M|w|d|h|m|s|[0-9])$'

ALGORITHM_DEFAULT_TIMEZONE = 'US/Pacific'

ALGORITHM_DEFAULT_CALCULATOR_PERCENTILE_PERCENTILE = 50

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_PERCENTILE = 5

ALGORITHM_DEFAULT_CALCULATOR_VALUE_SCALE_OPERATOR = '*'

ALGORITHM_DEFAULT_CALCULATOR_TIME_OFFSET_OFFSET = 0

ALGORITHM_DEFAULT_CALCULATOR_EXPONENTIAL_SMOOTH_SMOOTHING_FACTOR = 0.3

ALGORITHM_DEFAULT_CALCULATOR_SEASONAL_DECOMPOSE_FREQ = 24

ALGORITHM_DEFAULT_CALCULATOR_SEASONAL_DECOMPOSE_TREND_ONLY = False

ALGORITHM_DEFAULT_CALCULATOR_SEASONAL_DECOMPOSE_FILLNA = False

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_UPPER_PERCENTILE = 95

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_LOWER_PERCENTILE = 5

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_IS_UPPER = True


ALGORITHM_DEFAULT_HARD_THRESHOLD_THRESHOLD = 0

ALGORITHM_DEFAULT_HARD_THRESHOLD_OPERATOR = '>'

ALGORITHM_DEFAULT_HARD_THRESHOLD_LOCAL_WINDOW = '1'

ALGORITHM_DEFAULT_HARD_THRESHOLD_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE


ALGORITHM_DEFAULT_SOFT_THRESHOLD_OPERATOR = '>'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_LOCAL_WINDOW = '1'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_LAG_WINDOW = '1'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_BENCHMARK_METHOD = 'mean'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_BOUND_METHOD = 'std'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_FACTOR = 3

ALGORITHM_DEFAULT_SOFT_THRESHOLD_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE


ALGORITHM_DEFAULT_CUSHION_THRESHOLD_OPERATOR = '>'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_LOCAL_WINDOW = '1'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_LAG_WINDOW = '1'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_BENCHMARK_METHOD = 'mean'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_BOUND_METHOD = 'std'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_FACTOR = 2

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_UPPER_PERCENTILE = ALGORITHM_DEFAULT_CALCULATOR_CUSHION_UPPER_PERCENTILE

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_LOWER_PERCENTILE = ALGORITHM_DEFAULT_CALCULATOR_CUSHION_LOWER_PERCENTILE

