[tool.poetry]
name = "hello_todo"
version = "0.1.0"
description = ""
authors = ["Mathias Ngo <gogs@fake.local>"]

[tool.poetry.dependencies]
python = "*"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
