# Generated by Django 2.1.2 on 2018-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20181002_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthorship',
            name='student_colleague',
            field=models.IntegerField(blank=True, choices=[(0, 'Undergraduate'), (10, 'Masters'), (20, 'Doctoral')], null=True),
        ),
        migrations.AlterField(
            model_name='bookauthorship',
            name='student_colleague',
            field=models.IntegerField(blank=True, choices=[(0, 'Undergraduate'), (10, 'Masters'), (20, 'Doctoral')], null=True),
        ),
        migrations.AlterField(
            model_name='chapterauthorship',
            name='student_colleague',
            field=models.IntegerField(blank=True, choices=[(0, 'Undergraduate'), (10, 'Masters'), (20, 'Doctoral')], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_level',
            field=models.IntegerField(choices=[(0, 'Undergrad'), (10, 'Masters'), (20, 'Doctoral')], verbose_name='student level'),
        ),
        migrations.AlterField(
            model_name='datasetauthorship',
            name='student_colleague',
            field=models.IntegerField(blank=True, choices=[(0, 'Undergraduate'), (10, 'Masters'), (20, 'Doctoral')], null=True),
        ),
        migrations.AlterField(
            model_name='reportauthorship',
            name='student_colleague',
            field=models.IntegerField(blank=True, choices=[(0, 'Undergraduate'), (10, 'Masters'), (20, 'Doctoral')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Undergraduate'), (10, 'Masters'), (20, 'Doctoral')], null=True),
        ),
    ]
