language: python
python:
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install .
script:
- pytest
env:
  global:
  - secure: H1QrFjpJZ1/Gn8JsdqzzG0RWx700cPT1AZIkiGRbJXUQqunJ/A5vdHJm9XBKP+1/KE6TaDtb19bKj7MYrHk6YEul46O7z/cUXF/Ke1hK3Dc25rnLxbAVlaedpcoXpHXHuxgkK4cWMcxtFukWhD59nm8XurpRB7QGFuSoVBiDCXxCnQMaF5Jd2nGstf9F8+7kb0KokFMF4DW8WoqWdnbuQsizGFhoq9Kr0WB1HLRg7RF//Jqmg9lilnmCYp0kiyvXKfjEq1oF0SAVUDPLiMrdvcCPrqASelvqrYjMrjLw/NvearHyFxlaz+bAgMjws7rFVLH7FPiI5x7FdcJVWmUGlUFfSp4ZdaXkXjuhgAF+NvWM+wOI/d1LOiEq2u5bSEBBVKTlSe2BKySnxr8Bdwm/5Xha6d2L4pYNtHRF27pzcZJnp2sKxX0vMQIVUM4f5eYJRiSQv5JhTodPNS6yYaQNcIbSR5tb9T3A44XIu1GJBbLEJsZ8snNW1UIDqYwrurqV/sjoctdzWvd2ba9JAdSft2Ur4c1zxOx+H3cxK5GoV+Ag8oLLc8uopDdWDz8zz0pUEwAmg1xfXDvuRwcAzJCzn9PCbPFXQEQU/As9Al3nkjrz909UJLi41+oXHd5jYnjLGib7XPml5i8W0lJ0W2zVsNhkq2L7cmNLhsSxBcM7fCA=
  - secure: G4xLfDAG3JPushLPT9qhG41LjVloJIHmYeYVt3FNX5MzjmG9OV9V3hrvd42JWMX54F652umxloSC6rQ9MrYjjw20i/9k1KUpgzydSOINMT2jXD5QTHZwE53GAYU8ApCYKLIwuxBnPkUf4XSlFHy/wml6sXr9Y/zChtvwlUlZCBKasZb/AfIzLrwkcYECArtZAyVzXJxFRirUxFPvqJv7DcOPzglT3jdZXj2JCKu88La8cjXSbj9XUnEEgpWiNkZvGTbIOlH5ITrXxj+gjwzd8n5okoJ3lVJIThgnWzsVnD8DlKkIU+8cmXNcypEnRDdLibbs2FrXxYfUqEXcM1LumhQOkHFledA5qw/NfIw+of1uhiwbR1JlOvgMQOURQHqSaBorhmy102eOtg+yUW69s5+hY+kF7CqyjuvVYGPZuURPNyDP97s0NCTU5a24JOeR1OAFGJUd3t7RGAB45jc65c/hgcWMahU6bQzevZlEzHEl9aW4Jp/wK5jd42VuPh0zhpM913DpSp2NX6Iz8bYBkRAcQJ+5o2Kly5Gyyyjset98lFdMdvWgXIpDkJPtSE+pMsD51iMBmatWxQz9zGDXuzkBqPrPAGL5JnPqhK2uZJvo83If+Mp6y5ERkiHeHcHF2vOOwOBBUk6mra7ACWLJdJNBDacmTJMs9xgNM1RTZC8=
