version: 2
jobs:
    build:
     docker:
        - image: circleci/python:2.7
          environment:

     steps:
        - checkout
        - run:
            name: deps
            command: |
                pip install --upgrade -r requirements.txt

        - run:
            name: run tests
            command: |
              comptests --nonose duckietown_challenges_tests --reset
