[tool.poetry]
name = "rororo"
version = "1.2.0a1"
description = "Collection of utilities, helpers, and principles for building Python backend applications. Supports aiohttp.web, Flask, and your web-framework"
authors = ["Igor Davydenko <iam@igordavydenko.com>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://igordavydenko.com/projects.html#rororo"
repository = "https://github.com/playpauseandstop/rororo"
documentation = "https://rororo.readthedocs.io/"
keywords = ["utilities", "helpers", "principles", "backend", "backend application", "aiohttp", "flask", "web framework"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: WSGI",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
]

[tool.poetry.dependencies]
python = "^3.5.3"
jsonschema = "^2.6 || ^3.0"

[tool.poetry.dev-dependencies]
tox = "^3.5"
coveralls = "^1.5"
Sphinx = "^1.8"
sphinx_autodoc_typehints = "^1.3"
wheel = "^0.32.1"
aiohttp = "^3.4"
jsl = "^0.2.4"
fastjsonschema = "^2.4"
coverage = "^4.5"
twine = "^1.12"
