#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['clicker']

package_data = \
{'': ['*']}

setup(name='clicker',
      version='0.2.0',
      description='clicker',
      author='Ryan Wang',
      author_email='hwwangwang@gmail.com',
      url='https://github.com/ryanwang520',
      packages=packages,
      package_data=package_data,
     )
