
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-05T09:20:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8ae32e598fe65aa08f74a4c1c72751f5141d424",
 "version": "0.6.1+87.gd8ae32e"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
