[tool.poetry]
name = "hello_todo"
version = "0.1.5"
description = ""
authors = ["Mathias Ngo <ngo.mathias@gmail.com>"]

[tool.poetry.scripts]
todos = "hello_todo.cli:todo_lists"
init_todos = "hello_todo.cli:init_todo"
add_todolist = "hello_todo.cli:add_todolist"
add_todo = "hello_todo.cli:add_todo"
todolist = "hello_todo.cli:todo_list"


[tool.poetry.dependencies]
python = "*"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
