# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import molo.core.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('yourwords', '0007_add_yourwords_permission_to_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourwordscompetitionentry',
            options={'permissions': (('can_view_yourwords_entry', 'Can View YourWords Entry'),), 'verbose_name': 'YourWords Competition Entry', 'verbose_name_plural': 'YourWords Competition Entries'},
        ),
        migrations.AlterField(
            model_name='yourwordscompetition',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', molo.core.blocks.MarkDownBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='Item'))), ('numbered_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='Item'))), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yourwordscompetition',
            name='extra_style_hints',
            field=models.TextField(blank=True, default='', help_text='Styling options that can be applied to this section and all its descendants', null=True),
        ),
    ]
