# Generated by Django 2.1.1 on 2018-09-15 13:18

import base.fields.ImageSetField
import base.model.Images
import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名')),
                ('image', models.ImageField(storage=base.model.Images.ImageStorage(), upload_to='img/%Y/%m/%d')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SuperAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(default='', max_length=256, verbose_name='昵称')),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'super_account',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', base.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='邮箱')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('covers', base.fields.ImageSetField.ImageSetField(blank=True, verbose_name='封面')),
            ],
        ),
    ]
