[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools_scm",
    # Cython is an optional build requirement, as the sdist includes
    # pre-cythonized *.c sources
    # "cython",
]
build-backend = "setuptools.build_meta"
