
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-08T15:44:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "189ee5e7cab41339427b596687fc215ff27e0d16",
 "version": "0.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
