---
#- name: provision resources
#  debug:
#    msg: |
#        api_endpoint: {{ resource_group.api_endpoint }}
#        resource: {{ resource }}

- name: call OpenShift with user arguments
  openshift:
    api_endpoint: "{{ resource_group.api_endpoint }}"
    api_token: "{{ resource_group.api_token | default(omit) }}"
    insecure: "{{ resource_group.insecure | default(omit) }}"
    inline_data: "{{ resource.inline_data | default(omit) }}"
    file_reference: "{{ resource.file_reference | default(omit) }}"
    state: "{{ state }}"
  register: openshift_host
  no_log: "{{ not debug_mode }}"

- name: add output to topology
  set_fact:
    topology_outputs_openshift_resources: "{{ topology_outputs_openshift_resources + [openshift_host] }}"
  when: state == "present"
