
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-11T12:47:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5bd54fd17ef01cb604299e673fc9c0e5d1905f5",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
