[tool.poetry]
name = "zhlib-snapshot"
version = "0.1.2"
description = "Snapshot of zhlib: Dictionaries and what to learn in Chinese"
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"
peewee = "^3.7"
wordfreq = "^2.2"
jieba = "^0.39.0"
regex = "=2018.02.21"

[tool.poetry.dev-dependencies]
#zhlib = {path = "../zhlib"}
bs4 = "^0.0.1"
tqdm = "^4.28"
prettyprinter = "^0.14.0"
