[tool.poetry]
name = "awsrightsizer"
version = "1.0.7.2"
description = "A Python3 tool to help you determine the correct instance types to use for your running EC2/RDS instances."
authors = ["Jordan Gregory <jordan@gregory-dev.io>"]
license = "Apache-2.0"
readme = "README.rst"
homepage = "http://www.gregory-dev.io/awsrightsizer"
documentation = "http://awsrightsizer.readthedocs.io/"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: Apache Software License',
    'Programming Language :: Python :: 3 :: Only'
]
packages = [
    { include = "rightsizer" },
]

[tool.poetry.scripts]
rightsizer = 'rightsizer.main:main'

[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.9"

[tool.poetry.dev-dependencies]
pytest = "^3.9"
