sudo: required
language: python
python:
  - "3.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -e .[test]
    - pip install flake8 codecov
    - sleep 5
script:
    - flake8 aiofluent --config=setup.cfg
    - pytest -s --cov=aiofluent -s --tb=native -v --cov-report term-missing --cov-append tests
after_success:
    - codecov