# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EnergyProjectEnergySavingsChildDTO(Model):
    """EnergyProjectEnergySavingsChildDTO.

    :param energy_savings: The energy savings amount
    :type energy_savings: float
    :param energy_savings_unit: The energy savings unit
    :type energy_savings_unit:
     ~energycap.sdk.models.EnergyProjectEnergySavingsUnitDTO
    """

    _attribute_map = {
        'energy_savings': {'key': 'energySavings', 'type': 'float'},
        'energy_savings_unit': {'key': 'energySavingsUnit', 'type': 'EnergyProjectEnergySavingsUnitDTO'},
    }

    def __init__(self, energy_savings=None, energy_savings_unit=None):
        super(EnergyProjectEnergySavingsChildDTO, self).__init__()
        self.energy_savings = energy_savings
        self.energy_savings_unit = energy_savings_unit
