---
applications:
- guillotina_hydraidp
databases:
  db:
    storage: DUMMY_FILE
host: localhost
port: 8080
root_user:
  password: root
auth_extractors:
- guillotina.auth.extractors.BearerAuthPolicy
- guillotina.auth.extractors.BasicAuthPolicy
- guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
- guillotina.auth.validators.SaltedHashPasswordValidator
- guillotina.auth.validators.JWTValidator
cors:
  allow_origin:
  - http://localhost:8080
  - "chrome-extension://*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  - PUT
  - OPTIONS
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
jwt:
  secret: foobar
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner
auth_providers:
  hydra:
    configuration:
      client_id: auth-code-client
      client_secret: secret
      base_url: http://localhost:4444/
      authorize_url: http://localhost:4444/oauth2/auth
      access_token_url: http://localhost:4444/oauth2/token
    state: true
    scope: openid offline
# could be pg or cockroach
hydra_db:
  # dsn: postgres://hydra:secret@localhost:5432/hydra
  dsn: postgres://guillotina@localhost:5432/guillotina
  pool_size: 20

# hydra admin url should be internal, protected!
hydra_admin_url: http://localhost:4445/