
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-24T00:12:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f4a4137e58cd7d7716e8193b4de12e52ffb7832",
 "version": "1.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
