# Generated by Django 2.1.2 on 2018-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotask',
            options={'ordering': ['-id'], 'verbose_name': '自动抓取', 'verbose_name_plural': '自动抓取'},
        ),
        migrations.AddField(
            model_name='autotask',
            name='content_replace_from',
            field=models.CharField(blank=True, help_text='以JSON数组,类似[("eee","ffff"),(444, "opt")]', max_length=128, verbose_name='原内容'),
        ),
        migrations.AddField(
            model_name='autotask',
            name='content_replace_to',
            field=models.CharField(blank=True, max_length=128, verbose_name='替换内容'),
        ),
        migrations.AddField(
            model_name='autotask',
            name='title_replace_from',
            field=models.CharField(blank=True, help_text='以JSON数组,类似[("eee","ffff"),(444, "opt")]', max_length=128, verbose_name='原标题内容'),
        ),
        migrations.AddField(
            model_name='autotask',
            name='title_replace_to',
            field=models.CharField(blank=True, max_length=128, verbose_name='替换标题内容'),
        ),
        migrations.AlterField(
            model_name='autotask',
            name='content_except',
            field=models.CharField(blank=True, default='[]', help_text='以json格式', max_length=255, null=True, verbose_name='内容排除'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='at_article',
        ),
        migrations.AlterModelTable(
            name='author',
            table='at_author',
        ),
        migrations.AlterModelTable(
            name='autotask',
            table='at_auto_task',
        ),
        migrations.AlterModelTable(
            name='category',
            table='at_category',
        ),
        migrations.AlterModelTable(
            name='crawllogs',
            table='at_crawl_logs',
        ),
        migrations.AlterModelTable(
            name='remoteimages',
            table='at_remote_images',
        ),
    ]
