[tool.poetry]
name = "redditsweeper"
version = "1.0.0"
description = "Tool for automated removal of old reddit comments."
authors = ["Scott Hand"]
license = "MIT"
readme = "README.md"
repository = "https://www.github.com/scott-hand/redditsweeper"

[tool.poetry.dependencies]
python = "^2.7 || ^3.6 || ^3.7"
colorama = "^0.4.0"
ConfigArgParse = "^0.13.0"
praw = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^3.9"
coverage = "^4.5"
tox = "^3.5"
responses = "^0.10.2"
pytest-cov = "^2.6"

[tool.poetry.scripts]
redditsweeper = "redditsweeper.app:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
