## tag and version are updated by the versioner.py script in the toytree repo
## which then writes to meta.yaml during the conda build.
package:
  name: toytree
  version: "0.1.6"

source:
  git_url: https://github.com/eaton-lab/toytree.git
  git_tag: 0.1.6

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #str: '0.1.6'   ## the string before it: toytree-0.1.5-0
  #number: 0      ## the version number given to the build

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.1  ## eaton-lab forked version for now
    - pypng
    - reportlab
    - jupyter
    - nbconvert
    - requests
  run:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.1  ## eaton-lab forked version for now
    - pypng
    - reportlab
    - jupyter
    - nbconvert
    - requests

test:
  imports:
    - toytree

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using Toyplot.
