# automatically generated by the FlatBuffers compiler, do not modify

# namespace: lumby_fbs

import flatbuffers

class OrderBook(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOrderBook(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OrderBook()
        x.Init(buf, n + offset)
        return x

    # OrderBook
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OrderBook
    def OrdersContent(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .OrderContent import OrderContent
            obj = OrderContent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderBook
    def OrdersContentLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OrderBook
    def Crc32Checksum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def OrderBookStart(builder): builder.StartObject(2)
def OrderBookAddOrdersContent(builder, ordersContent): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ordersContent), 0)
def OrderBookStartOrdersContentVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OrderBookAddCrc32Checksum(builder, crc32Checksum): builder.PrependInt32Slot(1, crc32Checksum, 0)
def OrderBookEnd(builder): return builder.EndObject()
