# automatically generated by the FlatBuffers compiler, do not modify

# namespace: lumby_fbs

import flatbuffers

class OrderUpdates(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOrderUpdates(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OrderUpdates()
        x.Init(buf, n + offset)
        return x

    # OrderUpdates
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OrderUpdates
    def OrderUpdates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .OrderUpdate import OrderUpdate
            obj = OrderUpdate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderUpdates
    def OrderUpdatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def OrderUpdatesStart(builder): builder.StartObject(1)
def OrderUpdatesAddOrderUpdates(builder, orderUpdates): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(orderUpdates), 0)
def OrderUpdatesStartOrderUpdatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OrderUpdatesEnd(builder): return builder.EndObject()
