package:
  name: colormath
  version: {{ environ.get('GIT_DESCRIBE_TAG', 0) }}

source:
   git_url: https://github.com/gtaylor/python-colormath.git

build:
  script: build.sh
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python 
    #{{PY_VER}}*,>=2.7
    - enum34
    - networkx
    - setuptools
    - numpy >=1.7
  run:
    - networkx
    - setuptools
    - numpy >=1.7


about:
  home: http://python-colormath.readthedocs.org/en/latest/
  license: BSD
  summary: This module implements a large number of different color operations such as color space conversions, Delta E, and density to spectral.
