- job:
    name: senlinclient-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/senlinclient-dsvm-functional/run.yaml
    post-run: playbooks/legacy/senlinclient-dsvm-functional/post.yaml
    timeout: 7200
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/python-senlinclient
      - openstack/senlin

- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - openstackclient-plugin-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - senlinclient-dsvm-functional:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - senlinclient-dsvm-functional:
            voting: false
        - openstack-tox-lower-constraints
