---

exclude:
    - '^.*(.js)$'
    - '^.*(.css)$'
    - '^.*(.ico)$'
    - '^.*(.png)$'
    - '^.*(.svg)$'
    - '^.*(.html)$'
    - '^.*(.sh)$'
    - '^.*(.json)$'
    - '^.*(.htaccess)$'
    - '^.*(.conf)$'
    - '^.*(.hbs)$'
    - '^.*(.editorconfig)$'
    - '^.*(.nvmrc)$'
    - '^.*(.gitattributes)$'
    - '^.*(.gitignore)$'
    - '^.*(.prettierignore)$'
    - '^.*(.stylelintrc)$'

ignore:
    - '^(.*)node_modules(.*)$'

variables:
    -   name: gcpproject # config.yml
        prompt: "GCP Project Name"
        default: "trusty-acre-156607"
    
    -   name: frontendname
        prompt: "Frontend Name"
        default: "identities"
    
    -   name: dockerusername
        prompt: "Dockerhub Username"
        default: "dennisseidel"