# Generated by Django 2.0.7 on 2018-08-09 10:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postie', '0003_auto_20180504_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Score')),
                ('detail', models.CharField(max_length=128, verbose_name='Detail')),
                ('employees', models.ManyToManyField(related_name='reports', to='postie.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AlterField(
            model_name='letter',
            name='html',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='plain',
            field=models.TextField(blank=True, null=True, verbose_name='Plain text'),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='html',
            field=models.TextField(blank=True, help_text='Write variables inside {{  }}.', null=True, verbose_name='HTML text'),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='plain',
            field=models.TextField(blank=True, help_text='Alternative version of html text.Write variables inside {{  }}.', null=True, verbose_name='Plain text'),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='subject',
            field=models.CharField(help_text='Write variables inside {{  }}.', max_length=255, null=True, verbose_name='Subject'),
        ),
    ]
