#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['controlgraph', 'networkx', 'pydot']

entry_points = \
{'console_scripts': ['dbp = dbp:main']}

setup(name='dbp',
      version='0.6.0',
      description='Simple program to manage gbp-docker container lifecycle.',
      author='Dell inc.',
      author_email='opx-infra@openswitch.net',
      url='https://openswitch.net',
      py_modules=['dbp'],
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.5,<4',
     )
