
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-26T17:48:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "66adc53cb04209032b5196dcd1d968a45557d286",
 "version": "v0.3.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
