[tool.poetry]
name = "str2port"
version = "0.1.1"
description = "Convert string to md5 hash, then to port number. No randomization involved."
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/patarapolw/str2port"
homepage = "https://github.com/patarapolw/str2port"

[tool.poetry.dependencies]
python = "*"
click = "^7.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
str2port = 'str2port.__main__:cli'
