language: python

python:
  - "3.5"
  - "2.7"

install:
  - pip install numpy scipy uncertainties matplotlib codecov pytest-cov

script:
  - pytest --cov=multinorm --cov-report=term-missing

after_success:
  - codecov
