# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/python/auxygen/auxygen/gui/ui/ui_lakeshore_widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widgetSettings(object):
    def setupUi(self, widgetSettings):
        widgetSettings.setObjectName("widgetSettings")
        widgetSettings.resize(460, 231)
        widgetSettings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(widgetSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.comboRange = QtWidgets.QComboBox(widgetSettings)
        self.comboRange.setObjectName("comboRange")
        self.comboRange.addItem("")
        self.comboRange.addItem("")
        self.comboRange.addItem("")
        self.comboRange.addItem("")
        self.gridLayout.addWidget(self.comboRange, 2, 1, 1, 1)
        self.spinManual = QtWidgets.QDoubleSpinBox(widgetSettings)
        self.spinManual.setPrefix("")
        self.spinManual.setMaximum(100.0)
        self.spinManual.setObjectName("spinManual")
        self.gridLayout.addWidget(self.spinManual, 3, 1, 1, 1)
        self.labelHeater = QtWidgets.QLabel(widgetSettings)
        self.labelHeater.setObjectName("labelHeater")
        self.gridLayout.addWidget(self.labelHeater, 3, 0, 1, 1)
        self.buttonManual = QtWidgets.QPushButton(widgetSettings)
        self.buttonManual.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonManual.setIcon(icon)
        self.buttonManual.setObjectName("buttonManual")
        self.gridLayout.addWidget(self.buttonManual, 3, 2, 1, 1)
        self.labelSetpoint = QtWidgets.QLabel(widgetSettings)
        self.labelSetpoint.setObjectName("labelSetpoint")
        self.gridLayout.addWidget(self.labelSetpoint, 4, 0, 1, 1)
        self.checkBoxOutput = QtWidgets.QCheckBox(widgetSettings)
        self.checkBoxOutput.setObjectName("checkBoxOutput")
        self.gridLayout.addWidget(self.checkBoxOutput, 0, 1, 1, 1)
        self.buttonRange = QtWidgets.QPushButton(widgetSettings)
        self.buttonRange.setText("")
        self.buttonRange.setIcon(icon)
        self.buttonRange.setObjectName("buttonRange")
        self.gridLayout.addWidget(self.buttonRange, 2, 2, 1, 1)
        self.buttonPID = QtWidgets.QPushButton(widgetSettings)
        self.buttonPID.setText("")
        self.buttonPID.setIcon(icon)
        self.buttonPID.setObjectName("buttonPID")
        self.gridLayout.addWidget(self.buttonPID, 1, 2, 1, 1)
        self.buttonSetpoint = QtWidgets.QPushButton(widgetSettings)
        self.buttonSetpoint.setText("")
        self.buttonSetpoint.setIcon(icon)
        self.buttonSetpoint.setObjectName("buttonSetpoint")
        self.gridLayout.addWidget(self.buttonSetpoint, 4, 2, 1, 1)
        self.spinSetpoint = QtWidgets.QDoubleSpinBox(widgetSettings)
        self.spinSetpoint.setMaximum(1000.0)
        self.spinSetpoint.setProperty("value", 300.0)
        self.spinSetpoint.setObjectName("spinSetpoint")
        self.gridLayout.addWidget(self.spinSetpoint, 4, 1, 1, 1)
        self.labelPID = QtWidgets.QLabel(widgetSettings)
        self.labelPID.setObjectName("labelPID")
        self.gridLayout.addWidget(self.labelPID, 1, 0, 1, 1)
        self.labelRange = QtWidgets.QLabel(widgetSettings)
        self.labelRange.setObjectName("labelRange")
        self.gridLayout.addWidget(self.labelRange, 2, 0, 1, 1)
        self.editPID = QtWidgets.QLineEdit(widgetSettings)
        self.editPID.setObjectName("editPID")
        self.gridLayout.addWidget(self.editPID, 1, 1, 1, 1)
        self.buttonMacroPID = QtWidgets.QPushButton(widgetSettings)
        self.buttonMacroPID.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/macro"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonMacroPID.setIcon(icon1)
        self.buttonMacroPID.setObjectName("buttonMacroPID")
        self.gridLayout.addWidget(self.buttonMacroPID, 1, 3, 1, 1)
        self.buttonMacroRange = QtWidgets.QPushButton(widgetSettings)
        self.buttonMacroRange.setText("")
        self.buttonMacroRange.setIcon(icon1)
        self.buttonMacroRange.setObjectName("buttonMacroRange")
        self.gridLayout.addWidget(self.buttonMacroRange, 2, 3, 1, 1)
        self.buttonMacroManual = QtWidgets.QPushButton(widgetSettings)
        self.buttonMacroManual.setText("")
        self.buttonMacroManual.setIcon(icon1)
        self.buttonMacroManual.setObjectName("buttonMacroManual")
        self.gridLayout.addWidget(self.buttonMacroManual, 3, 3, 1, 1)
        self.buttonMacroSetpoint = QtWidgets.QPushButton(widgetSettings)
        self.buttonMacroSetpoint.setText("")
        self.buttonMacroSetpoint.setIcon(icon1)
        self.buttonMacroSetpoint.setObjectName("buttonMacroSetpoint")
        self.gridLayout.addWidget(self.buttonMacroSetpoint, 4, 3, 1, 1)

        self.retranslateUi(widgetSettings)
        QtCore.QMetaObject.connectSlotsByName(widgetSettings)
        widgetSettings.setTabOrder(self.checkBoxOutput, self.editPID)
        widgetSettings.setTabOrder(self.editPID, self.buttonPID)
        widgetSettings.setTabOrder(self.buttonPID, self.buttonMacroPID)
        widgetSettings.setTabOrder(self.buttonMacroPID, self.comboRange)
        widgetSettings.setTabOrder(self.comboRange, self.buttonRange)
        widgetSettings.setTabOrder(self.buttonRange, self.buttonMacroRange)
        widgetSettings.setTabOrder(self.buttonMacroRange, self.spinManual)
        widgetSettings.setTabOrder(self.spinManual, self.buttonManual)
        widgetSettings.setTabOrder(self.buttonManual, self.buttonMacroManual)
        widgetSettings.setTabOrder(self.buttonMacroManual, self.spinSetpoint)
        widgetSettings.setTabOrder(self.spinSetpoint, self.buttonSetpoint)
        widgetSettings.setTabOrder(self.buttonSetpoint, self.buttonMacroSetpoint)

    def retranslateUi(self, widgetSettings):
        _translate = QtCore.QCoreApplication.translate
        widgetSettings.setWindowTitle(_translate("widgetSettings", "Form"))
        self.comboRange.setItemText(0, _translate("widgetSettings", "Off"))
        self.comboRange.setItemText(1, _translate("widgetSettings", "Low"))
        self.comboRange.setItemText(2, _translate("widgetSettings", "Medium"))
        self.comboRange.setItemText(3, _translate("widgetSettings", "High"))
        self.spinManual.setSuffix(_translate("widgetSettings", " %"))
        self.labelHeater.setText(_translate("widgetSettings", "Heater: 000.00 %"))
        self.labelSetpoint.setText(_translate("widgetSettings", "Setpoint: 300.00 K"))
        self.checkBoxOutput.setText(_translate("widgetSettings", "Output"))
        self.spinSetpoint.setSuffix(_translate("widgetSettings", " K"))
        self.labelPID.setText(_translate("widgetSettings", "PID: 0 0 0"))
        self.labelRange.setText(_translate("widgetSettings", "Range: Off"))

from . import resources_rc
