# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/python/auxygen/auxygen/gui/ui/ui_lakeshore_sensors.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widgetSensors(object):
    def setupUi(self, widgetSensors):
        widgetSensors.setObjectName("widgetSensors")
        widgetSensors.resize(375, 349)
        widgetSensors.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(widgetSensors)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBoxA = QtWidgets.QCheckBox(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBoxA.setFont(font)
        self.checkBoxA.setTristate(True)
        self.checkBoxA.setObjectName("checkBoxA")
        self.gridLayout_3.addWidget(self.checkBoxA, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(widgetSensors)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 0, 1, 2, 1)
        self.checkBoxB = QtWidgets.QCheckBox(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBoxB.setFont(font)
        self.checkBoxB.setTristate(True)
        self.checkBoxB.setObjectName("checkBoxB")
        self.gridLayout_3.addWidget(self.checkBoxB, 0, 2, 1, 1)
        self.labelA = QtWidgets.QLabel(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelA.setFont(font)
        self.labelA.setObjectName("labelA")
        self.gridLayout_3.addWidget(self.labelA, 1, 0, 1, 1)
        self.labelB = QtWidgets.QLabel(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelB.setFont(font)
        self.labelB.setObjectName("labelB")
        self.gridLayout_3.addWidget(self.labelB, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line_4 = QtWidgets.QFrame(widgetSensors)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBoxC = QtWidgets.QCheckBox(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBoxC.setFont(font)
        self.checkBoxC.setTristate(True)
        self.checkBoxC.setObjectName("checkBoxC")
        self.gridLayout_2.addWidget(self.checkBoxC, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(widgetSensors)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 1, 2, 1)
        self.checkBoxD = QtWidgets.QCheckBox(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBoxD.setFont(font)
        self.checkBoxD.setTristate(True)
        self.checkBoxD.setObjectName("checkBoxD")
        self.gridLayout_2.addWidget(self.checkBoxD, 0, 2, 1, 1)
        self.labelC = QtWidgets.QLabel(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelC.setFont(font)
        self.labelC.setObjectName("labelC")
        self.gridLayout_2.addWidget(self.labelC, 1, 0, 1, 1)
        self.labelD = QtWidgets.QLabel(widgetSensors)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelD.setFont(font)
        self.labelD.setObjectName("labelD")
        self.gridLayout_2.addWidget(self.labelD, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(widgetSensors)
        QtCore.QMetaObject.connectSlotsByName(widgetSensors)

    def retranslateUi(self, widgetSensors):
        _translate = QtCore.QCoreApplication.translate
        widgetSensors.setWindowTitle(_translate("widgetSensors", "Form"))
        self.checkBoxA.setText(_translate("widgetSensors", "A"))
        self.checkBoxB.setText(_translate("widgetSensors", "B"))
        self.labelA.setText(_translate("widgetSensors", "000.00 K"))
        self.labelB.setText(_translate("widgetSensors", "000.00 K"))
        self.checkBoxC.setText(_translate("widgetSensors", "C"))
        self.checkBoxD.setText(_translate("widgetSensors", "D"))
        self.labelC.setText(_translate("widgetSensors", "000.00 K"))
        self.labelD.setText(_translate("widgetSensors", "000.00 K"))

