# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/python/auxygen/auxygen/gui/ui/ui_wcryo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WCryo(object):
    def setupUi(self, WCryo):
        WCryo.setObjectName("WCryo")
        WCryo.resize(864, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cryo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WCryo.setWindowIcon(icon)
        WCryo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(WCryo)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(WCryo)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sampleTempLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(28)
        self.sampleTempLabel.setFont(font)
        self.sampleTempLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sampleTempLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sampleTempLabel.setObjectName("sampleTempLabel")
        self.horizontalLayout_2.addWidget(self.sampleTempLabel)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.setTempLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(10)
        self.setTempLabel.setFont(font)
        self.setTempLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setTempLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.setTempLabel.setObjectName("setTempLabel")
        self.gridLayout.addWidget(self.setTempLabel, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gasSetTempLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(10)
        self.gasSetTempLabel.setFont(font)
        self.gasSetTempLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gasSetTempLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gasSetTempLabel.setObjectName("gasSetTempLabel")
        self.gridLayout.addWidget(self.gasSetTempLabel, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.tempErrorLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(10)
        self.tempErrorLabel.setFont(font)
        self.tempErrorLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tempErrorLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tempErrorLabel.setObjectName("tempErrorLabel")
        self.gridLayout.addWidget(self.tempErrorLabel, 2, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.statusLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(10)
        self.statusLabel.setFont(font)
        self.statusLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.phaseLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseLabel.sizePolicy().hasHeightForWidth())
        self.phaseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(10)
        self.phaseLabel.setFont(font)
        self.phaseLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phaseLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.phaseLabel.setObjectName("phaseLabel")
        self.verticalLayout.addWidget(self.phaseLabel)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gasHeatProgressBar = QtWidgets.QProgressBar(self.tab)
        self.gasHeatProgressBar.setProperty("value", 0)
        self.gasHeatProgressBar.setObjectName("gasHeatProgressBar")
        self.horizontalLayout_5.addWidget(self.gasHeatProgressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gasFlowProgressBar = QtWidgets.QProgressBar(self.tab)
        self.gasFlowProgressBar.setMaximum(10)
        self.gasFlowProgressBar.setProperty("value", 0)
        self.gasFlowProgressBar.setObjectName("gasFlowProgressBar")
        self.horizontalLayout_6.addWidget(self.gasFlowProgressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.evapHeatProgressBar = QtWidgets.QProgressBar(self.tab)
        self.evapHeatProgressBar.setMaximum(100)
        self.evapHeatProgressBar.setProperty("value", 0)
        self.evapHeatProgressBar.setObjectName("evapHeatProgressBar")
        self.horizontalLayout_7.addWidget(self.evapHeatProgressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.evapTempProgressBar = QtWidgets.QProgressBar(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evapTempProgressBar.sizePolicy().hasHeightForWidth())
        self.evapTempProgressBar.setSizePolicy(sizePolicy)
        self.evapTempProgressBar.setMinimum(70)
        self.evapTempProgressBar.setMaximum(500)
        self.evapTempProgressBar.setProperty("value", 70)
        self.evapTempProgressBar.setObjectName("evapTempProgressBar")
        self.horizontalLayout_8.addWidget(self.evapTempProgressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.suctTempProgressBar = QtWidgets.QProgressBar(self.tab)
        self.suctTempProgressBar.setMinimum(70)
        self.suctTempProgressBar.setMaximum(700)
        self.suctTempProgressBar.setProperty("value", 70)
        self.suctTempProgressBar.setObjectName("suctTempProgressBar")
        self.horizontalLayout_9.addWidget(self.suctTempProgressBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.suctHeatProgressBar = QtWidgets.QProgressBar(self.tab)
        self.suctHeatProgressBar.setMaximum(100)
        self.suctHeatProgressBar.setProperty("value", 0)
        self.suctHeatProgressBar.setObjectName("suctHeatProgressBar")
        self.horizontalLayout_10.addWidget(self.suctHeatProgressBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.pressureProgressBar = QtWidgets.QProgressBar(self.tab)
        self.pressureProgressBar.setMinimum(0)
        self.pressureProgressBar.setMaximum(50)
        self.pressureProgressBar.setProperty("value", 0)
        self.pressureProgressBar.setObjectName("pressureProgressBar")
        self.horizontalLayout_13.addWidget(self.pressureProgressBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.turboLabel = QtWidgets.QLabel(self.tab)
        self.turboLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.turboLabel.setMaximumSize(QtCore.QSize(24, 24))
        self.turboLabel.setBaseSize(QtCore.QSize(24, 24))
        self.turboLabel.setText("")
        self.turboLabel.setScaledContents(True)
        self.turboLabel.setObjectName("turboLabel")
        self.horizontalLayout_18.addWidget(self.turboLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.actionComboBox = QtWidgets.QComboBox(self.groupBox)
        self.actionComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.actionComboBox.setObjectName("actionComboBox")
        self.actionComboBox.addItem("")
        self.actionComboBox.addItem("")
        self.actionComboBox.addItem("")
        self.actionComboBox.addItem("")
        self.actionComboBox.addItem("")
        self.actionComboBox.addItem("")
        self.horizontalLayout.addWidget(self.actionComboBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.targetLabel = QtWidgets.QLabel(self.groupBox)
        self.targetLabel.setObjectName("targetLabel")
        self.horizontalLayout_14.addWidget(self.targetLabel)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.targetSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.targetSpinBox.setMinimum(8.0)
        self.targetSpinBox.setMaximum(500.0)
        self.targetSpinBox.setProperty("value", 300.0)
        self.targetSpinBox.setObjectName("targetSpinBox")
        self.horizontalLayout_14.addWidget(self.targetSpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.rateLabel = QtWidgets.QLabel(self.groupBox)
        self.rateLabel.setObjectName("rateLabel")
        self.horizontalLayout_15.addWidget(self.rateLabel)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.rateSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.rateSpinBox.setMinimum(1)
        self.rateSpinBox.setMaximum(360)
        self.rateSpinBox.setObjectName("rateSpinBox")
        self.horizontalLayout_15.addWidget(self.rateSpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.durationLabel = QtWidgets.QLabel(self.groupBox)
        self.durationLabel.setObjectName("durationLabel")
        self.horizontalLayout_16.addWidget(self.durationLabel)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.durationSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.durationSpinBox.setMinimum(1)
        self.durationSpinBox.setMaximum(1440)
        self.durationSpinBox.setObjectName("durationSpinBox")
        self.horizontalLayout_16.addWidget(self.durationSpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        spacerItem14 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem14)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.helpLabel = QtWidgets.QLabel(self.groupBox)
        self.helpLabel.setWordWrap(True)
        self.helpLabel.setObjectName("helpLabel")
        self.verticalLayout_10.addWidget(self.helpLabel)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem15)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startButton = QtWidgets.QPushButton(self.groupBox_2)
        self.startButton.setObjectName("startButton")
        self.gridLayout_2.addWidget(self.startButton, 0, 0, 1, 1)
        self.executeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.executeButton.setObjectName("executeButton")
        self.gridLayout_2.addWidget(self.executeButton, 0, 1, 1, 1)
        self.holdOnButton = QtWidgets.QPushButton(self.groupBox_2)
        self.holdOnButton.setObjectName("holdOnButton")
        self.gridLayout_2.addWidget(self.holdOnButton, 0, 2, 1, 1)
        self.turboOnButton = QtWidgets.QPushButton(self.groupBox_2)
        self.turboOnButton.setObjectName("turboOnButton")
        self.gridLayout_2.addWidget(self.turboOnButton, 0, 3, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.groupBox_2)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 1, 0, 1, 1)
        self.toSeqButton = QtWidgets.QPushButton(self.groupBox_2)
        self.toSeqButton.setObjectName("toSeqButton")
        self.gridLayout_2.addWidget(self.toSeqButton, 1, 1, 1, 1)
        self.holdOffButton = QtWidgets.QPushButton(self.groupBox_2)
        self.holdOffButton.setObjectName("holdOffButton")
        self.gridLayout_2.addWidget(self.holdOffButton, 1, 2, 1, 1)
        self.turboOffButton = QtWidgets.QPushButton(self.groupBox_2)
        self.turboOffButton.setObjectName("turboOffButton")
        self.gridLayout_2.addWidget(self.turboOffButton, 1, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.deviceButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.deviceButton.setChecked(True)
        self.deviceButton.setObjectName("deviceButton")
        self.deviceGroup = QtWidgets.QButtonGroup(WCryo)
        self.deviceGroup.setObjectName("deviceGroup")
        self.deviceGroup.addButton(self.deviceButton)
        self.gridLayout_3.addWidget(self.deviceButton, 0, 0, 1, 1)
        self.deviceLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.deviceLineEdit.setObjectName("deviceLineEdit")
        self.gridLayout_3.addWidget(self.deviceLineEdit, 0, 1, 1, 1)
        self.ipButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.ipButton.setObjectName("ipButton")
        self.deviceGroup.addButton(self.ipButton)
        self.gridLayout_3.addWidget(self.ipButton, 1, 0, 1, 1)
        self.ipLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.gridLayout_3.addWidget(self.ipLineEdit, 1, 1, 1, 1)
        self.editTimeout = QtWidgets.QLineEdit(self.groupBox_4)
        self.editTimeout.setObjectName("editTimeout")
        self.gridLayout_3.addWidget(self.editTimeout, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        spacerItem16 = QtWidgets.QSpacerItem(20, 132, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem16)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.connectButton = QtWidgets.QPushButton(WCryo)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_11.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(WCryo)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout_11.addWidget(self.disconnectButton)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.closeButton = QtWidgets.QPushButton(WCryo)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_11.addWidget(self.closeButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)

        self.retranslateUi(WCryo)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WCryo)

    def retranslateUi(self, WCryo):
        _translate = QtCore.QCoreApplication.translate
        WCryo.setWindowTitle(_translate("WCryo", "Cryostream"))
        self.label.setText(_translate("WCryo", "Sample temp"))
        self.sampleTempLabel.setText(_translate("WCryo", "000.00 K"))
        self.label_3.setText(_translate("WCryo", "Set Temp"))
        self.setTempLabel.setText(_translate("WCryo", "000.00 K"))
        self.label_2.setText(_translate("WCryo", "Gas Set Temp"))
        self.gasSetTempLabel.setText(_translate("WCryo", "000.00 K"))
        self.label_4.setText(_translate("WCryo", "Temp Error"))
        self.tempErrorLabel.setText(_translate("WCryo", "000.00 K"))
        self.label_5.setText(_translate("WCryo", "Status"))
        self.statusLabel.setText(_translate("WCryo", "000.00 K"))
        self.phaseLabel.setText(_translate("WCryo", "000.00 K"))
        self.label_6.setText(_translate("WCryo", "Gas Heat"))
        self.gasHeatProgressBar.setFormat(_translate("WCryo", "%p%"))
        self.label_7.setText(_translate("WCryo", "Gas Flow"))
        self.gasFlowProgressBar.setFormat(_translate("WCryo", "%p l/min"))
        self.label_8.setText(_translate("WCryo", "Evap Heat"))
        self.evapHeatProgressBar.setFormat(_translate("WCryo", "%p%"))
        self.label_9.setText(_translate("WCryo", "Evap Temp"))
        self.evapTempProgressBar.setFormat(_translate("WCryo", "%p K"))
        self.label_11.setText(_translate("WCryo", "Suct Temp"))
        self.suctTempProgressBar.setFormat(_translate("WCryo", "%p K"))
        self.label_10.setText(_translate("WCryo", "Suct Heat"))
        self.suctHeatProgressBar.setFormat(_translate("WCryo", "%p%"))
        self.label_12.setText(_translate("WCryo", "Line Pressure"))
        self.pressureProgressBar.setFormat(_translate("WCryo", "%p bar"))
        self.label_14.setText(_translate("WCryo", "Turbo Mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WCryo", "&Display"))
        self.groupBox.setTitle(_translate("WCryo", "Execute action"))
        self.label_13.setText(_translate("WCryo", "Phase"))
        self.actionComboBox.setToolTip(_translate("WCryo", "<html><head/><body><p>Phase of the cryostream.</p><p>Script function: <span style=\" font-weight:600;\">pylCryostream</span></p></body></html>"))
        self.actionComboBox.setItemText(0, _translate("WCryo", "Cool"))
        self.actionComboBox.setItemText(1, _translate("WCryo", "Ramp"))
        self.actionComboBox.setItemText(2, _translate("WCryo", "Plat"))
        self.actionComboBox.setItemText(3, _translate("WCryo", "Hold"))
        self.actionComboBox.setItemText(4, _translate("WCryo", "End"))
        self.actionComboBox.setItemText(5, _translate("WCryo", "Purge"))
        self.targetLabel.setText(_translate("WCryo", "Target Temp (K)"))
        self.rateLabel.setText(_translate("WCryo", "Ramp Rate (K/hour)"))
        self.durationLabel.setText(_translate("WCryo", "Duration (mins)"))
        self.helpLabel.setText(_translate("WCryo", "0"))
        self.groupBox_2.setTitle(_translate("WCryo", "Commands"))
        self.startButton.setText(_translate("WCryo", "Start cryo"))
        self.executeButton.setText(_translate("WCryo", "Execute now"))
        self.holdOnButton.setText(_translate("WCryo", "Hold"))
        self.turboOnButton.setText(_translate("WCryo", "Turbo on"))
        self.stopButton.setText(_translate("WCryo", "Stop cryo"))
        self.toSeqButton.setText(_translate("WCryo", "To sequence"))
        self.holdOffButton.setText(_translate("WCryo", "End Hold"))
        self.turboOffButton.setText(_translate("WCryo", "Turbo off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WCryo", "Comm&and"))
        self.groupBox_4.setTitle(_translate("WCryo", "Device"))
        self.deviceButton.setText(_translate("WCryo", "Device &name"))
        self.deviceLineEdit.setText(_translate("WCryo", "/dev/ttyS0"))
        self.ipButton.setText(_translate("WCryo", "&CryoProxy (host:port)"))
        self.ipLineEdit.setText(_translate("WCryo", "localhost:7900"))
        self.editTimeout.setText(_translate("WCryo", "3000"))
        self.label_15.setText(_translate("WCryo", "Communication timeout"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WCryo", "&Settings"))
        self.connectButton.setText(_translate("WCryo", "Connect"))
        self.disconnectButton.setText(_translate("WCryo", "Disconnect"))
        self.closeButton.setText(_translate("WCryo", "&Close"))

from . import resources_rc
