# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/python/auxygen/auxygen/gui/ui/ui_wseq.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WSeq(object):
    def setupUi(self, WSeq):
        WSeq.setObjectName("WSeq")
        WSeq.resize(692, 424)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/macro"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WSeq.setWindowIcon(icon)
        WSeq.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(WSeq)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(WSeq)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.actionsComboBox = QtWidgets.QComboBox(self.groupBox)
        self.actionsComboBox.setObjectName("actionsComboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/delay"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsComboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cryo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/blower"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/lakeshore"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsComboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iseg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsComboBox.addItem(icon5, "")
        self.verticalLayout_4.addWidget(self.actionsComboBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.actionSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.actionSpinBox.setMinimum(1)
        self.actionSpinBox.setMaximum(3600)
        self.actionSpinBox.setObjectName("actionSpinBox")
        self.horizontalLayout_3.addWidget(self.actionSpinBox)
        self.addActionButton = QtWidgets.QPushButton(self.groupBox)
        self.addActionButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addActionButton.setIcon(icon6)
        self.addActionButton.setObjectName("addActionButton")
        self.horizontalLayout_3.addWidget(self.addActionButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.downButton = QtWidgets.QPushButton(WSeq)
        self.downButton.setText("")
        self.downButton.setObjectName("downButton")
        self.horizontalLayout_2.addWidget(self.downButton)
        self.upButton = QtWidgets.QPushButton(WSeq)
        self.upButton.setText("")
        self.upButton.setObjectName("upButton")
        self.horizontalLayout_2.addWidget(self.upButton)
        self.removeButton = QtWidgets.QPushButton(WSeq)
        self.removeButton.setText("")
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_2.addWidget(self.removeButton)
        self.clearButton = QtWidgets.QPushButton(WSeq)
        self.clearButton.setText("")
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(WSeq)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.totalTimeLabel = QtWidgets.QLabel(WSeq)
        self.totalTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.verticalLayout_2.addWidget(self.totalTimeLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(WSeq)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(WSeq)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon7)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(WSeq)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/stop"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon8)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.seqTreeWidget = QtWidgets.QTreeWidget(WSeq)
        self.seqTreeWidget.setDragEnabled(False)
        self.seqTreeWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.seqTreeWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.seqTreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.seqTreeWidget.setColumnCount(1)
        self.seqTreeWidget.setObjectName("seqTreeWidget")
        self.seqTreeWidget.header().setVisible(True)
        self.verticalLayout_3.addWidget(self.seqTreeWidget)
        self.experimentProgressBar = QtWidgets.QProgressBar(WSeq)
        self.experimentProgressBar.setProperty("value", 0)
        self.experimentProgressBar.setObjectName("experimentProgressBar")
        self.verticalLayout_3.addWidget(self.experimentProgressBar)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(WSeq)
        QtCore.QMetaObject.connectSlotsByName(WSeq)

    def retranslateUi(self, WSeq):
        _translate = QtCore.QCoreApplication.translate
        WSeq.setWindowTitle(_translate("WSeq", "Sequences"))
        self.groupBox.setTitle(_translate("WSeq", "Add action"))
        self.actionsComboBox.setItemText(0, _translate("WSeq", "Delay (sec)"))
        self.actionsComboBox.setItemText(1, _translate("WSeq", "Cryo Hold"))
        self.actionsComboBox.setItemText(2, _translate("WSeq", "Euro Temp"))
        self.actionsComboBox.setItemText(3, _translate("WSeq", "Lakeshore Temp"))
        self.actionsComboBox.setItemText(4, _translate("WSeq", "Iseg Voltage"))
        self.totalTimeLabel.setText(_translate("WSeq", "Total time: \n"
"0 min"))
        self.runButton.setText(_translate("WSeq", "Run"))
        self.stopButton.setText(_translate("WSeq", "Stop"))
        self.seqTreeWidget.headerItem().setText(0, _translate("WSeq", "Actions"))

from . import resources_rc
