# automatically generated by the FlatBuffers compiler, do not modify

# namespace: lumby_fbs

# /// http://blog.bitfinex.com/api/websocket-api-update/
# /// "We are splitting the public trade messages into two: a “te” message which
# /// mimics the current behavior, and a “tu” message which will be delayed by 1-2
# /// seconds and include the tradeId. If the tradeId is important to you, use the
# /// “tu” message. If speed is important to you, listen to the “te” message. Or of
# /// course use both if you’d like."
class BfxTradeType(object):
# /// "tu"
    TradeUpdate = 0
# /// "te"
    TradeEntry = 1

